### ISSUE TITLE
app has stopped

### ISSUE THREAD

**Issue by spyexe** [DrKLO/Telegram#1001]
Hello after I compile telegram Dev and emulator working I open the app it said 
telegram has stopped what is the solution???
I can not open the app

**Comment by spyexe** [comment]
I use android 5 in the emulator

**Comment by DrKLO** [comment]
How we should help you, if you even didn't provide call stack?

**Comment by spyexe** [comment]
after I success compile without any changes in source code it show app has stopped

**Comment by aliakbari** [comment]
me too
