### ISSUE TITLE
I have this problem during the launching of the application. 

### ISSUE THREAD

**Issue by aansweer** [DrKLO/Telegram#1003]
I haven't modyfied anithing yet.

Error:A problem was found with the configuration of task ':TMessagesProj:packageDebug'.

File 'C:\Users\Mac\Desktop\Tutto\Programmi Android\Telegram-master\TMessagesProj\config\debug.keystore' specified for property 'signingConfig.storeFile' does not exist.

**Comment by tsubus** [comment]
Read the error message...you have to create the keystore, or it won't be able to sign the apk

**Comment by aansweer** [comment]
How can i make it?

**Comment by tsubus** [comment]
http://lmgtfy.com/?q=android+create+keystore

**Comment by aansweer** [comment]
it is not the key problem i think, because i tryed to creare a android keystore in named buld.jks, but it does't works, the problem is this;

File 'C:\Users\Mac\Desktop\Tutto\Programmi Android\Telegram-master\TMessagesProj\config\debug.keystore' specified for property 'signingConfig.storeFile' does not exist.


Can you please send me the remaining file at this email adress: aansweer@yahoo.it

**Comment by DrKLO** [comment]
@aansweer why you can't rename file to debug.keystore and place it to 'C:\Users\Mac\Desktop\Tutto\Programmi Android\Telegram-master\TMessagesProj\config\'  or edit build.gradle file?
Every developer should have his own keystore file, in other way it will be security issue.

**Comment by aansweer** [comment]
Ok today I'll try. One more thing, how can I change the package name?

**Comment by DrKLO** [comment]
@aansweer use search on github, there was a lot of this questions.
