### ISSUE TITLE
Question about Pull Requests and Commits

### ISSUE THREAD

**Issue by jomo** [DrKLO/Telegram#1007]
I have noticed that pull requests are not merged when accepted, but instead they are added to bulky commits that usually have *a lot* of changes. Sometimes so many that GitHub won't even display the full diff.

* Why are these not merged as usual?
* Why are changed not split into separate commits?

Also, most of the commits have very bad messages such as "Bug fixes" or "Update to x.x.x".
Sometimes they have a few more lines that briefly sum up what was touched, but it's rather uncommon.

Is there a good reason for this? I hope this can be improved in future :)

**Comment by tsubus** [comment]
I agree with everything, also because this way is not just very confusing, but it also doesn't give credit where credit is due. A better commit standard should be followed, for example like it's done by major custom Android ROM's.

**Comment by DrKLO** [comment]
1) Because almost all pull request requires to be edited before merge.
2) Because I'm doing all local changes in a single commit.

I will not separate anything because it's a way that I like to work, since I'm the onliest developer of the app and I just don't need it.

@tsubus I always give credits to author of patches in commit description.

**Comment by tsubus** [comment]
@DrKLO I respect your decision, you're doing a great job with this app, you should not change if you don't feel like it. For point 1) a gerrit instance would be helpful, but I guess it would be a little bit overkill since you're basically the only contributor. Thanks for you work, in any case :+1:

**Comment by jomo** [comment]
For point 1: Why don't you merge PRs and *then* edit them in another commit?
You could also ask PR authors to make the required changes before merging.

For point 2: Is there a specific reason you prefer to make a bunch of changes in a single commit?
This sort of ignores the whole idea of version control / git.

----

> I'm the onliest developer of the app

Well, you're the main author but you're not the *only* contributor. In fact, there are a bunch of other people who have contributed code via Pull Requests. They just don't show up on [the contributors page](https://github.com/DrKLO/Telegram/graphs/contributors) because their commits aren't included.
I try to understand your way to work, but you're just making it harder for others to follow changes or contribute.

**Comment by jomo** [comment]
FTR: there has been some discussion and advice [in #76](https://github.com/DrKLO/Telegram/pull/76#issuecomment-34425677). Sadly most of it was ignored.
