### ISSUE TITLE
Please reduce the empty space between the Emojis on the Emoji drawer and use the space to increase the size of the Emojis on the Emoji drawer

### ISSUE THREAD

**Issue by wp9015362** [DrKLO/Telegram#1011]
@DrKLO :

As already mentioned in https://github.com/DrKLO/Telegram/issues/843, WhatsApp for Android apparently has received a new material design user interface with the latest update.

The Emoji drawer in the new WhatsApp material design user interface now looks like this:

http://www.androidpolice.com/wp-content/uploads/2015/04/nexus2cee_whatsapp-material-7.png ([Source](http://www.androidpolice.com/2015/04/14/hands-on-whatsapp-goes-material-with-cool-animations-fabs-and-lots-of-purty/))

![Image](http://www.androidpolice.com/wp-content/uploads/2015/04/nexus2cee_whatsapp-material-7.png)

And this is how it currently looks like in Telegram:

https://telegram.org/file/811140073/1/IP83JaSL9H8/4f056c95a1cd5f0fec ([Source](https://telegram.org/blog/stickers))

![Image](https://telegram.org/file/811140073/1/IP83JaSL9H8/4f056c95a1cd5f0fec)

What I really like better about the WhatsApp for Android Emoji drawer is not just [the fact that it's background is brighter](https://github.com/DrKLO/Telegram/issues/843), but also that there is less empty space between the Emojis, which makes it possible for the Emojis to be bigger in size and therefore have better visibility.

In Telegram for Android, there is more empty space between the Emojis on the Emoji drawer and they appear smaller than on the WhatsApp for Android Emoji drawer.

Both on the WhatsApp for Android Emoji drawer as well as on the Telegram for Android Emoji drawer there are eight Emojis being displayed in a row, but the WhatsApp for Android Emoji drawer still manages to have bigger Emojis because there is not as much empty space between the Emojis as on the Telegram for Android Emoji drawer.

It's not a big difference, but noticeable in direct comparison.

It would be nice if the Emojis were a bit bigger.

So, could you please reduce the empty space between the Emojis on the Telegram for Android Emoji drawer and use the space to increase the size of the Emojis?

It would be much appreciated.

Regards

**Comment by tsubus** [comment]
I honestly don't see any difference, save for the background.

**Comment by wp9015362** [comment]
> @tsubus wrote:
> 
> I honestly don't see any difference, save for the background.

Then have a look at the following screenshots:

Telegram with native 1080 pixels width:

![Image](https://cloud.githubusercontent.com/assets/7558360/7144199/350b8dfc-e2e4-11e4-93b8-1d17a6edaeae.png)

According to my measurements, each Emoji is 80x80 pixels. And there are 57 pixels of emtpy space between each Emoji in width and 57 pixels of emtpy space between each Emoji in height.

Now compare that with WhatsApp (native 1440 pixels in width downscaled to 1080 pixels in width from [screenshot mentioned in first post](http://www.androidpolice.com/wp-content/uploads/2015/04/nexus2cee_whatsapp-material-7.png) for comparison):

![whatsapp](https://cloud.githubusercontent.com/assets/7558360/7144294/e085c1ac-e2e4-11e4-8b3e-3dcd4bd6a01d.png)

According to my measurements, each Emoji is 87x87 pixels in size. And there are only 46 pixels of emtpy space between each Emoji in width and only 46 pixels of emtpy space between each Emoji in height.

So, as I said, there ist not a big difference, but there is a difference, and it's noticeable.

So there is some room for improvement for Telegram for Android (IMHO).

PS:

By the waym by comparing the the screenshots above, it becomes really noticeable, that the Emojis in Telegram for Android do suffer from image compression, as reported in:

https://github.com/DrKLO/Telegram/issues/914 

Regards

**Comment by wp9015362** [comment]
@DrKLO :

Thank you very much for having fixed this with v2.8.0.

:+1: 

Regards
