### ISSUE TITLE
Passord Bug

### ISSUE THREAD

**Issue by hamiltoncneto** [DrKLO/Telegram#1014]
Hi, I activated the feature that ask a password to access telegram app and when I set a timeout to autolock the app, I receive a screen that shows the password field to put my password to unlock. But if I enter the password without select the field, my password is inserted on chat not in the password field. I see this bug many times in my computer. I'm using a Mackbook pro with Yosemite.

Thank you.

**Comment by DrKLO** [comment]
You mean Telegram client for Mac OS?

**Comment by hamiltoncneto** [comment]
Hi, DrKLO!

Yes, I just forgot to say that.

Bye

**Comment by DrKLO** [comment]
Mac OS X client developer said that it should be fixed in last release.
