### ISSUE TITLE
Enhancements and new features

### ISSUE THREAD

**Issue by fduraibi** [DrKLO/Telegram#102]
##### Here is a list of thing that I believe need to be fixed/implemented so people will accept Telegram as a replacement for other messaging apps like Whatsapp, Line, Chaton...etc:
- ~~When sharing Youtube videos (directly from Yourtube app or if it was received in whatsapp) Telegram will only post the URL and will strip the video title. (it would be also good if Telegram can show a small thumbnail of the video like whatsapp does).~~
- When pasting a message that has been copied from Whatsapp the Emojies in that message will show like text emojis (the ones embedded in the font) and Telegram will not replace them with the picture ones.
- Telegram doesn't allow creating messages with extra spaces and new lines, instead it will trim all consecutive newlines or spaces into 1 newline or space (i think that is done by the HTML object). This behavior sometimes breaks the message formatting specially if the message has ascii artwork.
- Current message size is small (only 2048), (whatsapp has unlimited message size but that is not good since you can cause a denial of service by sending a huge message that can crash someones phone) a larger size, maybe 8K or 16K should be reasonable and still not too big.
- Currently Telegram processes only 50 emojis in each message the rest will default to how the OS handles them. I am not sure why there is a limit if the message size is already limited. I increased mine to 200 and I didn't notice any effect on performance.

##### This is a list of new additions that I would love to see in Telegram:
- ~~Support of animated pictures, maybe user attached GIF or AnimEmoji (like Chaton and Line).~~
- Support message formatting, using HTML tags or simple tags such as using before a line to make it bold.
- When attaching a photo allow the user to select between attaching a resized and compressed version (for fast transfer) and this can be the default or to send the photo as it is (a feature that will be very useful when you want to share a photo with others and you want to maintain its resolution and size)

**Comment by roko-p** [comment]
@fduraibi Closed because all the remaining feature requests have been rejected or they are referenced in other issues?

Any issues for those custom emojis/emoticons?
