### ISSUE TITLE
Multi Account support

### ISSUE THREAD

**Issue by luksi-reiku** [DrKLO/Telegram#1021]
I would want to use other accounts without having to log out, for example for sharing a phone with a friend without a smartphone so he can use telegram too.

**Comment by DrKLO** [comment]
It will require a lot of changes in current code, so it will be easier to write new application from scratch. So i will not implement this.

**Comment by devianpctek** [comment]
As an alternative you can use a different client if you want to lend it to your friend, Plus messenger is a good client too

**Comment by davux** [comment]
Lollipop is experimenting a multi-user feature. This way you can configure Telegram (and any other app, for that matter) for different contexts. For example separate work and personal profiles, or use a Guest profile to lend your phone to a friend.
