### ISSUE TITLE
Feature request: Subscribable Public Read-only Broadcasts

### ISSUE THREAD

**Issue by mohsenrf** [DrKLO/Telegram#1025]
Right now there are no public groups or broadcasts in telegram. 
Wouldn't it be nice and very useful if there was Broadcasts that were public and you can subscribe to if you like (anonymously of course) and receive newsletters, files, pictures and all sorts of great content by different publishers right in your telegram app? 
(That would easily replace the need for a bunch of other apps and technologies like Email Newsletters, RSS Feeds, etc.).

**Comment by AUDI-A4** [comment]
+1 nice idea.

**Comment by luksi-reiku** [comment]
+1

**Comment by DrKLO** [comment]
There is no API for that.

**Comment by eckcon** [comment]
Maybe there will be one one day ;-)
https://medium.com/@eckstein/five-features-that-would-make-telegram-even-more-awesome-d6a755f97bbe
