### ISSUE TITLE
[Feature Request/Bug?] File names of downloaded Telegram Files

### ISSUE THREAD

**Issue by Mindstormer619** [DrKLO/Telegram#1029]
On Telegram Desktop, downloading a file, like this one:

![image](https://cloud.githubusercontent.com/assets/441849/7312565/871fb16c-ea6a-11e4-9da6-1df9b5196fad.png)

... gives this file:

![image](https://cloud.githubusercontent.com/assets/441849/7312573/ae98d7be-ea6a-11e4-86cb-eb42e4590832.png)

Meanwhile, on Telegram for Android, downloading any file gives this:

![screenshot_2015_04_24_10_17_36](https://cloud.githubusercontent.com/assets/441849/7312669/43ce4326-ea6d-11e4-9c27-8079507385c5.jpg)

This makes it impossible to search for a specific file when not connected to the internet (when I cannot do a normal Telegram search, as my internet connection is often _really_ spotty), Also, recent files opened in apps show that weird long coded file name, so I find it difficult to switch among opened books and stuff. Why would this file naming system even be in place? Why not just name the file based on what it's called in the chat window?

**Comment by DrKLO** [comment]
Feature. There can be a lot of files with the same name, so app will be unable to understand which file belongs to which message. I know you can say that I can store somewhere this information, but you can re-login and all this information will be lost and you will have to download all files again.
So I don't think that this file names will be changed someday.

**Comment by Mindstormer619** [comment]
You could put a unique code as a suffix to the file name, like a.txt could
now be a_5764533.txt or whatever. We'd still be able to run searches
offline and from other apps while having the uniqueness feature. Plus you
could calculate computed file names because you know what the original file
was named.

**Comment by AUDI-A4** [comment]
agreed @mindstormer619

**Comment by Mindstormer619** [comment]
@AUDI-A4 Thanks, see I just don't see why you would want to use the current implementation. If the app requires this coded file name so that it can uniquely compute its existence, then it can also do the same with a suffix preceded by a delimiter. The current implementation makes Telegram nearly impossible to use for file sharing (which is a major use case in the first place) unless you are connected to the internet, in which case I might as well not save the file at all as I really cannot search for it on my device anyway. At least provide an option to download it to some other location with a file name of my choosing. Telegram might not count the file that's downloaded, but hey, at least I can _use_ it on my device now. 

@DrKLO I would classify this as more of a bug than a suggested feature. After all, without this it's pretty useless to download files if I still require the internet to find them on my own device. Telegram's search feature does not work offline either. This is quite deal breaking to the whole idea of downloading files, and is therefore a bug. 

I move for the reopening of this issue.

**Comment by DrKLO** [comment]
@Mindstormer619 and than I should get all files in current dir and search files with prefix? I don't think so, it will be performance issue.

**Comment by Mindstormer619** [comment]
@DrKLO At least provide a Save As option where we can save the file to the folder of our choice with the original file name. Telegram needn't identify the file as downloaded within the chat as the file is not present within Telegram's own folder. But at least I can find my own downloaded file on my own system offline, which is the whole point of downloading a file in the first place. 

Will searching using a suffix of the file name instead of the entire name really make that much of a performance impact? Interesting, I didn't think it would affect it that much. You're the developer and you know the underlying workings of this application better than anyone. But I've used this app long enough that I know this is a major shortcoming. I can't find my own downloaded files, man! Frankly, I don't care if Telegram knows that the file is downloaded or not. I want to be able to do what I want with my own downloaded files, with minimal hassle. I don't think that's too much to ask.

**Comment by Mindstormer619** [comment]
Any updates on this? I have put up a new issue with a "Save As" option feature request (as that would solve this problem for me, as well as being different enough that it warranted its own issue) in #1054.

By the way, awesome job on the latest update :smile:

**Comment by anawim** [comment]
I want this since day one and asked many times via Telegram support account. 
Plus I don't know why but in order to play (with proper artist and title displayed) the mp3 files I receive I have to move the files to another directory (which is really annoying) no matter what app I'm using to play them.
