### ISSUE TITLE
There should be no of contacts in Telegram

### ISSUE THREAD

**Issue by AUDI-A4** [DrKLO/Telegram#1037]
**In the first screen**

It is showing contacts only not no of contacts
![photo_2015-04-29_16-32-52](https://cloud.githubusercontent.com/assets/7442148/7389704/233ac858-ee8e-11e4-90fd-470ebd11ac4d.jpg)

**In the seconds screen**
Suppose i have 20 contacts in my list. It should show 20 contacts not contacts text alone like whatsapp
![ddsg](https://cloud.githubusercontent.com/assets/7442148/7389710/3f3fc72e-ee8e-11e4-9a0e-933572098f1f.jpg)

**Comment by DrKLO** [comment]
Don't create issues about beta versions.

**Comment by AUDI-A4** [comment]
@drklo thanks i agreed.But can you implement to show number of contacts like whatsapp
