### ISSUE TITLE
Webp stickers

### ISSUE THREAD

**Issue by ferezvi** [DrKLO/Telegram#1041]
There's a problem sending personal stickers from telegram android (webp format, transparent layer), it works fine from tdesktop see screenshots, send it as a file and as a image same result. (tested moto g 1&2,  samsung galaxy ace and tablet xperia s)
![android](https://cloud.githubusercontent.com/assets/10686215/7418514/0e161dfa-ef34-11e4-8b8c-11e4188c43b4.png)
![tdesktop](https://cloud.githubusercontent.com/assets/10686215/7418515/0e226164-ef34-11e4-95bb-27bbdd5786d2.png)

**Comment by muava12** [comment]
Is this version 2.8.0 ?

**Comment by muava12** [comment]
Older than version 2.8.0 still can't send webp as sticker

**Comment by ferezvi** [comment]
Play store only has v2.7.0(492) when i'll get 2,8 i'll check it again thanks

**Comment by ferezvi** [comment]
v.2.8 solve the problem thanks great job¡¡
