### ISSUE TITLE
Empty navigation drawer in phone input activity

### ISSUE THREAD

**Issue by DanilinEgor** [DrKLO/Telegram#1043]
On phone input activity I can swipe from left to right and empty navigation drawer will be opened.
![xz54dsaqyva](https://cloud.githubusercontent.com/assets/1484280/7425592/1a388c7a-efbc-11e4-83ce-5be94ad13586.jpg)
![4p6ggbfaxzc](https://cloud.githubusercontent.com/assets/1484280/7425591/1a38237a-efbc-11e4-91d9-493d09e18dbc.jpg)

**Comment by DrKLO** [comment]
steps to reproduce?

**Comment by DrKLO** [comment]
Oh, figured out, i need to open country picker. Thanks, will be fixed in next update.
