### ISSUE TITLE
No info is showing when sending media or file

### ISSUE THREAD

**Issue by AUDI-A4** [DrKLO/Telegram#1045]
Whenever i am recording an audio then others can see my status.But for uploading media and file then it is still showing online to others.How to get it working for media or file.Please explain

**Comment by DrKLO** [comment]
And it shouldn't. It's not implemented yet. Only viewing supported for now.

**Comment by AUDI-A4** [comment]
so it wont show uploading media like recording status to others as it is not implemented.what do you mean by viewing supported

**Comment by AUDI-A4** [comment]
@DrKLO Why it is mentioned over there in changelog  for sending media as others cannot see my status for sending media instead of online while i am sending media.Can you explain please.
