### ISSUE TITLE
Auto download long audio messages

### ISSUE THREAD

**Issue by Christilut** [DrKLO/Telegram#1047]
So I somehow recorded an hour of my phone being in my pants which it promptly sent over Telegram (this is a seperate issue). The message got auto downloaded at the phone of other users. Message being about 58 minutes which isn't very good if a user is wasting his mobile data.
Audio being on by default for mobile data...

Perhaps audio download should not be on by default for mobile data OR only auto download short messages (< 1 minute perhaps).

**Comment by DrKLO** [comment]
For now only audio message which less then 10mb will be automatically downloaded.
