### ISSUE TITLE
Sticker suggestions should be removed now that Emoji drawer has it's own sticker category

### ISSUE THREAD

**Issue by wp9015362** [DrKLO/Telegram#1051]
@DrKLO :

When stickers were introduced to Telegram, the stickers were suggested when using certain Emojis, as described over there:

https://telegram.org/blog/stickers

But since v2.8.0, the Telegram for Android Emoji drawer now has it's own sticker category to manually choose from and insert the stickers.

So, IMHO, the sticker suggestions should be removed.

Could you please remove the suggestions?

Regards

**Comment by auchri** [comment]
Let's wai for the stickers revolution: https://telegram.org/blog/captions-places#android-goodies :)

**Comment by DrKLO** [comment]
No, I will not remove it.

**Comment by wp9015362** [comment]
> @DrKLO wrote:
> 
> No, I will not remove it.

IMHO that doesn't make too much sense, because:

The blog post said:

> https://telegram.org/blog/stickers
> 
> [...] Telegram stickers are grouped around emotions, not characters. They do not clutter the interface, but are shown only when they are relevant – you will see a list of emotionally corresponding stickers whenever you start a message with an emoji. [...]

But now they are not shown only when they are relevant. They now have their own category in the Emoji drawer. So the suggestions should be removed IMHO.
