### ISSUE TITLE
Switching between keyboard and Emoji drawer no longer happens instantaneously

### ISSUE THREAD

**Issue by wp9015362** [DrKLO/Telegram#1052]
@DrKLO :

When using Telegram for Android v2.7 on Android 4.4 KitKat, switching between the keyboard and the Emoji drawer happended instantaneously.

The keyboard and the Emoji drawer came up immediately without any animations.

But with Telegram for Android v2.8.0 on Android 5.0 Lollipop, the switch no longer happens instantaneously.

The keyboard now fades in and out / blends over the Emoji drawer with an awkward animation.

Not sure if this was introduced by the upgrade from Telegram for Android v2.7 to Telegram for Android v2.8.0 or if it was introduced by the upgrade from Android 4.4 KitKat to Android 5.0 Lollipop.

But with Telegram for Android v2.7 on Android 4.4 KitKat switching between the keyboard and the Emoji drawer definitely looked better than with Telegram for Android v2.8.0 on Android 5.0 Lollipop.

Is there any chance you could remove that animation and make switching between the keyboard and the Emoji drawer be instant again (i.e. without animation)?

Regards

**Comment by DrKLO** [comment]
It's another workaround for keyboard bug on android 5.x. When heads-up notification is shown, it takes focus and resize everything on screen, so emoji panel moves up. Previously emoji panel was above everything, for now I'm closing keyboard when emoji panel is showed.

https://github.com/DrKLO/Telegram/issues/793
https://github.com/DrKLO/Telegram/issues/981

I think strange animation is better when it's above everything else.
