### ISSUE TITLE
update v. 2.8.0

### ISSUE THREAD

**Issue by mosqueiro** [DrKLO/Telegram#1053]
Where is the update v. 2.8.0 ?

**Comment by mosqueiro** [comment]
Because you have closed the topic ?

**Comment by mokhtarabadi** [comment]
Why we cannot access the latest source of Telegram android project?

**Comment by AUDI-A4** [comment]
@mokhtarabadi When developer wants you to access the latest source then you can access otherwise you cannot

**Comment by DrKLO** [comment]
I can't understand, why you just can't wait until I will fix all crashes and bugs? I shouldn't post any source code after release immediately.

**Comment by mosqueiro** [comment]
Now I understand @DrKLO on the indexing of crashs . Thank you very much.
