### ISSUE TITLE
[Feature Request] "Save As" option for files

### ISSUE THREAD

**Issue by Mindstormer619** [DrKLO/Telegram#1054]
I had opened #1029 recently because it was frustrating to find files downloaded to the system because of Telegram's random-looking naming scheme for downloaded files into the default location, pretty much beating the purpose of downloading the file in the first place. This file naming apparently cannot be corrected due to certain performance issues.

Hence here's a new, related feature request. The user can save the file to a **location of his choice** with a **user-provided file name**. Note that this is **NOT the default save option** and will be accessible by using the three vertical dots (options icon) on a file in the chat window. By default, the file name selected is the _file name visible in the chat window_ (the _original file name_ as uploaded by the sender) and not a random string of gibberish. The location, once selected by the user, persists in the application data and hence the app provides the same folder to save in the next time the user does the "Save As" option on a file.

Note that by doing so (using _Save As_ instead of default save), Telegram will not denote the file as "downloaded" as it has not been downloaded to the default location. That is, Telegram **continues to show** this:

![screenshot_1430518375](https://cloud.githubusercontent.com/assets/441849/7438181/8ae0f680-f07d-11e4-8de5-9e3ab9924111.jpg)

... instead of this:

![photo_2015-05-02_03-29-01](https://cloud.githubusercontent.com/assets/441849/7438055/d2d8ce6a-f07b-11e4-9be7-829eacc37b8a.jpg)

And that's perfectly fine. I just want to be able to search for my files while I'm not connected to the internet. If I had to be connected to the internet every time I wanted to find a file, I would rather not download it and send a web link to it or something. The whole point of saving a file to your device is so that you can find and use it later without being connected to an external network. I don't know why this hasn't been implemented yet - this is pretty much the only major design flaw I find with Telegram today.

**Comment by AUDI-A4** [comment]
save as option was there in previous version of telegram.You could have saved your files by tapping onto filenames.But they removed it since 3 or 4 updates

**Comment by Mindstormer619** [comment]
@AUDI-A4 They probably removed it because Telegram was not able to keep a track of the files that were downloaded, as @DrKLO said in #1029. But what I am suggesting is that Telegram only needs to keep a track of the files that are downloaded using the default option (by clicking on the file directly and resulting in a coded non-human-friendly filename). The files that are downloaded using the _Save As..._ option from the popup menu will be saved to a location of your choice. Telegram need not keep a track of them or whether they are downloaded or not.

A simple `Toast` that pops up to say that the file has completed downloading would be enough.

**Comment by Mindstormer619** [comment]
With an update somewhere, there's a feature to Save To Downloads *after* the file has been downloaded normally. Though I'm not entirely happy as this saves two copies of the file, I'm closing this issue for now. @DrKLO thanks.
