### ISSUE TITLE
Change name of folder

### ISSUE THREAD

**Issue by Nekbakht** [DrKLO/Telegram#1055]
After install telegram app on android it create folder in sdcard Telegram 
I wanna change folder name. How i can do it?

**Comment by Mindstormer619** [comment]
I don't really think you can. As far as I know, this feature has not been implemented.

**Comment by friend4chams** [comment]
This was already discussed check this:

https://github.com/DrKLO/Telegram/issues/985

**Comment by Mindstormer619** [comment]
Nah, he wants to do this on the default installed app. Not an app he is developing.
