### ISSUE TITLE
How to add new chat background to telegram?

### ISSUE THREAD

**Issue by Nekbakht** [DrKLO/Telegram#1058]
I wanna add new picture for chat background 
How i can do this?

**Comment by Mindstormer619** [comment]
The button on the leftmost side here:

![](http://s11.postimg.org/im3m07clf/Screenshot_2015_05_26_09_08_01.png)

That button will allow you to open from gallery. Please close the issue now.

**Comment by davux** [comment]
@nekbakht: This is not a user forum. :) Issues are for reporting a problem on the software or for requesting a new feature.
