### ISSUE TITLE
Increase group size

### ISSUE THREAD

**Issue by shiblymeeran** [DrKLO/Telegram#1059]
We have groups that are flooding with members. 200 is very low in limits. I understand that there's nothing that can be done from client side. If you could take it as a request to the API dev team, I'd be happy. Or just guide me with the same.

**Comment by shiblymeeran** [comment]
I would be good to have 1000 or more.

**Comment by AUDI-A4** [comment]
@shiblymeeran is not it funny to have group limit of 1000 or more.Nobody wants to join this app because of whatsapp.So what is use to have 1000 members in one group without having much people over here

**Comment by shiblymeeran** [comment]
No, they do. Telegram is beautiful when it comes to groups. There is a group that we have where there are unrelated members. But we share funny stuff like memes. This group is flooding. Telegram gives privacy so that those who don't have the contact of other members won't know their phone numbers.. So it is better we have a bigger group size.

**Comment by java-boy** [comment]
I think that would be great if we could be able to have members more than 200 in one group.
we have a group in telegram that members are sharing products related to building construction, we sure need to have more than 200 members in one group!
Now the group capacity is full and no one can add more members.
I think the best choice is to have an option to let the group creator or group admin to set the group size.
then there will be freedom and no restriction!
Best wishes.

**Comment by edmael** [comment]
Agreed.

This restriction should be removed or at least there should be room for more people.

**Comment by nvx** [comment]
I have also hit the 200 user limit and would love for the limit to either be removed, or increased to at least 1000.

The current main alternative is to use Slack for such large groups, but there's a lot of overhead in that and it's really not suitable for more ad-hoc groups which is where Telegram really excels below the 200-user limit!

**Comment by brettus78** [comment]
Hi,

We are a large gaming community and are struggling to cater to the numbers with TG.
Most of the community love TG and find Slack to bloaty and heavy but due to room number restrictions, they are looking to move to Slack.
If you increase the number to 1000 or more, our choice will be simple - TG.

Please implement this increase.

**Comment by brunosan** [comment]
:+1: for this.

**Comment by FLamparski** [comment]
:+1: to this. That or you lose a bunch of us to Slack or :shudder: IRC.

**Comment by arashmidos** [comment]
:+1:

**Comment by mkg71** [comment]
Please raise the max user limit per channel.

**Comment by bkerensa** [comment]
Please raise it to 1000.... let groups decide how big they want to be

**Comment by mautematico** [comment]
:+1:

**Comment by uira** [comment]
We get 207 members in a group. Did you get anything similar?

https://twitter.com/uira/status/626547522060816384

**Comment by farsadf** [comment]
Yep, It would be better to increase the limit or at least explain why you 've got this limit.

**Comment by Fruchle** [comment]
Please raise the group size limit to 1000 members.

**Comment by adrenalinenz** [comment]
An increase in member limits to at least 500 would be beneficial to a number of Telegram groups I'm in! :)

**Comment by prky** [comment]
I'm in several groups that are constantly hitting the 200 member limit - please raise to at least 500, preferably 1000.

**Comment by cincauhangus** [comment]
We was told that Malaysia's group chat load over the public holidays is almost equivalent to the last DDOS attack. Please increase the limit so we can let other countries be the benchmark. :P

**Comment by DrKLO** [comment]
This is server side. Discussing anything about it in android client repo is useless.

**Comment by nvx** [comment]
Is there a more appropriate location where this feature can be requested? There is clearly demand for it.

**Comment by java-boy** [comment]
Please tell us where is the location that we can ask to add this feature?
Kindest regards.

**Comment by mirhl** [comment]
See [here](https://github.com/DrKLO/Telegram/issues/1144#issuecomment-110343984)
