### ISSUE TITLE
password for chats & approve security

### ISSUE THREAD

**Issue by 1pilo** [DrKLO/Telegram#106]
- It would be great if someone could set a password for his account, so that there can write only his friends or user with the password/key

- Then It would be great if theres the option to compare keys/fingerprints before a secure chat starts. Until now the chat simply starts without asking me or giving me a notification (only small lock in the left top corner).

Thats it, thank you a lot and happy coding.

**Comment by DrKLO** [comment]
Password protection added in 2.5.0.
