### ISSUE TITLE
When a LTR nick joins a group by invite it bugs the join message

### ISSUE THREAD

**Issue by blackdev1l** [DrKLO/Telegram#1066]
I know the title is terrible, but i don't know how to describe it better.

When someone who has a Left to right nickname (like arabic) joins, his/her nickname  is printed out on far right of the join message. 
 The invite message become something like
 joins group by link invite <nickname> 

![2015-05-05 13 55 37](https://cloud.githubusercontent.com/assets/5544509/7482437/c555e6fc-f377-11e4-9ef9-47cc42b07239.png)

I hope with the screenshot it's better.

**Comment by DrKLO** [comment]
It's android StaticLayout issue or text rendering issue. I can't do anything with it.
