### ISSUE TITLE
Critical security bug

### ISSUE THREAD

**Issue by magicgoose** [DrKLO/Telegram#1070]
Using SMS for user authentication is insecure. So, as long as SMS are used for this purpose, all the talk about Telegram's security is BS…

SMS are sent/received in plain text and mobile carrier can do _everything_ with them. Also, the mobile connection itself is not secure, so even if we trust mobile carriers, the phone can connect to a rogue network that's run by an attacker who intercepts SMS and uses them as he wishes.

Also, SMS can also be intercepted locally on a device, even if it's not rooted. There are already plenty of apps that require READ SMS permission.

**Comment by nastys** [comment]
Enable the Two-Step Verification:
https://telegram.org/blog/sessions-and-2-step-verification
