### ISSUE TITLE
[Feature Request] Press tab  key to complete username in group chat.

### ISSUE THREAD

**Issue by them3gabyte** [DrKLO/Telegram#1072]
Hello,

IS it possible to implement this feature in Telegram group chat? When we type '@' there is a list of all the members in the group, if we know only the first letters we press tab and it auto completes it until it has a conflict just like in UNIX Shell we use tab to complete directories and commands.
Similar feature can also be seen in IRC chats.

**Comment by auchri** [comment]
I think you are talking about Telegram Desktop: https://github.com/telegramdesktop/tdesktop

**Comment by them3gabyte** [comment]
Sorry my bad!
