### ISSUE TITLE
Telegram only connects via wifi

### ISSUE THREAD

**Issue by Matumbotatakombe** [DrKLO/Telegram#1074]
The problem started yesterday 9th May around noon when my telegram could not connect using mobile data.  Other messenging running ok on mobile data.  Telegram keeps showing "Connecting".  Running telegram on PC and phone.  Connecting using wifi without any problem.  Tried reinstalling telegram but the problem still persist.  Using Android 4.2.2.  Been using telegram since April last month. Im from Malaysia. Please help.

**Comment by auchri** [comment]
Maybe your mobile carrier blocks the servers of telegram. Or there is a temporary routing problem.

**Comment by Matumbotatakombe** [comment]
there's a few internet package that my mobile carrier offers at my country.  Im using Digi as my mobile carrier with subscription of RM3(USD0.84) per week with 0mb data.  I was told that all  messenging will not be charge with data.  Im using WeChat and Telegram since April last month.  This seems to be true until two days ago.  WeChat seems to be fine but the problem exist with Telegram.  Today, I've unsubscribe my previous package of RM3 and Telegram went back online for me but its pay as you go now.  This has become very confusing.  Anyways, thanks auchri for responding.
