### ISSUE TITLE
Double checks in group messaging

### ISSUE THREAD

**Issue by krelob** [DrKLO/Telegram#1079]
Meaning could be clarified. Seems that a message gets a double check if any user has seen the message. Not sure if this is the intent or if there would be a way to display who has seen the message.

**Comment by AUDI-A4** [comment]
@krelob i think there should be double check for delivered message like it currently we have and for seen message there can be color change for double tick or add one extra dot with double tick like voice msg

**Comment by krelob** [comment]
I think the second check means the message has been seen not delivered. In WhatsApp the second check means delivered and the checks change color when the message is read.

**Comment by frazzmark** [comment]
It's all written in the website, double tick means "seen" but there's no indication of "received" simply because it can be received in many devices (your pc, phone, or web browser). Please read the FAQ on telegram website.

**Comment by krelob** [comment]
@Frazzmark I think you misunderstand. I simply mean that in group messaging the second check means that _any_ of the other users had read the message. Hangouts for example lets you determine _which_ users are caught up.

**Comment by frazzmark** [comment]
Ah that's different. Well anyway that isn't something that can be changed in this repo. It can only depend on the Telegram API, which is not the goal here.
