### ISSUE TITLE
Delete individual messages in cloud chats

### ISSUE THREAD

**Issue by krelob** [DrKLO/Telegram#1080]
Seems that when deleting individual messages from a group chat the message is deleted only for the single user. Would be nice to be able to completely clear some of a chat without deleting everything. The current meaning could at least be clarified when deleting individual messages.

**Comment by DrKLO** [comment]
There is no API for that.

**Comment by krelob** [comment]
What happens when all participants delete a particular message. Does it remain in the proprietary cloud?

**Comment by krelob** [comment]
Maybe there should be a toast message explaining that the message is not really deleted.

**Comment by DrKLO** [comment]
Every user has his own inbox. When a user deletes a message, it deleted only from his inbox. There is no special inbox for whole chat.

**Comment by krelob** [comment]
Thank you very much for your response.  Keep up the good work!
