### ISSUE TITLE
telegram stops after download sources, compile ... run then stops

### ISSUE THREAD

**Issue by codelogman** [DrKLO/Telegram#1083]
hi, i paste the logs:

05-13 04:52:52.501 V/SmartFaceService - 3rd party pause(3065): onReceive [android.intent.action.ACTIVITY_STATE/org.telegram.messenger/create]
05-13 04:52:52.586 D/dalvikvm(12270): Trying to load lib /data/app-lib/org.telegram.messenger-1/libtmessages.8.so 0x42991e28
05-13 04:52:52.591 D/dalvikvm(12270): Added shared lib /data/app-lib/org.telegram.messenger-1/libtmessages.8.so 0x42991e28
05-13 04:52:52.731 I/dalvikvm(12270): Could not find method android.media.MediaCodec.getInputBuffer, referenced from method org.telegram.android.MediaController.convertVideo
05-13 04:52:52.731 I/dalvikvm(12270): Could not find method android.media.MediaCodec.getOutputBuffer, referenced from method org.telegram.android.MediaController.convertVideo
05-13 04:52:52.776 V/SmartFaceService - 3rd party pause(3065): onReceive [android.intent.action.ACTIVITY_STATE/org.telegram.messenger/pause]
05-13 04:52:52.801 I/dalvikvm(12270): Could not find method android.widget.EdgeEffect.setColor, referenced from method org.telegram.android.AndroidUtilities.setListViewEdgeEffectColor
05-13 04:52:52.801 I/dalvikvm(12270): Could not find method android.widget.EdgeEffect.setColor, referenced from method org.telegram.android.AndroidUtilities.setListViewEdgeEffectColor
05-13 04:52:52.801 V/SmartFaceService - 3rd party pause(3065): onReceive [android.intent.action.ACTIVITY_STATE/org.telegram.messenger/create]
05-13 04:52:52.806 E/dalvikvm(12270): Could not find class 'android.animation.StateListAnimator', referenced from method org.telegram.ui.IntroActivity.onCreate
05-13 04:52:52.806 W/dalvikvm(12270): VFY: unable to resolve new-instance 21 (Landroid/animation/StateListAnimator;) in Lorg/telegram/ui/IntroActivity;
05-13 04:52:52.806 D/dalvikvm(12270): DexOpt: unable to opt direct call 0x0027 at 0x64 in Lorg/telegram/ui/IntroActivity;.onCreate
05-13 04:52:52.881 E/AndroidRuntime(12270): Process: org.telegram.messenger, PID: 12270
05-13 04:52:52.881 E/AndroidRuntime(12270): java.lang.RuntimeException: Unable to resume activity {org.telegram.messenger/org.telegram.ui.IntroActivity}: java.lang.IllegalArgumentException: App ID length must be 32 characters.
05-13 04:52:52.881 E/AndroidRuntime(12270): 	at org.telegram.messenger.Utilities.checkForCrashes(Utilities.java:765)
05-13 04:52:52.881 E/AndroidRuntime(12270): 	at org.telegram.ui.IntroActivity.onResume(IntroActivity.java:239)
05-13 04:52:52.886 W/ActivityManager(3065):   Force finishing activity org.telegram.messenger/org.telegram.ui.IntroActivity
05-13 04:52:53.196 I/WindowManager(3065): Screenshot max retries 4 of Token{450ce038 ActivityRecord{434b4b78 u0 org.telegram.messenger/org.telegram.ui.IntroActivity t13 f}} appWin=Window{433f6150 u0 Starting org.telegram.messenger} drawState=4
05-13 04:52:53.211 D/CrashAnrDetector(3065): processName: org.telegram.messenger
05-13 04:52:53.211 D/CrashAnrDetector(3065): broadcastEvent : org.telegram.messenger data_app_crash
05-13 04:52:53.211 V/SmartFaceService - 3rd party pause(3065): onReceive [android.intent.action.ACTIVITY_STATE/org.telegram.messenger/pause]
05-13 04:52:54.681 I/ActivityManager(3065): Process org.telegram.messenger (pid 12270) (adj 9) has died.
05-13 04:52:56.051 D/dalvikvm(12342): Trying to load lib /data/app-lib/org.telegram.messenger-1/libtmessages.8.so 0x42992818
05-13 04:52:56.056 D/dalvikvm(12342): Added shared lib /data/app-lib/org.telegram.messenger-1/libtmessages.8.so 0x42992818
05-13 04:52:56.156 I/dalvikvm(12342): Could not find method android.media.MediaCodec.getInputBuffer, referenced from method org.telegram.android.MediaController.convertVideo
05-13 04:52:56.156 I/dalvikvm(12342): Could not find method android.media.MediaCodec.getOutputBuffer, referenced from method org.telegram.android.MediaController.convertVideo
05-13 04:52:56.211 I/dalvikvm(12342): Could not find method android.widget.EdgeEffect.setColor, referenced from method org.telegram.android.AndroidUtilities.setListViewEdgeEffectColor
05-13 04:52:56.211 I/dalvikvm(12342): Could not find method android.widget.EdgeEffect.setColor, referenced from method org.telegram.android.AndroidUtilities.setListViewEdgeEffectColor

**Comment by codelogman** [comment]
apparently, this class "import android.animation.StateListAnimator;" does'nt exist, and maybe with an android manager update repositories etc can solve the problem, rigth now i'm still downloading the updates, so when that finished i try again and tells if works or not, greets

**Comment by DrKLO** [comment]
You should remove hockey app from project or fill values for it.
{org.telegram.messenger/org.telegram.ui.IntroActivity}: java.lang.IllegalArgumentException: App ID length must be 32 characters.
