### ISSUE TITLE
Feature Request: Bot Users / Service Proxy Users

### ISSUE THREAD

**Issue by socmag** [DrKLO/Telegram#1085]
I have a legitimate desire to integrate bot users into my contacts.... 

Basically, I want to control my (or friends) home automation system (and other stuff) using telegram messenger, so I need a way to add my house as a user.  Then I can do stuff like this

```
Chris's House:  <-- would be one of my contacts
============
go to kitchen
>ok
turn lights to 50%
>done
turn heating to 23 degrees
>done
```

Useful for all kinds of neat stuff, as you can probably imagine.

I used to be able to do this a long time ago by spoofing the MSN Messenger protocol, and it was very cool.  Maybe there is a way to do this already, but I'm not at all familiar with the Telegram source.  Also, the requirement of a phone number is a bit of a buzz-kill for this I think.

Something else to consider, perhaps.

Oh, and Telegram Rocks! :+1:

**Comment by dgadelha** [comment]
Try Telegram CLI

**Comment by Walkman100** [comment]
> Also, the requirement of a phone number is a bit of a buzz-kill for this I think.

You can use a temporary number to create an account, or get a pay-as-you-go SIM...

**Comment by Mindstormer619** [comment]
There is a bot api at the moment.

**Comment by socmag** [comment]
congrats on the API - looking now - seems comprehensive!  great :)
