### ISSUE TITLE
Get site information without UserAgent.

### ISSUE THREAD

**Issue by ryush00** [DrKLO/Telegram#1093]
I chatted a URL. But no information printed.
I checked log and found out telegram was blocked by CloudFlare due to no user agent.
So I whitelisted your server (maybe information gathering server?) and worked correctly.

Please add user agent when check information

**Comment by DrKLO** [comment]
Our API developer said that our bot has TelegramBot user agent.

**Comment by ryush00** [comment]
![The image](https://cloud.githubusercontent.com/assets/4997174/7720110/582b6c6c-ff04-11e4-81de-c7979271edfa.png)
