### ISSUE TITLE
[Feature-request] Photo caption characters 

### ISSUE THREAD

**Issue by mbnoimi** [DrKLO/Telegram#1098]
I suggest to set the length of photo caption characters same as usual text message.

Currently (ver. 2.9.0) I find it very short specially for Arabic characters.

**Comment by DrKLO** [comment]
Not client related.

**Comment by mbnoimi** [comment]
@DrKLO Come on!
You closed many issues related to the server and never answer how to ask for features related to server API.

**Comment by DrKLO** [comment]
@mbnoimi I answered in some closed issues: via twitter or our support.
