### ISSUE TITLE
Unsupported content warning when sharing webpage

### ISSUE THREAD

**Issue by mirhl** [DrKLO/Telegram#1103]
I mean, it's working and all, but the message popup. 

The link is [this](http://mobile.ilsole24ore.com/solemobile/main/art/notizie/2015-05-21/otto-mille-chiesa-cattolica-calo-2015-e-anche-effetto-vatileaks-140331.shtml) and I'm using 5.1.1 AOSP browser. 

Is there any way I could give some more insights in this? Because at the moment I wouldn't know how to narrow further the description of the issue.

**Comment by DrKLO** [comment]
It's just interface issue and will be fixed in next update.
