### ISSUE TITLE
[Feature Request] Segmented Sticker Panel like TDesktop

### ISSUE THREAD

**Issue by Mindstormer619** [DrKLO/Telegram#1107]
So Telegram Desktop has _this_ for stickers:

![image](http://s25.postimg.org/ha5r8hq9b/screenshot_1432279337.jpg)

While our sticker panel on Android is pretty much a cluttered mess. It would be nice to have a pack-based segregation for stickers so we can find the sticker we are looking for as quick as possible. Also, just like TDesktop, a "Frequently Used Stickers" segment can be kept at the top.

Thanks, and yet again, great work so far!

**Comment by wp9015362** [comment]
+1

**Comment by brunobsouzac** [comment]
+1

The telegram is need a new UI / UX Design. Whatsapp merlhooru much of it, especially in usability, but still has much to improve.

telegram could adopt several of these things.

Add a button to share the telegram desktop stickers would be nice.

**Comment by markuznw** [comment]
+1, having more than 10-15 makes it a total mess with current UI :D

**Comment by brunobsouzac** [comment]
@markuznw  what do you think of this idea ?? looks at the end of the reviews (I decided to make a mockup using the paint)
https://github.com/DrKLO/Telegram/issues/1147#issuecomment-111154097

**Comment by Fsmv** [comment]
I have implemented this here: https://github.com/Fsmv/Telegram/commit/0443f1c541008c2b66a3c594a6509bdc6183fecc

**Comment by Mindstormer619** [comment]
With the latest update, this has been fixed to a degree better than I expected. Thanks devs! You guys are the greatest.
