### ISSUE TITLE
Android instant notification not working on v2.9.1

### ISSUE THREAD

**Issue by wanglongqi** [DrKLO/Telegram#1110]
I have noticed this problem for a while. Last time I simply reverse the application to v2.4.1, but lose all of the secret chat histories. I reset `notifications and sounds settings`, enable the `notifications service`. The problem is still there. Telegram is running in the background from the process monitor. Anyone met same problem?

**Comment by dgadelha** [comment]
Uninstall and Reinstall Telegram.

**Comment by wanglongqi** [comment]
Tried, no use. The client received the message, but no notifications.

**Comment by DrKLO** [comment]
Group chats or not? Smart notifications were introduced in group chats in 2.8.0.

**Comment by wanglongqi** [comment]
All chats. The messages are downloaded to the phone, but no notifications are trigged. In some case, the first message has notification. After that, all messages go silent.

**Comment by DrKLO** [comment]
Which device and android version?
Also make sure that you don't have any apps which disabling Android AlarmManager API and there is no "battery saving" apps which can kill app in background. There is 1 second delay for notifications if your not online from other device and 3 seconds delay if you online from other device.
Also you can install debug version https://rink.hockeyapp.net/apps/a5b5c4f551dadedc9918d9766a22ca7c and send logs to me, I will tell you exactly what's happening.

**Comment by wanglongqi** [comment]
Where can I find the logs?

**Comment by DrKLO** [comment]
Go to app settings and press send logs. Make sure that you tried to receive notification before sending logs.

**Comment by DrKLO** [comment]
You can send it to drklo.developer@gmail.com or to @drklo in Telegram.

**Comment by wanglongqi** [comment]
Thanks for help from @DrKLO! The problem has been identified. Looking forward to next release.
