### ISSUE TITLE
Can't add stickers to different sticker pack

### ISSUE THREAD

**Issue by muava12** [DrKLO/Telegram#1114]
When i trying to add sticker to different published sticker pack the @Sticker bot always said: "Sorry, the link you gave me is incorrect." , but i sure that i have given the correct link and command (like this: /addsticker [http://telegram.me/addstickers/MyPack] )

**Comment by dgadelha** [comment]
You want to add a Sticker to a pack that's not yours?

**Comment by muava12** [comment]
No, i try to add sticker to the pack that i've created

**Comment by glococo** [comment]
It is "/addsticker telegram.me/addstickers/MyPack"

btw: After you add the new Sticker, probably you have to remove the pack and reinstall it.

**Comment by muava12** [comment]
@glococo Thankyou, it works..
