### ISSUE TITLE
Messages are assumed for read when phone is locked

### ISSUE THREAD

**Issue by mirhl** [DrKLO/Telegram#1115]
Let's assume I was reading a group and I lock the phone. 

Now I have the desktop client, and no new message is notified because telegram on the phone will think I'm still looking at the conversation.

**Comment by DrKLO** [comment]
Smart notifications were introduced in 2.8.0. Mobile client knows, that you online from other device and it will not show notification it you will read message from desktop client.

**Comment by mirhl** [comment]
Yes, but the actual problem is that even if Telegram is the "active" application, but phone is locked, I'm not reading messages
