### ISSUE TITLE
ability to schedule a message

### ISSUE THREAD

**Issue by zaxebo1** [DrKLO/Telegram#1117]
in gliph messenger, we can **schedule a message to be send at a particular time in future** .
Please implement it in telegram's mobilephone client too.
This scheduling feature is very **useful** for **scheduling a message to be sent on somebody's birthday** etc

 the **scheduled message should be supported for secret chat** and non-secret chat both. (this is really important, as 100% of my one-to-one communication on telegram is via secret chat only).

If it is not in telegram API, then please get it added in telegram API, as it is very useful addition.

**Comment by DrKLO** [comment]
Useless for me. You can implement it by yourself in your own version.
