### ISSUE TITLE
Perfect Forward Secrecy Bug

### ISSUE THREAD

**Issue by kocuroglu** [DrKLO/Telegram#1118]
At https://core.telegram.org/api/end-to-end/pfs, it says:

> In order to keep past communications safe, official Telegram clients will initiate re-keying once a key has been used to decrypt and encrypt more than 100 messages, or has been in use for more than one week, provided the key has been used to encrypt at least one message. Old keys are then securely discarded and cannot be reconstructed, even with access to the new keys currently in use.

I have tested this with two devices (Samsung Galaxy SII and Samsung Galaxy SII) with latest Telegram version (as of now v2.9.1 (542)). However key visualization doesn't change.

0. Start Secret Chat between SII and SIII, save encryption key visualization.
1. Send 105 messages from SII to SIII 
2. Send 110 messages from SIII to SII

Expected: encryption key visualization to be changed

Result: encryption key visualization stays same

This is also true for older secret chats. I have secret chats older than two weeks and their encryption key visualizations haven't changed (Had tested this before but one the Telegram versions was old, so did the test again).

If I'm not missing something, PFS doesn't work (or at least the way it is described).

**Comment by DrKLO** [comment]
Key visualization shouldn't change, look at IdenticonDrawable.java:
data = encryptedChat.key_hash;
It's calculated from first key.
You should better debug code and see (SecretChatHelper.java), that auth_key is changing as expected.
Since new key is generated via previous key, it's enough to display image only for first key.
