### ISSUE TITLE
Black box when showing emoji panel

### ISSUE THREAD

**Issue by arnaldo2792** [DrKLO/Telegram#1119]
When the emoji panel is displayed, a black box appears in the chat view
![720111685_12691_1467226793440782793](https://cloud.githubusercontent.com/assets/6305870/7804221/48668e90-0325-11e5-8693-0fa3688b4f0b.jpg)

**Comment by AUDI-A4** [comment]
it seems to me you are using beta(dev) version of Telegram .please don't create issue on the beta version of telegram.

**Comment by arnaldo2792** [comment]
I'm using the play store version (2.9.1), is that the beta version?

**Comment by AUDI-A4** [comment]
no

**Comment by arnaldo2792** [comment]
So if I'm not using the beta version, why i'm getting that error?

**Comment by AUDI-A4** [comment]
will be fixed soon

**Comment by DrKLO** [comment]
It was fixed in 545 build
