### ISSUE TITLE
Feature request: group stickers

### ISSUE THREAD

**Issue by AliMD** [DrKLO/Telegram#1120]
Thank for new stickers feature, its awesome
Could you please group stickers for faster access ? (tabs like viber or just simple horizontal line) 
fast smile access is good idea but I usually take long time to find some stickers if i forgot the smile or when i find other sticker in same group
Thank you in advance

**Comment by Mindstormer619** [comment]
This is done in the latest update. Please close issue.

**Comment by AliMD** [comment]
:ok_hand:
