### ISSUE TITLE
"Unsupported characters" when sending arabic RTL text

### ISSUE THREAD

**Issue by mirhl** [DrKLO/Telegram#1131]
I was trying to pass the iphone crashing message from my desktop to phone, but I only get Unsupported characters notice instead. 

effective.
Power
لُلُصّبُلُلصّبُررً ॣ ॣh ॣ ॣ
冗

**Comment by DrKLO** [comment]
Server side filter to prevent iOS crash.

**Comment by mirhl** [comment]
It shouldn't be a burden for you to fix other person's oversights.
