### ISSUE TITLE
Attributed Text Support

### ISSUE THREAD

**Issue by alkaline9500** [DrKLO/Telegram#1135]
It would be cool to be able to **bold** and *italicize* text!

I'd push for Markdown support, but I know that market is a little niche. 😛

**Comment by WuerfelDev** [comment]
How about **bold** and _italic_ ?

**Comment by WuerfelDev** [comment]
I mean ** for bold and _ for italic, that's easy and light.

**Comment by DrKLO** [comment]
Duplicate.
Also there is not only Android client, we have open platform. So if there will be API specification for that, it will be implemented.
