### ISSUE TITLE
[Feature Request] Long Press sticker --> Delete a sticker from current sticker collection

### ISSUE THREAD

**Issue by JoachimR** [DrKLO/Telegram#1137]
Some stickers that I have imported are useless for me and I want to get rid of them. I thought long pressing a sticker could bring up the option of deleting that sticker, like a picture in the standard android gallery app ( see e.g. http://img.wonderhowto.com/img/19/93/63534639962862/0/free-up-storage-space-your-nexus-5-plus-keep-from-getting-full.w654.jpg )

**Comment by DrKLO** [comment]
It's not possible to delete sticker from someone's sticker set. If it's your sticker set, you should delete it via stickers bot.
