### ISSUE TITLE
Issue with Stickers

### ISSUE THREAD

**Issue by JordiSalvans** [DrKLO/Telegram#1140]
Hello,

Today three stickers packs disappeared from Telegram. In Sickers list the packs appears, but with 0 stickers each pack. I deleted the packs and I tried to add again but I can't, neither can I add new packs, an error appears. 

![screenshot_2015-06-04-13-42-50](https://cloud.githubusercontent.com/assets/12331506/7983344/aab63644-0abf-11e5-959e-020a920624f4.png)

Other packs works fine and my friends can add the packs that I can't

Thanks

**Comment by Mindstormer619** [comment]
Amazing! I have the same issue over on Telegram Desktop out as well [here](https://github.com/telegramdesktop/tdesktop/issues/788).

Do you have a total of 22 packs as well?

**Comment by JordiSalvans** [comment]
Oh, It's true! Well, I have 21 packs, not 22.

If I delete one pack, I can add another

**Comment by Mindstormer619** [comment]
21 including the default pack or excluding it? I have 22 including the default one that's always there (Great Minds)

**Comment by JordiSalvans** [comment]
Yes, 21 with Great Minds

**Comment by Mindstormer619** [comment]
Whoops, damn it's 21 for me too. Must have miscounted.

**Comment by Mindstormer619** [comment]
Seems like Telegram is allowing only 20 custom sticker packs in total now :sob:

**Comment by auchri** [comment]
Yes: https://www.twitter.com/telegram/status/606457674558017536

**Comment by Mindstormer619** [comment]
Seems it's a server issue that just got [fixed](https://mobile.twitter.com/telegram/status/606506502946451456). You can close it now @JordiSalvans.

**Comment by JordiSalvans** [comment]
Thanks a lot
