### ISSUE TITLE
Some links just don't get previews

### ISSUE THREAD

**Issue by mirhl** [DrKLO/Telegram#1144]
[This](http://www.who.int/mediacentre/news/releases/) works, [this](http://www.who.int/mediacentre/news/releases/2015/ear-care/en/) doesn't work. 

Why?

**Comment by DrKLO** [comment]
It's server related. I don't know how it works.

**Comment by mirhl** [comment]
Where do you report server problems?

**Comment by auchri** [comment]
On twitter: https://twitter.com/telegram or with the support feature at the android app

**Comment by mirhl** [comment]
Ok, telegram support said the link that doesn't work has not the metadata necessary for preview service
After a little inspection in the pages source code, I noticed the odd one has no *[description](http://www.metatags.org/meta_name_description)* tag in the header. 

*The website is rendered only if some data is available*
*If only one exists, it's automatically "discarded"*
