### ISSUE TITLE
[Feature Request] Polls in groups

### ISSUE THREAD

**Issue by sergiormb** [DrKLO/Telegram#1145]
Hello !, I am Sergio Pino and live in Spain. I've been using Telegram from its beginning with my friends from college. I've always thought of a feature that can be very useful for groups and this would be a poll system.

In groups discusses decisions, for example:
- Day to celebrate the party
- Restaurant to dine
- ...

I think that facilitates implantation system hashtags for voting.

What do you think?

**Comment by DrKLO** [comment]
There is no API for that.

**Comment by guiraldelli** [comment]
Actually, you can use bots for it, such as this: https://github.com/yagop/telegram-bot

**Comment by SweetLion** [comment]
Is it possible to add the poll feature to the API? Telegram offers many excellent functions and polls would come in very handy. Great idea @sergiormb

**Comment by sergiormb** [comment]
But the issue is closed :( is the first time that I contribute in this repository and I really don't know what is the methodology of work that is used here to work with my own ideas.
