### ISSUE TITLE
[Feature Request] Change the user selection for new chat

### ISSUE THREAD

**Issue by ibiBgOR** [DrKLO/Telegram#1146]
I saw this video: [WhatsApp Material redesign](https://www.youtube.com/watch?v=RHs2ESt65Rw)
And I thought that the animation to choose an user is really nice would it be possible to implement this? What does others say? Is this nice or is it just meh?

**Comment by DrKLO** [comment]
No, this is not material.
http://www.google.com/design/spec/material-design/introduction.html
