### ISSUE TITLE
Telegram - New ideas, UX / UI Design

### ISSUE THREAD

**Issue by brunobsouzac** [DrKLO/Telegram#1147]
The Telegram came to rule, but to become better he should have some new options, and focus on improved usability and design (UX and UI), so users do more in less time and everything very intuitive way:

  1 - While placing the phone number, the second step would be compulsorily put anickname this would facilitate for groups and also get used to the users instead of spending your phone, have more privacy and use thenickname

2 - Strengthen opportunities for newnicknames as "." "_" "-" And in smaller size showed the user nickname (in groups) we type for faster. (option to respond is great but we will not always answer but mentioned and already having the nickname in front is faster).

3 - Renewal of Design and usability mainly (ICQ, Whatsapp)

Images that can serve as inspiration (Whatsapp used some of ICQ as well):

ICQ - After registering, we have these three choices, just slide sideways

1 
![1 chats](https://cloud.githubusercontent.com/assets/12419098/8022766/7b857068-0cbf-11e5-8796-9864290411e8.jpg)

2
![2 chat button](https://cloud.githubusercontent.com/assets/12419098/8022769/83ce82c8-0cbf-11e5-89cc-3c00e2bd1862.jpg)

3
![3 - users](https://cloud.githubusercontent.com/assets/12419098/8022773/950e2228-0cbf-11e5-9856-0f7f6798d8bc.jpg)

4 
![4 settings perfil](https://cloud.githubusercontent.com/assets/12419098/8022775/9cddb4aa-0cbf-11e5-8553-2179fa88e5ba.jpg)

Chat 1
![chat 1](https://cloud.githubusercontent.com/assets/12419098/8022780/d8bb9c58-0cbf-11e5-8733-81ef38bb16b2.jpg)

Chat 2 
![chat 2 options](https://cloud.githubusercontent.com/assets/12419098/8022805/4f702494-0cc1-11e5-9f37-eac41379ddfa.jpg) 
Inside Chat, just slide to the left and see the simple and organized options, easy stop create a group with this person, block, check the shared medias, disable notifications this user, put a wallpaper in this chat, activate and disable automatic voice messages (features in iOS but we want to all OS)

Chat 3 

![chat 3](https://cloud.githubusercontent.com/assets/12419098/8022812/da71b242-0cc1-11e5-92a2-c17aacb1b61f.jpg)

Chat 4
![chat 4](https://cloud.githubusercontent.com/assets/12419098/8022816/097a2e20-0cc2-11e5-8987-274073d2cdc4.jpg)
![chat 5](https://cloud.githubusercontent.com/assets/12419098/8022818/1c987462-0cc2-11e5-8e72-0e94d931d749.jpg)

Chat 5 Image Gallery (Instagram, facebook, Google+, etc.)
![chat 6](https://cloud.githubusercontent.com/assets/12419098/8022820/61e28724-0cc2-11e5-975c-e93e9f8e86e6.jpg)

Whatsapp - Recasting used things such as ICQ is simplified and usability, was very beautiful, but in some other things floating button would be better to add people for example. Slide view all your profile and options.

![home](https://cloud.githubusercontent.com/assets/12419098/8022824/a5d71184-0cc2-11e5-9761-905e61e2a0f6.jpg)

![photo_2015-06-02_22-13-40](https://cloud.githubusercontent.com/assets/12419098/8022828/c0ef26e6-0cc2-11e5-86ff-173c44f316a6.jpg)

![photo_2015-06-02_22-13-47](https://cloud.githubusercontent.com/assets/12419098/8022830/dc71ec96-0cc2-11e5-9953-f0ee7ee2d6a0.jpg)

![3116133_385](https://cloud.githubusercontent.com/assets/12419098/8022831/e2a531d6-0cc2-11e5-86a1-7bef2084d205.jpg)

Telegram:
I think we just lack that pro Telegram get simpler to use, organized, less cluttered, more beautiful. I suggest to the logo to return to the airplane.

 This aircraft is used in several places to the site compared to the simplified it seems a GPS arrow who is now on Android

![the best logo](https://cloud.githubusercontent.com/assets/12419098/8022843/9deede2e-0cc3-11e5-9532-2b7953be1eb5.png)

Another reference on effects if they want to test:

![material_design effects](https://cloud.githubusercontent.com/assets/12419098/8022845/be124cea-0cc3-11e5-9bd2-28e2338c3d34.gif)
This button could get inside the chat in the right corner, and the Messenger Iphone, avoiding problems by sending the wrong message (how many of us no longer do that?)

Messenger Iphone
![25113829950157](https://cloud.githubusercontent.com/assets/12419098/8022875/4168954e-0cc5-11e5-943d-14af08babaca.jpg)
![voicemessages](https://cloud.githubusercontent.com/assets/12419098/8022876/4168e0da-0cc5-11e5-94eb-88796cef85c0.gif)

What do you think ??? I wonder if they think like me and can see these improvements. Thank you

**Comment by tonghuix** [comment]
Have you draw a mokeup for this new design?

**Comment by brunobsouzac** [comment]
@tonghuix I do not move with such tools, but if anyone knows me state I study for a light time and I'm sure I would make a mockup with these ideas.

You know show me some software to mockup + effects in gif?

**Comment by tonghuix** [comment]
I prefer draw.io as a template mockup design tool, cause it easy to hand up. But it not provide effects in gif, so that would only for static design.

**Comment by brunobsouzac** [comment]
@tonghuix OK, I took a quick look and it does not come with visual MT and buttons. But I will give a studied and see what I can do here. Even just a draft but passing the true idea.

**Comment by sabret00the** [comment]
You do know that Telegram was heralded for its design by Google two years running. None of the clients you list above have that honour.

**Comment by brunobsouzac** [comment]
@sabret00the I see your point, but the examples above have much more practical usability and with fewer steps to do something than currently Telegram. He needs a renovation.

Google may have mentioned but what criteria he used for this? Telegram innovated much at all and especially for being one of the first who quickly adopted the Material Design (this will be the discretion of Google?).

I would like the opinion of all of this, with what they liked and did not like here presented. So we can get great ideas and transform into one and see if the Telegram staff accepted.

Sorry for my english.

**Comment by sabret00the** [comment]
At Google IO 2015 only eighteen apps were recognised. 18 out of all the apps available on the Play Store that have implemented Material Design. Telegram was one of those that were recognised. Above each and every app you named/screenshotted above. 
That said, if you're serious about improving the usability, by all means make those suggestions. But be succinct and rely less on comparisons with lesser apps. 
Also feel free to use your native tongue if you're more comfortable with that. 
On 9 Jun 2015 04:52, brunobsouzac <notifications@github.com> wrote:@sabret00the I see your point, but the examples above have much more practical usability and with fewer steps to do something than currently Telegram. He needs a renovation.

Google may have mentioned but what criteria he used for this? Telegram innovated much at all and especially for being one of the first who quickly adopted the Material Design (this will be the discretion of Google?).

I would like the opinion of all of this, with what they liked and did not like here presented. So we can get great ideas and transform into one and see if the Telegram staff accepted.

Sorry for my english.

**Comment by brunobsouzac** [comment]
+1

I remember when Google said it. But on the apps above issues submitted in my opinion the usability of them is a little more practice and law. It would be a supplement to the Current Telegram. for example, search photos and gifs, it's a dark gallery that does not fit well with the rest of the app, we could change that. I realized that many users do not even know this option could be moved directly to the attachment menu, as shown in this post (did a search on telegram groups to make the posting).

I appreciate the comments.

In the telegram could innovate?

**Comment by DrKLO** [comment]
Apps should follow material design: http://www.google.com/design/spec/material-design/introduction.html
ICQ and WA doesn't. Bad examples.
Also I'm not designer. So better ask our support or twitter about this.

**Comment by brunobsouzac** [comment]
I'm no designer but I decided to play around with the paint (not photoshop, nor know move).

Here I mixed various ideas of Hangouts, Whatsapp, ICQ, Google Messenger and Viber.

I tried to respect the Material Design in the way it is used well, hope you like it getting messy with wrong colors. But now it gives to have a good idea and all focused on usability. More in fewer steps.

The good thing is that Google encourages creativity in MT, the mixture in my view was good, what do you think? Easier to understand than the post?

Hangouts by Google:

![photo_2015-06-11_05-23-04](https://cloud.githubusercontent.com/assets/12419098/8107285/a0da2874-101e-11e5-8673-f81f78fe016b.jpg)
![photo_2015-06-11_05-23-12](https://cloud.githubusercontent.com/assets/12419098/8107286/a0dca9a0-101e-11e5-9e6b-c995d9f82a69.jpg)


New idea telegram:

Old is just better. After placing the phone and full name number, I think it would be great to have another screen asking to register your @nickname, thus popularized use the @nickname.
![logo and nickname](https://cloud.githubusercontent.com/assets/12419098/8107551/82aeb98a-1020-11e5-9099-0a6347f1bfb5.jpg)

I changed some functions, and how many people ask where the exit button is and think hard, put in order.
![telegram 1 new](https://cloud.githubusercontent.com/assets/12419098/8109101/64ec0d34-102b-11e5-84d2-65b23cda44cf.jpg)

tabbed browsing
![telegram 2 new](https://cloud.githubusercontent.com/assets/12419098/8109157/aaa0a678-102b-11e5-82f8-ffda0265dfd3.jpg)

![telegram 3 new](https://cloud.githubusercontent.com/assets/12419098/8109258/1552fc3c-102c-11e5-9490-70bb822a1677.jpg)
![telegram 4](https://cloud.githubusercontent.com/assets/12419098/8109259/155ae1c2-102c-11e5-8824-efbd8a59e820.jpg)

Chat menu
![telegram 4 -menu chat](https://cloud.githubusercontent.com/assets/12419098/8109277/23d6bd5c-102c-11e5-988e-c84eb4b96705.jpg)

Telegram files. Here I tried to change a little icons as presented, but the old way is also good, just need to put the search for images, more practical to see.
![telegram files](https://cloud.githubusercontent.com/assets/12419098/8109293/32a9236a-102c-11e5-88ab-5ee3af7b8a9c.jpg)

Change the colors of the gallery and search images / gifs for standard or blank Telegram
![photo_2015-06-11_05-22-52](https://cloud.githubusercontent.com/assets/12419098/8109363/9593c6ba-102c-11e5-85e6-928532a3a613.jpg)

If you like I change the post and put those images.
