### ISSUE TITLE
Telegram app android always "Connecting..." over 2g\3g network

### ISSUE THREAD

**Issue by slimus** [DrKLO/Telegram#1148]
Since the 5th of June it is written "Connecting..." when the connection is not over Wi-Fi but over mobile carrier (when the connection is over Wi-Fi application works normally). When I ask the support of mobile carrier which I use they told that there is no traffic blocks. I'm from Russia, my IP: 217.118.66.143. Could you please suggest me what I can do to use the application when I connect over mobile carrier?

**Comment by AUDI-A4** [comment]
Same here works fine with wifi but does not work with mobile 2g and 3g since they made the app :(
