### ISSUE TITLE
Separation of MTProto concerns from Android ones. Would it be a good idea?

### ISSUE THREAD

**Issue by Hossein-Fasihi** [DrKLO/Telegram#1149]
I was just trying to get acquainted with the source code. It appears to me that the packages inside org.telegram (_Namely **org.telegram.messenger** and  **org.telegram.android** packages_) are quite co-dependent on (coupled with) each other. 
It seems to me that it could've been a much easier task for other client developers who try to reach this goal, if the dependencies where to be arranged in a way that **messenger** classes, which seems to be more related to MTProto concerns, were independent of other packages.
This way other developers would be able to take the MTProto implementation and easily use it in other platforms (Say, a Java desktop application or a serverside Java EE application).
Would it be considered an acceptable idea by fellow Telegram developers, if one was to try refactoring in a fork and then pull request, to reach the aforementioned arrangement?

**Comment by DrKLO** [comment]
Not possible for now. Will take a lot of time.
