### ISSUE TITLE
Per Monitor DPI awareness in Windows 8.1 / 10

### ISSUE THREAD

**Issue by Mavo82** [DrKLO/Telegram#1150]
Using two screens with different resolution (4K and FullHD), most of my applications get automatically scaled when moved from one screen to the other. In Telegram however, the Window remains the same pixelsize and is gigantic in FullHD, but tiny in 4K. 

See https://msdn.microsoft.com/en-us/library/windows/desktop/dn469266%28v=vs.85%29.aspx for further reference about "per Monitor–DPI Awareness".

**Comment by dgadelha** [comment]
This shouldn't be on telegram desktop isuses?
