### ISSUE TITLE
Android addressbook two way sync

### ISSUE THREAD

**Issue by tguser** [DrKLO/Telegram#1155]
On Android creating a new contact (in google contacts i.e.) if a corresponding Telegram contact is found it is correctly added in Telegram app.
On the other side deleting a contact from phone the corresponding Telegram contact is not deleted and I have to delete it in app.
I think Telegram addressbook should reflect local deletion.

If I delete a contact I do not want/need to contact him anymore.
Also, maintaing 2 addressbook may be too much work.
I.E.:
1) got a new job and synced contacts (200) from corporate exchange
* 200 more contacts in smartphone address book
* 123 of 200 are Telegram users so 123 new contacts in Telegram addressbook

2) change job and delete 200 business contacts
* 123 contacts to delete from Telegram addressbook.

Stupid example maybe... maybe I would delete only 50 of 200 contacts. 
But I need to keep my local / tg contacts in sync.

**Comment by DrKLO** [comment]
"I think Telegram addressbook should reflect local deletion."
No, it shouldn't. Since some android devices can suddenly return empty contacts list. So it will wipe all your contacts list.

**Comment by davux** [comment]
Is it technically possible to prompt the user when a contact is deleted from Android address book? Something like "Contact Too was just deleted from your addressbook. Would you like to delete the contact from Telegram as well?"
