### ISSUE TITLE
INPUT_CONSTRUCTOR_INVALID when calling geochats_getLocated

### ISSUE THREAD

**Issue by mrsaleh** [DrKLO/Telegram#1156]
This block of code always reture INPUT_CONSTRUCTOR_INVALID , I checked it many times and I just don't understand what happen that it ends with this error , everything seems to be OK.

 TLRPC.InputGeoPoint geoPoint = new TLRPC.InputGeoPoint();
        geoPoint.lat = geoLocation.getLatitude();
        geoPoint._long = geoLocation.getLongitude();

        TLRPC.TL_geochats_getLocated req = new TLRPC.TL_geochats_getLocated();
        req.geo_point = geoPoint;
        req.radius = 5000000; //5000 km
        req.limit  = 50; // 50 geo chat

        ConnectionsManager.getInstance().performRpc(req, new RPCRequest.RPCRequestDelegate() {
            @Override
            public void run(TLObject response, TLRPC.TL_error error) {
              // response is null , and error contains INPUT_CONSTRUCTOR_INVALID
             });

**Comment by DrKLO** [comment]
Geo chats API is disabled on server side.

**Comment by mrsaleh** [comment]
And when you enable geo chat api on server ?!
