### ISSUE TITLE
calling getUsers procedure allways returns error INPUT_FETCH_ERROR 

### ISSUE THREAD

**Issue by mrsaleh** [DrKLO/Telegram#1157]
TLRPC.TL_users_getUsers req = new TLRPC.TL_users_getUsers();
        for(int userId:usersIds) {
            TLRPC.InputUser inputUser = new TLRPC.InputUser();
            inputUser.user_id = userId;
            req.id.add(inputUser);
        }
        ConnectionsManager.getInstance().performRpc(req, new RPCRequest.RPCRequestDelegate() {
            @Override
            public void run(TLObject response, TLRPC.TL_error error) {
                if(error==null){
                    Log.e("telegram",error.text); //always error filled with INPUT_FETCH_ERROR
                    return;
                }
                if(response!=null){
                    TLRPC.Vector users = (TLRPC.Vector)response;
                }
            }
        });
//----------------------------------------------------------------------------------------------------------
If I must fill accesshash parameter , then how can I obtain it , I want to restore users that saved somewhere and are not in contact list

**Comment by DrKLO** [comment]
You using it wrong. Look into InputUser.TLdeserialize for possible InputUser classes.

**Comment by mrsaleh** [comment]
what ? can you explain more?

you know something , recently I have test this code 
            TLRPC.User user = new TLRPC.User();
            user.id = geo.telegramId;
            TLRPC.InputUser inputUser = getInputUser(user);

and the INPUT_FETCH_ERROR error doesn't show up but instead I get an error with code -1000, do you have any idea ?

what you mean TLdeserialize ? can you show me a sample code or something?

**Comment by DrKLO** [comment]
TLRPC.User is base class, as TLRPC.InputUser, it's just contains all user variables. It's not TL object.
