### ISSUE TITLE
Feature request: support for threads

### ISSUE THREAD

**Issue by pedrox** [DrKLO/Telegram#1159]
There is a huge gap between e-mail technology and IM technology. E-mail feels outdated and slow even with great clients (such as Inbox, Mailbox etc.). IM on the other hand lacks organization of conversations in threads (compare "compose new e-mail to my team subject X" vs "text about X on my team group via IM").
Telegram is awesome and could somehow support threads/subjects of conversations. And other related feature would be to be backwards compatible with e-mail clients (to help the transitions). So I could create a "start a new thread to my team subject X" easily via telegram and Cc someone else that still uses e-mail.

I know is a crazy ideia and involve a lot of effort. But I think we are near a disrupting transition from e-mail to something else and telegram could be this new thing.

**Comment by DrKLO** [comment]
There is no API for that.

**Comment by guiraldelli** [comment]
There is no API for what? Sending email or supporting threads?

Looking to [`messages.createChat`](https://core.telegram.org/method/messages.createChat), I think there is a *workaround* for creating threads: imagine my chat is called *The Chat*. So threads of this chat could be new chats named as *The Chat#ThreadName*, for instance, and the handling of it as threads would be made in the UI.

Let's restate it is a **workaround**, not a correct way for implementing it. For the latter, I would have to study in details the API, which I haven't done.

Still, my question is still valid. :grin:

**Comment by DrKLO** [comment]
So you can create your own version with this workaround. For me it's useless.

**Comment by guiraldelli** [comment]
Fortunately, I have asked a technical question (*There is no API for what? Sending email or supporting threads?*), not personal opinions. Hence, I think it is valid to ask you what you meant if your answer (*There is no API for that.*).

I can understand it may not be in the Telegram's plans to implement threads as Slack or HipChat does, but not the pseudo-technical and incomplete answer.

**Comment by asdofindia** [comment]
I have thought about threads based on the replies feature too. But building something based entirely on the UI of the client is a sure way to break Telegram on every other client. Unless the API specifically is written for threaded messages (like replies are supported now), it is probably not a wise idea to implement threads.
