### ISSUE TITLE
Fatal Exception

### ISSUE THREAD

**Issue by bkerensa** [DrKLO/Telegram#1167]
06-16 02:26:18.141 17985 17985 E AndroidRuntime: FATAL EXCEPTION: main
06-16 02:26:18.141 17985 17985 E AndroidRuntime: Process: org.telegram.messenger, PID: 17985
06-16 02:26:18.141 17985 17985 E AndroidRuntime: java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to android.view.WindowManager$LayoutParams
06-16 02:26:18.141 17985 17985 E AndroidRuntime: 	at org.telegram.ui.Components.ChatActivityEnterView.onSizeChanged(ChatActivityEnterView.java:1208)
06-16 02:26:18.141 17985 17985 E AndroidRuntime: 	at org.telegram.ui.Components.SizeNotifierFrameLayout$1.run(SizeNotifierFrameLayout.java:80)
06-16 02:26:18.141 17985 17985 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
06-16 02:26:18.141 17985 17985 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-16 02:26:18.141 17985 17985 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
06-16 02:26:18.141 17985 17985 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5401)
06-16 02:26:18.141 17985 17985 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-16 02:26:18.141 17985 17985 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:725)
06-16 02:26:18.141 17985 17985 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:615)

**Comment by DrKLO** [comment]
It's not my problem, that you installed preview android M version.
