### ISSUE TITLE
Option to show emoji list on single tap on Enter

### ISSUE THREAD

**Issue by woj-tek** [DrKLO/Telegram#1168]
Many IM/sms apps use by default short tap on enter to show emoji list and long-tap to insert new line. Currently Telegram uses defaults that are more in-line with multi-line forms (so, email for example). Would it be possible to change it to what other IM uses or add it as an option?

**Comment by DrKLO** [comment]
It's not possible to override keyboard button actions. It's different app.

**Comment by woj-tek** [comment]
Kindly disagree, vide:
http://stackoverflow.com/questions/20670482/default-emoji-button-in-google-keyboard-with-android-4-4

(and for the reference as well - option: http://android.stackexchange.com/questions/44443/how-to-get-the-enter-return-key-in-messaging-mms-app-jelly-bean)
