### ISSUE TITLE
Error in RecyclerListView.java and PasscodeView.java

### ISSUE THREAD

**Issue by ullahchozta** [DrKLO/Telegram#1170]
If generate signed APK, 

1. any error in RecyclerListView.java
Message show : 
"Error:(24, 19) error: RecyclerListViewItemClickListener is not abstract and does not override abstract method onRequestDisallowInterceptTouchEvent(boolean) in OnItemTouchListener"

2. any error in PasscodeView.java
Message show : 
Error:(1014, 46) error: incomparable types: Object and int

Thanks

**Comment by DrKLO** [comment]
Use java 7.

**Comment by ullahchozta** [comment]
how about java 8 ?

**Comment by n0mer** [comment]
@ullahchozta , i'm getting the same error on 1.8.0_60-b27

Were you able to fix it?
