### ISSUE TITLE
Feature Request: show contact timezone

### ISSUE THREAD

**Issue by lapo-luchini** [DrKLO/Telegram#1172]
When having many distant friends/contacts, it's useful to have a quick glance at their current time when writing a message. (or not, e.g. if it's their middle of the night and you know they don't silence their phone just in case of emergencies)

**Comment by ullahchozta** [comment]
hi,, can you help me.. i have problem about recyclerlisview.java. if I generate signed apk, that error..

**Comment by DrKLO** [comment]
No server API for that.
