### ISSUE TITLE
[Feature Request] Message Priority

### ISSUE THREAD

**Issue by alkaline9500** [DrKLO/Telegram#1175]
I don't know if this would be extremely useful, but it would be a neat idea if you could set a priority on a message (low, medium, high). Then you could allow the user to configure notification profiles for each. For example, low priority messages should show a notification, but not vibrate, etc. Consider a use case where I know my friend is at work and I want to send her like 5 photos, but I don't want to blow up her phone if she's in a meeting.

**Comment by alkaline9500** [comment]
Of course, she could put her phone on silent, but this way, the sender could be able to choose the importance of a message.

**Comment by DrKLO** [comment]
There is no server API for that.
