### ISSUE TITLE
Failed to find provider info for com.teslacoilsw.notifier

### ISSUE THREAD

**Issue by friend4chams** [DrKLO/Telegram#1177]
Why is this error?

Failed to find provider info for com.teslacoilsw.notifier

app run properly but this error is shown in log list,

seems it occurs when when open a new chat or open a previous chat.

Why is that so? and what is the fix?

**Comment by DrKLO** [comment]
It's to support NovaLauncher unread counter on icon. On devices without this launcher you will see this error in logcat. No way to disable it.

**Comment by friend4chams** [comment]
Ok but it does not work for 5.0 or 5.1 Android, and does not show counter on icon.

**Comment by DrKLO** [comment]
You should have NovaLauncher and TeslaUnread installed.
