### ISSUE TITLE
[Feature Request] Block certain stickers packs

### ISSUE THREAD

**Issue by XyLoNaMiyX** [DrKLO/Telegram#1180]
Hello there! I'd like an option to block certain stickers packs that may be offensive for certain people (for example, those NSFW) and maybe these people are not happy seeing them. Once a sticker pack is blocked, if anyone sends it, the person won't be able to see it until, for example, the person holds on the sticker for some seconds.

Thanks in advance!
 Lonami

**Comment by mokhtarabadi** [comment]
+1

**Comment by DrKLO** [comment]
There is no API for that.

**Comment by XyLoNaMiyX** [comment]
@DrKLO, even if there's no API for that, can't the client application just block certain stickers so it doesn't display them or something similar?

**Comment by pschichtel** [comment]
+1 I'd really like to be able to disable certain stickers or even complelely disable stickers
