### ISSUE TITLE
Cannot save sticker packs used in secret chat

### ISSUE THREAD

**Issue by Fsmv** [DrKLO/Telegram#1181]
If someone sends a sticker in a secret chat and you don't have the sticker pack the only option presented is delete.

Initially I thought this was intentional but after some debugging I found that what really happens is in ChatActivity::createMenu getMessageType appropriately determines that the message is a sticker but on [line 2512](https://github.com/DrKLO/Telegram/blob/f8e8d089f7c7008288668f4f4cb053ea48d5df2f/TMessagesProj/src/main/java/org/telegram/ui/ChatActivity.java#L2512-L2515) getInputStickerSet returns null because the sticker attribute has null in its member for the sticker set, this causes the type to be returned as 2 instead of the 7 we want. This leads me to believe its a problem with sending sticker messages in encrypted chats.

I tried to fix the issue myself but I don't know enough about how message sending works or why the encrypted chat code path is so different from the non-encrypted chat path.

**Comment by DrKLO** [comment]
Secret chats scheme wasn't updated to support sticker packs. It can't be fixed without API changes.

**Comment by Fsmv** [comment]
Should I report the bug on the API project?

**Comment by Mindstormer619** [comment]
Perhaps. Or you could send Telegram a tweet
