### ISSUE TITLE
Update prompt not working correctly

### ISSUE THREAD

**Issue by samayres1992** [DrKLO/Telegram#1185]
(I'm on El Capitan so maybe this is why)

Whenever I restart my Mac I get a prompt to update to 1.65, even though I'm currently on version 1.65.21868. 

Not a major issue but it is worth addressing, in my opinion at least.

**Comment by DrKLO** [comment]
This is not mac app repo.

**Comment by samayres1992** [comment]
@DrKLO Whoops, sorry.
