### ISSUE TITLE
Let user select own Emoji resources and fonts, like stickers

### ISSUE THREAD

**Issue by Jamesits** [DrKLO/Telegram#1194]
We just need an option.

#222 #624 #829

**Comment by DrKLO** [comment]
No, but you can make your own version with your own fonts, emoji, etc.

**Comment by ultravioletnanokitty** [comment]
some "community" project you've got here. we want customisability in the OFFICIAL version of telegram, not some buggy fork. you did it with stickers, there's no excuse not to offer it for other resources. a+ job listening to your users. :/
