### ISSUE TITLE
Feature: Start using QRCodes

### ISSUE THREAD

**Issue by pjrobertson** [DrKLO/Telegram#1199]
I've recently moved to China, where the No.1 messaging app is WeChat (微信).
Whilst it started out as a simple clone of WhatsApp it now has many more features. For starters they use QRCodes a lot, which I think would be something great to add to telegram.
Here are some places they could be used:

* Adding contacts/groups to Telegram (scan your friend's QRCode). I know Telegram doesn't have its own contacts database right now, so this might need some reworking
* QRCodes for bots - people/companies could place QRCodes on adverts/websites for people to start following
* Logging in to Webogram (add a QRCode to https://web.telegram.org/#/login which you can scan. See http://web.wechat.com/ as an example)
* Link the desktop apps with your phone
* (?) Potentially use them to copy secret chat encryption keys, incase you want to move your secret chats to a new phone. I'm not sure on the end to end encryption used for secret chats, so I don't know if this would be possible
* In the future they could be used for many more things: payments (like Alipay), sharing content with friends; e.g. adding new emoticon sets, setting background wallpaper etc.

If you think this is a good idea, then it should probably be discussed further somewhere else (is there a 'dev' user list for Telegram?)
I'd probably suggest adding QS Codes to the mobile apps and Webogram first to use them to log in to webogram. Then they could be expanded for other areas.

**Comment by DrKLO** [comment]
Not client related.

**Comment by pjrobertson** [comment]
@DrKLO - As I asked in my post, do you have a dev user list where this kind of thing can be discussed?

**Comment by DrKLO** [comment]
@pjrobertson you can ask about it in Twitter or our support.
