### ISSUE TITLE
Feature Request: Add the ability to ban users from groups

### ISSUE THREAD

**Issue by niklas-heer** [DrKLO/Telegram#1202]
This function absolutely crucial to operate a large Telegram group. The invitation link makes it possible for trolls to rejoin the group. There should really be an option to ban a user permanently from rejoining a group even tough he/she is invited again or clicks on the invite link.
Simply generating a new invite link does not help, because we publish the url in our forum.

**Comment by AUDI-A4** [comment]
There is no API for that ;)

**Comment by niklas-heer** [comment]
Mhm... okay. Is there some place more appropriate, where I could request this feature?

**Comment by kenniki** [comment]
You can try asking the Telegram Support for this.
More realistically, you're going to need a bot though.
