### ISSUE TITLE
Double greater-than sign (>>) automatically converted to »

### ISSUE THREAD

**Issue by anonimus-programus** [DrKLO/Telegram#1204]
Sent this line to a friend:
echo 'i ALL=(ALL) ALL' >> /etc/sudoers

received:
echo 'i ALL=(ALL) ALL' » /etc/sudoers

So that command line couldn't be executed properly.

**Comment by anonimus-programus** [comment]
Same case happened to:
dpkg --list | grep linux-image

received:
dpkg —list | grep linux-image

**Comment by auchri** [comment]
I think this is a issue of Telegram Desktop: https://github.com/telegramdesktop/tdesktop/issues/803

**Comment by anonimus-programus** [comment]
Thank @auchri.

Hope this issue gets fixed soon.

**Comment by auchri** [comment]
I think you can close the issue here :)
