### ISSUE TITLE
Error:(24, 19) error: RecyclerListViewItemClickListener is not abstract and does not override abstract method onRequestDisallowInterceptTouchEvent(boolean) in OnItemTouchListener

### ISSUE THREAD

**Issue by EasonWang01** [DrKLO/Telegram#1205]
This problem occur and I have seen that DrKLO  says in other post that it need to use java 7 .

How's that means? How to change to java7 and how to check my current version?

**Comment by DrKLO** [comment]
For what you removed RecyclerView code from project and trying to use RecyclerView from support library?

**Comment by DrKLO** [comment]
But anyway solution for this error exist in error text.
