### ISSUE TITLE
Created New Seperated APP using Telegram API .Duplicacy of Message occur.

### ISSUE THREAD

**Issue by gauravbansal123** [DrKLO/Telegram#1206]
We have integrated new seperate app changing all package name and using telegram api for registering process ,now the contact list we are getting is same as we get in telegram app ,but the user that are getting have not registered our app so why they are displaying? Is their any Solution for this.

**Comment by DrKLO** [comment]
Why it should be different if your app using the same servers as official Telegram app?
Onliest solutions it's to write your own backend.
