### ISSUE TITLE
Seeking Info on User Class

### ISSUE THREAD

**Issue by nOmi7** [DrKLO/Telegram#1209]
What is flags in new User class?
How is it used for what could not find any  info on the same any help will be really appreciated.

TL_userContact , userSelf , deleted , empty are renamed to old ? however i get response from server as TL_User always in what cases ill get _old objects ? 
will they be removed in future ?

Thanks

**Comment by DrKLO** [comment]
It's already removed. You can find all flags in TLRPC class.
Since I store users as TL objects in database, I need keep all old objects for back compatibility.

**Comment by nOmi7** [comment]
Thanks i wanted to know how does server calculates values of flags ?
I did not understand below code.

public static class TL_user extends User {
        public static int constructor = 0x22e49072;


        public void readParams(AbsSerializedData stream, boolean exception) {
            flags = stream.readInt32(exception);
            id = stream.readInt32(exception);
            if ((flags & 1) != 0) {
                access_hash = stream.readInt64(exception);
            }
            if ((flags & 2) != 0) {
                first_name = stream.readString(exception);
            }
            if ((flags & 4) != 0) {
                last_name = stream.readString(exception);
            }
            if ((flags & 8) != 0) {
                username = stream.readString(exception);
            }
            if ((flags & 16) != 0) {
                phone = stream.readString(exception);
            }
            if ((flags & 32) != 0) {
                photo = UserProfilePhoto.TLdeserialize(stream, stream.readInt32(exception), exception);
            }
            if ((flags & 64) != 0) {
                status = UserStatus.TLdeserialize(stream, stream.readInt32(exception), exception);
            }
            if ((flags & 16384) != 0) {
                bot_info_version = stream.readInt32(exception);
            }
        }
