### ISSUE TITLE
flags in 3.x update

### ISSUE THREAD

**Issue by nOmi7** [DrKLO/Telegram#1211]
Thanks @DrKLO  i wanted to know how does server calculates values of flags ?
I did not understand below code.

public static class TL_user extends User {
public static int constructor = 0x22e49072;

    public void readParams(AbsSerializedData stream, boolean exception) {
        flags = stream.readInt32(exception);
        id = stream.readInt32(exception);
        if ((flags & 1) != 0) {
            access_hash = stream.readInt64(exception);
        }
        if ((flags & 2) != 0) {
            first_name = stream.readString(exception);
        }
        if ((flags & 4) != 0) {
            last_name = stream.readString(exception);
        }
        if ((flags & 8) != 0) {
            username = stream.readString(exception);
        }
        if ((flags & 16) != 0) {
            phone = stream.readString(exception);
        }
        if ((flags & 32) != 0) {
            photo = UserProfilePhoto.TLdeserialize(stream, stream.readInt32(exception), exception);
        }
        if ((flags & 64) != 0) {
            status = UserStatus.TLdeserialize(stream, stream.readInt32(exception), exception);
        }
        if ((flags & 16384) != 0) {
            bot_info_version = stream.readInt32(exception);
        }
    }

**Comment by DrKLO** [comment]
From TL scheme:
user#22e49072 flags:# id:int access_hash:flags.0?long first_name:flags.1?string last_name:flags.2?string username:flags.3?string phone:flags.4?string photo:flags.5?UserProfilePhoto status:flags.6?UserStatus bot_info_version:flags.14?int = User;

for example flags.2 where 2 mean number of bit in flags field.

**Comment by nOmi7** [comment]
@DrKLO  so does this mean server will create flag value based on the data that i have .

eg . if i have access value , first name , last name  every other attribute EXCEPT BOTi may have flag number 2047 ?

while in case if i have NO photo and access hash and lastname  flag can be  91 ?
