### ISSUE TITLE
Do not completely ignore chats on mute

### ISSUE THREAD

**Issue by ManuelSchneid3r** [DrKLO/Telegram#1212]
Muting chats suppresses textual notifications, too. People tend to mute vivid chats since the continuous notifications quickly start to be annoying. However completely suppressing notifications is not a good idea, since in my case people don't check telegram for days since they communicate solely in the muted chat.

Please still notify users textually in the notification center or give separate options to suppress notifications, e.g. a "don't notify" and "mute" option.

**Comment by DrKLO** [comment]
You can disable sound and vibration for specific chat in its profile.
