### ISSUE TITLE
Error:(24, 19) error: RecyclerListViewItemClickListener  I don't remove anything

### ISSUE THREAD

**Issue by EasonWang01** [DrKLO/Telegram#1214]
As this closed issue https://github.com/DrKLO/Telegram/issues/1205    I do not edit any code,just clone it  ,when I tried to run it this problem happened.My last time run this repo was four month ago,it works fine.
But now it can't,I still don't know how to solve it.Thanks

**Comment by DrKLO** [comment]
So check your imports:
https://github.com/DrKLO/Telegram/blob/master/TMessagesProj/src/main/java/org/telegram/ui/Components/RecyclerListView.java#L21
