### ISSUE TITLE
Share content using tg scheme

### ISSUE THREAD

**Issue by Amir-Mousavi** [DrKLO/Telegram#1215]
Hi. I want to share to telegram app using tg scheme. 
I want to use somthing like the below code:
`<a href="tg://share?text=hi this a text"> hi </a>`
I see that this example that create a chat with bot:
`<a href="tg://resolve?username=somebot"> chat hi bot </a>`

**Comment by auchri** [comment]
Not android app related.

https://twitter.com/telegram

**Comment by BobTheProgrammer** [comment]
Where can i get some support with this issue?

**Comment by auchri** [comment]
On twitter: https://twitter.com/telegram :)

**Comment by BobTheProgrammer** [comment]
I sent you guys a tweet,but I don't use twitter and don't know how to use
it very well. How do I know wheb you will answer me?

Thanks
Bogdan

**Comment by DrKLO** [comment]
tg://msg?text=...&url=... was implemented in 3.1.1.

**Comment by valeriosouza** [comment]
Has no option to start a new chat? Only people who have talked?
