### ISSUE TITLE
Telegram official release

### ISSUE THREAD

**Issue by modmonkey** [DrKLO/Telegram#1216]
Sir 
We Know That Telegram is more stable and secure Than  others
But There Is No official release Version In Github
 
Why?

**Comment by DrKLO** [comment]
What you mean?
About what do you think this repo?

**Comment by modmonkey** [comment]
Sir developer of jabber,kontalk,chatsecure,jitsi,conversation everybody release compiled version on github

**Comment by DrKLO** [comment]
For what? Download it for play market or build by yourself.

**Comment by modmonkey** [comment]
why Not From Github
