### ISSUE TITLE
How can i coppy button of stickers from new source code of telegram to old ?

### ISSUE THREAD

**Issue by Nekbakht** [DrKLO/Telegram#1224]
I have a old version source code of telegram and many things changed but a new version have button of stickers and i wanna to coppy this function to my version 
Can u say me what is name java code of keyboard and stickes?

**Comment by DrKLO** [comment]
I have no idea what you changed in your source code, so no. Nobody can help you with it.

**Comment by DrKLO** [comment]
Make patch from you current source code, download last source code from repo, then apply your patch and resolve conflicts.
