### ISSUE TITLE
telegram clients crashes when a bot sends them a message with invalid "reply_markup" value

### ISSUE THREAD

**Issue by mohsensafari** [DrKLO/Telegram#1232]
Hi, I was writing a bot in nodejs. then realized when I send a message with invalid "reply_markup", the android clients that receive the message will crash the value for "reply_markup" is:
```javascript
'{"keyboard": [[], [], [], []], "one_time_keyboard": true}' 
```

**Comment by DrKLO** [comment]
It was fixed on server side.
