### ISSUE TITLE
[HOW TO]how do i chnage user photo placeholders 

### ISSUE THREAD

**Issue by nOmi7** [DrKLO/Telegram#1233]
Hello I want to change the user placeholder which are circles to rectangles how do i do that ?
I am tried manythings but it did not go well any pointers to it will be really helpful

Thanks

**Comment by DrKLO** [comment]
AvatarDrawable.java

**Comment by nOmi7** [comment]
@DrKLO  I did try editing the code but its not working  
I made drawRect instead of canvas.drawCircle 
as canvas.drawRect(size / 2, size / 2, size / 2, size/2, paint); to try with but it chagnes the color to white and doest not apply the background fill over the name,

paint.setColor(color);
        canvas.save();
        canvas.translate(bounds.left, bounds.top);
       canvas.drawRect(size / 2, size / 2, size / 2, size/2, paint);

**Comment by DrKLO** [comment]
http://developer.android.com/reference/android/graphics/Canvas.html#drawRect(float, float, float, float, android.graphics.Paint)
Look at function args? why size / 2 everywhere?
