### ISSUE TITLE
In-app playback of external videos stopped working after upgrade to version 3.1.0

### ISSUE THREAD

**Issue by giordano** [DrKLO/Telegram#1234]
With version 3.0.1 I noticed accidentally that this app was able to play a YouTube video without opening an external app (browser or YouTube app), but after upgrading to version 3.1.0 I can no longer use this feature.  Is there an option to activate this?  I can't find it either.

**Comment by DrKLO** [comment]
Only for android 4.4+ since old android version doesn't update its system webview from play store.
