### ISSUE TITLE
[3.1.1] Opus files not recognized as music

### ISSUE THREAD

**Issue by gFreezer** [DrKLO/Telegram#1235]
If I share an mp3 file via Telegram, it appears in form of a little player where you can play the file in-app.
If I try the same thing with opus files, they just appear as downloadable file without a player. This is kind of awkward as the voice messages also use opus afaik, so Telegram should already be able to play opus streams in-app.

**Comment by DrKLO** [comment]
And shouldn't. Opus only for voice notes.

**Comment by gFreezer** [comment]
reason?
