### ISSUE TITLE
BOT slash command menu should enter command in message box, not send it off immediately

### ISSUE THREAD

**Issue by ADTC** [DrKLO/Telegram#1236]
The slash commands listed in a bot's slash `/` menu is useful, except that bots often have commands that accept parameters (arguments). In that case, the menu becomes useless as selecting a command fires it off to the bot immediately.

Instead of that, it should simply enter the command in the message box (with a trailing space and the caret after that). This lets the user type in any optional arguments and then send the command to the bot.

This should also apply to command links in the chat, in bot description, etc.

**Comment by DrKLO** [comment]
No, it shouldn't.

**Comment by ADTC** [comment]
Why? How to use commands that accept parameters? Manually type it in all the time? You don't realize how painful that is?

**Comment by Mindstormer619** [comment]
C'mon, @DrKLO, don't be an ass. There's another issue at #1190 regarding the same thing. There are enough people and logical reasons already presented. Don't close issues giving half-assed reasons, please.

**Comment by ADTC** [comment]
Vote for re-open.
