### ISSUE TITLE
[Question] about PTS  and SEQ

### ISSUE THREAD

**Issue by nOmi7** [DrKLO/Telegram#1240]
Hello 

I wanted to know how is PTS and SEQ calculated by the server for any updates the  i see its getting incremented even if a delete a contact or add one .. and not only on message/chat  send , read , delete etc ..actions .

when is the value of pts reset  to 0 again ? It always getting incremented for diff user/diff dialogs too. same is with the TLRPC.messages_SentMessage.id  when does it reset to 0.

How does the value of PTS and SEQ affect the client behaviour ?

https://core.telegram.org/constructor/updates.state is not clear to me .

any pointers will be really helpful.

Thanks

**Comment by DrKLO** [comment]
https://core.telegram.org/api/updates
PTS for all updates with messages actions.
SEQ for all other updates.
PTS never reset to 0.
I don't know how it's calculated, I'm not server dev.
