### ISSUE TITLE
[Q] how to add contact with phone number programmatically?

### ISSUE THREAD

**Issue by mokhtarabadi** [DrKLO/Telegram#1242]
which method Can i use for add a new contact from a phone number? (which class?)

**Comment by wfjsw** [comment]
Just create a contact to system's contacts book and it will import to telegram automatically.

**Comment by mokhtarabadi** [comment]
@wfjsw I want to do it programmatically

**Comment by wfjsw** [comment]
@mokhtarabadi Just programmatically write to contacts book using Android API :full_moon_with_face:

**Comment by mokhtarabadi** [comment]
@wfjsw No, I don't want to use Android system phonebook.
I found this method but it has limit
       TLRPC.User user = new TLRPC.TL_user();
        user.first_name = "Mohammad";
        user.last_name = "Mokhtari";
        user.phone = "+98933324****";
        ContactsController.getInstance().addContact(user);

I want to add many contacts (more than one hundred) at one time.

**Comment by wfjsw** [comment]
As telegram keeps everything on cloud, it must have an API limit to prevent users from flooding their servers. I think this is not an app issue but Telegram itself's. You may contact Telegram support.

**Comment by DrKLO** [comment]
https://core.telegram.org/method/contacts.importContacts
