### ISSUE TITLE
Some times messages are not notified... until telegram is opened

### ISSUE THREAD

**Issue by ggrandes** [DrKLO/Telegram#125]
Checked on wifi, connection checked and is ok, but messages don't input until app opened

**Comment by 3zzy** [comment]
This is the only feature stopping me (and possibly other millions of users) from switching to Telegram. Notifications just don't work. They show up as soon as you open the app. For a message app, this is just not acceptable.

**Comment by fduraibi** [comment]
@3zzy Are you sure you are not using any other application that cleans cache data and kill background apps?

I use Telegram on different phones (Nexus 4, Samsung Galaxy S2, and many emulators) and my friends too and none of them have this problem. Only one guy has it but he is using a cleaning app that kills Telegram.

**Comment by tdido** [comment]
In both my Moto G and Galaxy Note 10.1 2014 (neither have Google services), the situation is similar to the one described by @kastedo, except that in my case it happens also when on WiFi.

**Comment by midi** [comment]
@DrKLO I changed my setup. Not running any VPN currently, still running stock 5.0.1 on my Nexus 5.
Telegram failed to notify me last week on Friday (Play Store version) of new messages.
Device was connected to a stable and strong WiFi connection.
The notification service was disabled.
If I recall correctly, the messages arrived several hours later, without me opening Telegram.
The weird thing is, that at the time of the sent messages, I was actually using my device and using other Internet services, so I most definitely wasn't offline.

Resorted to activate the Notification Service, while my contact was in town, to be able to have a reliable communication channel.
This results in a visible battery consumption as can be seen in the battery monitor.

If there's anything for me to help fixing this horrendous behavior, let me know!

**Comment by muava12** [comment]
And this issue still not yet resolved until now. I get same problem here, using the latest version from google play

**Comment by AUDI-A4** [comment]
@muava12 you are right.One of my friend never get notified though his notification service is running in background.He is using redmi

**Comment by AUDI-A4** [comment]
It works perfectly in wifi networks not working properly in mobile data connection

**Comment by muava12** [comment]
I opened new issue severeal days ago #1026 , not yet commented by @DrKLO

but just tried v2.8.0 pre-release version, and surprisingly this problem solved on my device. Let me know that on next release this issue wil be solved on your (or your friends) device too

**Comment by Mosrite** [comment]
While I don't have the problem myself, three of my friends do have it. And they're definitely not tech-savvy enough to install something like a process killer. Whatsapp runs smoothly on their devices, so they start to get annoyed of Telegram... :/
It would be so great if this could be fixed!

**Comment by srikrishnacj** [comment]
My phone does not receiving any messages after i closed application... my friends have the same problem... telegram is much faster than whatsapp and available for multiple platform, UI looks cool.... but for me an application does not do its job properly is just garbage... I am not able receiving anything even after i enable notification services. year old bug is not resolved yet... poor support

**Comment by AUDI-A4** [comment]
i dont know, why developer does not take it seriously, dev thinks it works for us thats all.IM app without notification is of no use.

**Comment by srikrishnacj** [comment]
I guess this App is not for everyone... this app is only targeted for those who want to hide chat from Russian security agency... I will continue to use whatsapp... i am gonna use awesome telegram desktop client

**Comment by AUDI-A4** [comment]
suprisingly, none of my friends want to use this app and no one friend is using this app. This app is having lack of users count. i am forcibly using whatsapp.Some of my friends tried this app and they got frustated because of never notified from app.This company came with news like we have 2 billion active msgs sent daily that is not a big deal.A one user sent 1000 msg to another msg by spamming.It actually matters how many active users you have.So if you see that point of view it has already crossed 800 million active user that is huge.

**Comment by srikrishnacj** [comment]
All of my friends use whatsapp. Whats interesting with telegram is its beautiful native client for all platforms and secret chats. so we thought to give a try. but Its useless with out proper notifications. Its not working with MI OS and Moto G. only where the notification worked for me is Andyroid Emulator.

**Comment by AUDI-A4** [comment]
Secret chat is not a big deal.Whatsapp is using same thing like telegram secret chat

**Comment by AUDI-A4** [comment]
Nothing interested in secret chat telegram i found.none of my friends found the secret chat good.

Worst thing i found in telegram is emoji which is too small and bullshit

Another bullshit i found while forwarding msg, text will be quoted

Believe me, somehow they are managing servers because there are not much users in telegram.They are saying Telegram will be free forever but it wont at all once they will be out of money.

Support 200 members in groups and sending pdf is not a big deal.These kind of things, whatsapp can do easily

**Comment by ggrandes** [comment]
Issue was corrected in a far away time
