### ISSUE TITLE
[BUG] Sharing image as file changes extension to .file

### ISSUE THREAD

**Issue by Roxot** [DrKLO/Telegram#1256]
When sharing an image as a file it changes its extension to .file, which causes problems in opening the image. The image is shared by hitting the "share file"-button in Telegram, choosing "Gallery" and picking the correct image in the Google Photo's app that comes up. 

I'm using a Nexus 5 running Android 5.1.1, Telegram for Android v3.1.1 (580) and Google Photos build 1.2.0.98687623. Also see the screenshot attached. 

![bug](https://cloud.githubusercontent.com/assets/2978452/8889103/1f0ecbf4-32cb-11e5-8f58-12aa894ba71a.jpg)

**Comment by DrKLO** [comment]
Google changed content provider in last google photos version. This will be handled in next release.
