### ISSUE TITLE
Nexus 7 Notification LED issue 

### ISSUE THREAD

**Issue by kgizdov** [DrKLO/Telegram#1263]
Hi, 

On my other devices, I'm easily able to adjust the colour of the notification LED through the settings. However, on the Nexus 7, regardless of what I specify in the settings, the LED is always white. I've tried it on a friend's Nexus 7 and the issue is also present. 

Regards

**Comment by nadam** [comment]
It's because your other devices have multi-color LEDs. The Nexus 7 LED is white only.

**Comment by kgizdov** [comment]
Haha, should have checked that first... Thanks
