### ISSUE TITLE
New mention in group @all

### ISSUE THREAD

**Issue by yolapop** [DrKLO/Telegram#1265]
I don't know if the team have thought of this. Sometimes people mute groups, and in effect, they're excluded from the conversation except when they're mentioned personally. Sometimes people just throw random important news for all to see. The other people who have muted the groups would see the news rather late and sometimes never.

I think it would be handy if there's `@all` that will notify all people in the group even if they have muted the group. What do you think?

**Comment by nadam** [comment]
I think that would be annoying. If I mute a group I want it to be quiet unless someone mentions me specifically.

**Comment by yolapop** [comment]
I know that this feature might get abused as people can flood `@all` all the time, but if you find one person who abuses this mention then you can just right kick him from the group.

I think it's a neat feature regardless how it's going to notify people. Slack has `@everyone` too.

**Comment by DrKLO** [comment]
@all already working for group admins.

**Comment by yolapop** [comment]
@DrKLO but not working for non-admins? Why is that?

**Comment by imaihikaru** [comment]
@DrKLO is it just for group admin? I agree if non-member can use @all mention because sometimes they have important message for all of member.

**Comment by DrKLO** [comment]
It's server side. Nothing can be done on client side.

**Comment by nadam** [comment]
@imaihikaru non-admins could ask the admin to send the important message and the admin can decide whether it's important enough.

@DrKLO what would be the best place to report server side issues. We have another issue that has been reported repeatedly to all the support channels for a month without any proper reply.
