### ISSUE TITLE
[guidance] Extract pure Java API

### ISSUE THREAD

**Issue by nadam** [DrKLO/Telegram#1272]
I've started extracting code from this project to create a pure Java API. There is another Java API already at https://github.com/ex3ndr/telegram-api but it's out of date and not maintained anymore.

The way I'm doing this is to remove all GUI stuff and dependencies to Android SDK and libtmessages.7.so. It's quite difficult though so I wonder if I'm wasting my time on an impossible project or not. Or maybe someone else is working on something similar already and we can team up.

**Comment by DrKLO** [comment]
There is no other Java projects for Telegram. Soon network part of this repo will be moved to C++.

**Comment by nadam** [comment]
@DrKLO ok, but would you say it's straight forward to extract a pure Java API this way or would it require weeks of reverse engineering libtmessages.7.so or some other obstacles?
