### ISSUE TITLE
Broadcast List for web app :Feature Request

### ISSUE THREAD

**Issue by spectrojin** [DrKLO/Telegram#1276]
Hi Guys,

I really like using Telegram. it's a good alternative to whatsapp and even better in some regards.
But what I am really missing is to use broadcast lists on the web interface, which comes really handy when using it on my laptop. I would really love to see this one on telegram web.

Thanks and Regards.

**Comment by DrKLO** [comment]
This project only about Android app.

**Comment by spectrojin** [comment]
where do I post my queries about the Telegram web ?

On Fri, Aug 7, 2015 at 1:15 AM, DrKLO <notifications@github.com> wrote:

> This project only about Android app.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DrKLO/Telegram/issues/1276#issuecomment-128484010>.
>



-- 

----------------------------------

Sameer Khan
Associate System Engineer
IBM India Pvt. Ltd.

<http://www.facebook.com/spectrojin> Facebook
<http://www.facebook.com/da.sameerkhan>
<http://www.twitter.com/sameer_khan> Twitter
<http://www.twitter.com/sameer_khan>
<http://www.linkedin.com/profile/view?id=41551343> LinkedIn
<http://www.linkedin.com/profile/view?id=41551343>
