### ISSUE TITLE
[Feature request] Remote content attachment

### ISSUE THREAD

**Issue by afshinpir** [DrKLO/Telegram#1277]
Hi all

I thought this feature can be really great for telegram.
When you add a link to your post, telegram makes a headline for it automatically. But I though it will be  great if it could automatically attach media content to message rather than just a headline and creating link.
For example, If I post a youtube link, rather than creating a link and headline for it, it remotely get that youtube video and attach it to post. maybe adding a post mode to differ between these 2 types will be a good option too.

This feature needs some server side help and cannot be done from client side alone for sure.

Regards

**Comment by DrKLO** [comment]
This repo only about android client, I can't help you with that.
