### ISSUE TITLE
[feature request]get audio stream and photo for bot

### ISSUE THREAD

**Issue by developerAy** [DrKLO/Telegram#1279]
Hi there. 
As a telegram bot developer, i want to develop a bot which can be controlled by voice. 
But as a matter of fact you just send audio object which contains file_id and not the audio stream.
I propose to send audio streams when the bot developers get updates so that we can process the voice. 

The same thing happen for photos, I wanna process images with computer vision algorithms and don't have access to the image itself but only the file_id. 

Please add this feature for bot developers. 

Best regards.
Ayoobi.

**Comment by mokhtarabadi** [comment]
+1

**Comment by DrKLO** [comment]
I'm not API developer, i can't help you with that.
