### ISSUE TITLE
[iOS and Android] "Add to Stickers" missing in secret chats

### ISSUE THREAD

**Issue by wp9015362** [DrKLO/Telegram#1280]
@DrKLO :

As described in the following Telegram Blog entry:

> https://telegram.org/blog/stickers-revolution
> 
>  [...] When you receive a sticker from a set you do not currently have installed,
> simply tap on it and choose ’Add to Stickers‘ (’Info' on iOS) to preview and add the whole set. [...]

there should be an "Add to Stickers" option when you tap on a sticker that you haven't installed yet.

I mean this one:

![Image](https://cloud.githubusercontent.com/assets/7558360/9134696/0ba734d4-3d07-11e5-8676-c91f61879032.png)

But this option is only available in standard chats.

It's not available in secret chats.

In both Telegram for iOS as well as in Telegram for Android, this option is missing in secret chats.

Could you please fix that and also forward it to the Telegram for iOS developers, so that they can also fix it for Telegram for iOS (couldn't find an issue tracker for the iOS version, so I posted it here, since both, the Android version as well as the iOS version are affected)?

Regards

**Comment by DrKLO** [comment]
Secret chats API doesn't support this.
