### ISSUE TITLE
Video compression parameters

### ISSUE THREAD

**Issue by seccomiro** [DrKLO/Telegram#1281]
Is there any different video compression parameter between the GitHub code and the Google Play official app?
I can't achieve the same final video quality.
Mine is really really poor and the other is nicer.

Take a look at this video: https://www.dropbox.com/s/xhle4dw5u0arxx3/VID_20150807_17263-small.mp4?dl=0

**Comment by DrKLO** [comment]
There is no difference at all. Everything is the same.
