### ISSUE TITLE
OGG audio files are not supported

### ISSUE THREAD

**Issue by danialbehzadi** [DrKLO/Telegram#1282]
When I choose audio from attachment menu, it list all mp3 audio files, but not OGG(vorbis) audio files. I think this is important for a free software to support free file formats and standards.

**Comment by KrisKorrel** [comment]
I'm able to send ogg files just fine. Your problem may have something to do with where your ogg files are stored.

**Comment by danialbehzadi** [comment]
Yes. My bad

**Comment by danialbehzadi** [comment]
Some one close this issue FGS.
