### ISSUE TITLE
Implement a functionality to listen to all voice-messages in a group chat

### ISSUE THREAD

**Issue by tihansen** [DrKLO/Telegram#1283]
Me and my friends rely heavily on voice-messages in group-conversations and it is already helpful to have the little indicator showing "unread" messages, but you have to listen to every single one and tap it manually. 

Some kind of button to listen to all new and unread voice-messages in a continous conversation would be really awesome and time-saving! 

Thanks in advance for taking the time!

**Comment by AUDI-A4** [comment]
Duplicate  https://github.com/DrKLO/Telegram/issues/1116

**Comment by tihansen** [comment]
You are absolutely correct, this is a duplicate. Thanks!
