### ISSUE TITLE
Request: Block a user in Groups

### ISSUE THREAD

**Issue by DRSDavidSoft** [DrKLO/Telegram#1285]
Hi there, this is my proposal for a new feature in Telegram.

*Blocking a user in Groups*

**Problem:**
When a certain user is blocked on the Telegram, one can still receive his or her messages on the same group where they are both members.

**Suggested Solutions:**
* There should be an additional option located at the Group Settings to *block* certain members. By adding users to this blacklist, all (or part) of his or her messages should be ignored and not displayed in the group. It should be able to block *messages*, *stickers*, *media*, or a combination of them. Using checkboxes would be efficient for this.
* When blocking a user in Telegram, we should be presented with an additional checkbox, which would ask if the user should be ignored on ALL groups too. If this option is enabled, Telegram should ignore any messages/stickers/media from the blocked person.

I hope you find these hopeful.
Thanks for taking time.

**Comment by DrKLO** [comment]
Not client related.
