### ISSUE TITLE
Request: Block certain Stickers

### ISSUE THREAD

**Issue by DRSDavidSoft** [DrKLO/Telegram#1286]
Hi there, this is my proposal for a new feature in Telegram.

*Blocking certain Stickers in Telegram*

**Problem:**
A user can send a disgusting or NSFW sticker over and over. In case blocking the user wouldn't be an option, we need to block the sticker.

**Suggested Solution:**
By default, Telegram's stickers are divided to two types: Standalone .webp files and Sticker Packs.
If a .webp file is being sent over and over, the content would be the same, meaning their file hash would also be the same.

The idea is to keep a blacklist containing MD5 hashes of blocked stickers. Now each time a new sticker is received, Telegram should calculate and compare the sticker's hash within the blacklist. If the hash is matched, Telegram should ignore and delete the Sticker (thus not saving it to the Phone.)

For the Sticker Packs this could be applied too, however there should be an option to block a Pack of stickers *entirely*.

Now a workaround to this is to modify the Sticker's content a bit to change the hash, but this would only happen if the user learns that the Stickers he/she is sending is blocked.

I hope you find these hopeful.
Thanks for taking time.

**Comment by DrKLO** [comment]
Not client related.

**Comment by DRSDavidSoft** [comment]
Why not? By the definition, the client have to ignore and hide the stickers, how the server could?

**Comment by auchri** [comment]
The blocked stickers should be synced to all clients, so there should be a server api for that

**Comment by DRSDavidSoft** [comment]
Quite right... So where should I ask for the API to be added by the developers? Are they on GitHub?
Also, the client *could* also use a custom or third-party to sync additional data... including this feature ;) Not that it *should*.

**Comment by auchri** [comment]
Twitter: twitter.com/telegram
