### ISSUE TITLE
[Feature request] Group Admin,Add to the group by username & add people only from admin.

### ISSUE THREAD

**Issue by andrepaandrea** [DrKLO/Telegram#1289]
I'd like to have something like group permission.
e.g. nominate group admins
I'd like to add people to the group by username ,without use necessary the phone number and I don't like that people can add other people without have the privileges.
(p.s. sorry for the incorrect english)

**Comment by DrKLO** [comment]
Not client related, no API for that.

**Comment by wfjsw** [comment]
You can add by username, using the well-hidden search button on the top of the contact chooser.
