### ISSUE TITLE
send quiet message by demand (feature)

### ISSUE THREAD

**Issue by arieljannai** [DrKLO/Telegram#1290]
Hi,

__TL;DR__: Send a quiet message (no sound at the receiver side).

A bit longer:
It can be great if I could send someone a message, that I decide that it will be quiet (by some flag).
Sometimes, I want to send someone a message (in the middle of the night for example), and I only want to send it now cause that's the moment it popped into my head, I don't care if the person will see it tomorrow morning, and I don't want to interrupt if he's going to wake up from the message notification sound.

What do you think about it?
Reasonable? Useful?

Thanks,
Ariel

**Comment by DrKLO** [comment]
Not client related, no API for that.

**Comment by arieljannai** [comment]
Is there a place it is related, or I can suggest it?

**Comment by omyno** [comment]
I like your idea. What you could try is to send a message to https://twitter.com/telegram . Or go to Settings -> Ask a question.

**Comment by arieljannai** [comment]
@omyno cool, I'll try that :smile:
