### ISSUE TITLE
Telegram app contacts and Chat history syn to my Custom app

### ISSUE THREAD

**Issue by munna0541** [DrKLO/Telegram#1297]
Hi, I successfully renamed the package, configured all the BuildVars and built it. It is successfully running and working great. But the main problem is, it is displaying the All the Telegram App Contacts List and My Previous chat history in both Telegram and in My Custom App as well. Even chat notifications also I'm getting for both the apps.

Can you please help me to get resolve of this.

**Comment by DrKLO** [comment]
Since this apps are using same Telegram API - it's ok. To avoid this you need to write your own server.

**Comment by omarkerr** [comment]
@munna0541 contact me please at odecejr@gmail.com
