### ISSUE TITLE
Telegram unusable in multi-window mode when 

### ISSUE THREAD

**Issue by Yajo** [DrKLO/Telegram#1305]
Now that we have multiwindow (https://github.com/DrKLO/Telegram/issues/419), when the tablet is horizontal, Telegram becomes almost unusable. See screenshot in Galaxy Tab A:

![screenshot_2015-08-27-08-40-29](https://cloud.githubusercontent.com/assets/973709/9514533/2030bdd2-4c9b-11e5-84e7-025e10c49fa0.png)

It would be nice to use the mobile view in such state.

**Comment by DrKLO** [comment]
Since it's not official android feature, there will not be any support of it. I don't like samsung and their buggy software.

**Comment by Yajo** [comment]
That bug is a feature for some people. Chatting and browsing at the same time is useful IMHO. Would you accept PR at least?

**Comment by DrKLO** [comment]
Fixing this requires adding their multiwindow sdk to app for detection that it was enabled in runtime. I don't think that it's good idea, since it can bring other bugs in app.

**Comment by Yajo** [comment]
Ah OK. I never developed for Android, but I thought it had some kind of responsive layout feature. Thanks anyway.
