### ISSUE TITLE
Feature Request: gateway to let users partecipate to telegram chats with email

### ISSUE THREAD

**Issue by aronchi** [DrKLO/Telegram#1307]
Telegram is a great app, but It doesn't have the greatest diffusion for this kind of app.

To increase Telegram user base, and let telegram users invite gradually other people, I think an email gateway should be a great improvement.

Let say I have 10 friends. Everyone uses another evil chat app, and 8 uses telegram. I cannot open a telegram thread because of this two evil friends wich refuses to install the telegram client.

But everyone have an email. So, I could add them by email:
1) they can receive one email every 5 minutes of chat and answer to a telegram+chat_id email to  answer to us
2) they can decide to receive only one daily email
3) they can decide to don't receive one chat or no telegram email at all to avoid spam

You can also make an opt-in to partecipate to a chat.

The great advantage is that everyone has an email. You can also create an invite to telegram in the email footer. With special email tags / subject and email user can also aprtecipate actively to Telegram. Maybe one day they will subscribe to the service.

This would also be useful where there's a firewall against telegram protocol or a proxy that limits telegram website: one could use a standard email also if he has a telegram account, maybe by chat/group settings.

**Comment by DrKLO** [comment]
Not client related.
