### ISSUE TITLE
Clickable links

### ISSUE THREAD

**Issue by auchri** [DrKLO/Telegram#1328]
If I send someone a link (e.g. example.world), the link is clickable.

When I open the same chat again, the link is no longer clickable:
![device-2015-09-04-180543](https://cloud.githubusercontent.com/assets/5092164/9688500/d93abdd8-532f-11e5-8e1b-528d88e6eaa0.png)

It's because of https://github.com/DrKLO/Telegram/commit/906746d573e73ab185f05dc919a65fa9d364da35#diff-a8bad98093e611dcbbfa6a7df7c4e4c7R673

Android parses the links different as the server

**Comment by DrKLO** [comment]
Before message is sent android will parse it with Linkify, after it takes links from server. It's ok.
