### ISSUE TITLE
Contact Duplication 

### ISSUE THREAD

**Issue by zambotn** [DrKLO/Telegram#1332]
@DrKLO Telegram contacts keep multiplying: yesterday I had x7 of each contact so I removed duplicated manually but after one day they appear (x4) again. (so I suppose it's a synchronization issue).

**Comment by DrKLO** [comment]
Contact duplication in phonebook? You probably using some device specific restriction to access phonebook, which forbid app to read contacts, but allow to add it. So app doesn't know this it was already  in phonebook and writing it again.

**Comment by zambotn** [comment]
That's right. Im using i Xiaomi phone and it has a builtin permission manager that (randomly) chose to forbid telegram to read contacts.
