### ISSUE TITLE
Is there a way to avoid receiving 420 FLOOD errors when debugging ?

### ISSUE THREAD

**Issue by thibauld** [DrKLO/Telegram#1333]
Hi,
I just got a FLOOD_WAIT_X error because, for debugging purposes, I am currently making tests that require to login and logout from telegram. Now I just need to wait some hours before continuing but is there a way I can avoid getting those FLOOD_WAIT_X in the future ? A sandbox server I could use to perform my tests instead of the production one ? A special debug mode that would just emulate the user authentication ? Any solution would be very welcomed.
Thanks

**Comment by DrKLO** [comment]
You may try test backend, look ConnectionsManager.java, loadSession()
