### ISSUE TITLE
Cannot get to automatically open a specific chat when the user logs in

### ISSUE THREAD

**Issue by thibauld** [DrKLO/Telegram#1339]
I am trying to display a ChatActivity fragment every time a user opens Telegram.
I was able to do it very easily when the user is already logged in by adding the following ```onStart()``` method to the LaunchActivity class:
```
protected void onStart() {
        super.onStart();
        if (UserConfig.isClientActivated()) {
            Bundle args = new Bundle();
            args.putInt("user_id", 12345678);
            ChatActivity fragment = new ChatActivity(args);
            actionBarLayout.presentFragment(fragment, false, true, true);
        }
    }
```

However, I am banging my head because I am unable to get the same result *right after* the user logs in. More specifically: If the user is not logged in when he opens Telegram, a LoginActivity is being display. At the end of the LoginActivity, ```needFinishActivity()``` is called and displays a DialogActivity. Unfortunately, replacing the DialogActivity by a ChatActivity in this method does not work.
```
public void needFinishActivity() {
        clearCurrentState();
        Bundle args = new Bundle();
        args.putInt("user_id", 12345678);
        ChatActivity fragment = new ChatActivity(args);
        presentFragment(fragment, true);
        NotificationCenter.getInstance().postNotificationName(NotificationCenter.mainUserInfoChanged);
    }
```

```presentFragment()``` systematically fails because, in  ```ChatActivity::onFragmentCreate()```, the ```MessagesStorage.getInstance().getUser(userId)``` returns null. It seems that the App is still not initialized even though, before calling ```presentFragment()```, I test ```UserConfig.isClientActivated()```.

Thinking that I was calling ```presentFragment()``` to soon (before everything is initialized), I even tried another implementation where I call ```presentFragment(new ActivityChat(args))``` from ```DialogActivity::onBecomeFullyVisible()``` but it did not work either.

So I am now short of ideas: How can I manage to display a ChatActivity right after the user login ? Any help, pointer, tip, would be really appreciated ! Thanks a lot

**Comment by thibauld** [comment]
I was able to *sometimes* get the specific chat to open after login. It looks like the issue is the following: if the dialogs have already been retrieved in the background when ```MessagesStorage.getInstance().getUser(userId)``` is called, then the function does not return null and the chat opens after login. However, most of the time, the dialogs do not have the time to load and it causes the function to fail and return false. How should I "elegantly" tackle the issue ? In which method would you ideally trigger a notification to display the specific chat after login ?
Thanks a lot for your help on this

**Comment by DrKLO** [comment]
With which user you want to open chat? If you want to open chat with yourself, you can call MessagesController.getInstance().putUser(UserConfig.getCurrentUser(), true); before opening chat

**Comment by thibauld** [comment]
Thank you very much, for your answer. I want to open a chat with a bot (@democrabot... which does not do much for now). Based on your example, what command should I use to retrieve the bot user information so that I can pass it to ```MessagesController.getInstance().putUser()``` ?
Thanks again!

**Comment by DrKLO** [comment]
So you should load this user first from server by username (see example at MessagesController.openByUserName)

**Comment by thibauld** [comment]
Great, I was able to get it working !
If it can help somebody else, here how I did it in the end.
In LaunchActivity:
```
    @Override
    protected void onStart() { 
        super.onStart();
        if (UserConfig.isClientActivated()) {
            if (!actionBarLayout.fragmentsStack.isEmpty()) {
                BaseFragment fragment = actionBarLayout.fragmentsStack.get(0);
                MessagesController.getInstance().openByUserName("username", fragment, 1);
            }
        }
    }
```
and this in LoginActivity:
```
    public void needFinishActivity() {
        clearCurrentState();
        Bundle dcargs = new Bundle();
        dcargs.putInt("openChatAfterLaunch", 1);
        presentFragment(new DialogsActivity(dcargs), true, true);
        NotificationCenter.getInstance().postNotificationName(NotificationCenter.mainUserInfoChanged);
    }
```
and finally in DialogsActivity:
```
    public DialogsActivity(Bundle args) {
        super(args);
        openChatAfterLaunch=args.getInt("openChatAfterLaunch", 0);
    }

    @Override
    public void onBecomeFullyVisible() { 
        if (openChatAfterLaunch==1){
            openChatAfterLaunch=0;
            MessagesController.getInstance().openByUserName("username", DialogsActivity.this, 1);
        }
    }
```

Anyway, I will publish the whole code source of our custom Telegram will be published here once it is functional : https://github.com/democratech

Thanks for your help !
