### ISSUE TITLE
[Security] Images deleted from secret chat are in cache

### ISSUE THREAD

**Issue by SkyWheel** [DrKLO/Telegram#1345]
Cached images from all secret chats are in `%sdcard%/Android/data/org.telegram.messenger/cache/`
According to Telegram FAQ, 
>As soon as the time runs out, the message disappears from both devices and leaves no trace.

![faq](https://cloud.githubusercontent.com/assets/10903432/9831115/3badcd30-598d-11e5-9ab9-c9995ef5246e.png)
>no trace.

I think there is urgent need to fix this issue.
...or we need to fix Telegram FAQ.
BTW, any ideas how to fix Telegram FAQ?

**Comment by DrKLO** [comment]
duplicate

**Comment by SkyWheel** [comment]
Hi @DrKLO ,
Could you please mention the number of duplicated issue?
