### ISSUE TITLE
Messages scroll the wrong way when using a mouse wheel

### ISSUE THREAD

**Issue by riesdepies** [DrKLO/Telegram#1348]
When I attach a mouse to my Android device and I use my mouse wheel to scroll in the converstation pane, messages scroll up when I expect them to scroll down and vica versa.

So when I 'push' the mouse wheel away (finger extends) the messages scroll up.
Expected behavior is that the messages scroll down.

Telegram for Android v3.1.3 (592)

**Comment by DrKLO** [comment]
You should address this issue to google or to your device vendor. There is nothing about Telegram. It doesn't handle anything like this manually.

**Comment by riesdepies** [comment]
Thanks for your response. Although I understand that the mouse-wheel scrolling behavior is not actively handled by Telegram, Telegram does however affect it. The reversed scrolling issue actually does not occur in older versions of Telegram, for example v2.7.0 (492) works fine. In some versions the issue only occurs within the messages panel, not in the contacts panel, for example v2.8.0 (516). In Telegram v2.9.0 (537) and later the issue occurs in both the contacts panel and the messages panel. I should add that I use Telegram in landscape mode on an Android TV-box (Minix Neo X7) on KitKat. 
Hope this is helpful. Best regards,

Richard
