### ISSUE TITLE
Open ChatActivity from other activity by user id

### ISSUE THREAD

**Issue by l3l4c7-h4t** [DrKLO/Telegram#1353]
hi,
i add some activity to telegram and in my activity have a button.

i want when some user clicked the button, open ChatActivity by user id (example: 95574322).

this is my code for do that:

Bundle args = new Bundle();
args.putInt("user_id", 95574322);
presentFragment(new ChatActivity(args), true);

my Activity extended to BaseFragment 

but does not any happen ...

please help, im so confused

Update:

i debugging  and i saw "actionBarLayout" is null. Perhaps that is because of this (null actionBarLayout )?

sry for bad type english.

**Comment by DrKLO** [comment]
Use search.
