### ISSUE TITLE
Feature request: set displayed name on per-chat basis

### ISSUE THREAD

**Issue by levitsky** [DrKLO/Telegram#1355]
It would be very nice to be able to change your displayed name in a specific group chat.

Use case: a chat for an online game, where you don't really want to use your real name and would rather put your game username as displayed name, vs texting your regular contacts (whom you don't want to confuse by using your in-game name, of course).

Any chance this could be implemented? Thanks.

**Comment by DrKLO** [comment]
Not client related.
