### ISSUE TITLE
Impossible to send anything since last update

### ISSUE THREAD

**Issue by guillermogf** [DrKLO/Telegram#1357]
I can't seem to send any file since last update from the Play Store.
I get the error icon (white exclamation mark with red background) with anything I try sending.

Android 4.0.4
Huawei Ascend P1 (U9200)
Telegram 3.2.0 (621) - Play Store

**Comment by DrKLO** [comment]
https://code.google.com/p/android/issues/detail?id=24327

**Comment by guillermogf** [comment]
What do you mean with that/What does that mean?

**Comment by DrKLO** [comment]
This is Android 4.0 bug. Trying to find workaround.

**Comment by DrKLO** [comment]
3.2.1 (624) on the way to play market
