### ISSUE TITLE
Public Key, where to put

### ISSUE THREAD

**Issue by EdoEscada** [DrKLO/Telegram#1362]
Where do I have to put this Public Key : 

Public keys:
-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAwQEAwVACPi9w23mF3tBkdZz+zwrzKOaaQdr01vAbU4E1pvkfj4sqDsm6
lyDONS789sVoD/xCS9Y0hkkC3gtL31tSfTlgCMOOul9lcixlEKzwKENj1Yz/ws7daS
an9tqw3bfaUV/nqgbhGX81v/+7RFAEd+RwFnK7as+XYl9sluzHRyVVaTTveB2GazTw
Efzk2DWgkBluml8OREmvfraX3bkHZJTKX4EQSjBbbdJ2ZXIsRrYOXfaA+xayEGB+
8hdlLmAjbCVfaigxX0CDqWeR1yFL9kwd9P0NsZRPsmoqVwMbMu7mStFai6aIhc3n
Slv8kg9qv1m6XHVQY3PnEw+eQQtqSIXklHwIDAQAB
-----END RSA PUBLIC KEY-----

**Comment by DrKLO** [comment]
for what? source code already contains all public keys to work with mtproto

**Comment by EdoEscada** [comment]
thank you for info, Doc
