### ISSUE TITLE
Allow terminating single Sessions

### ISSUE THREAD

**Issue by stefan-niedermann** [DrKLO/Telegram#237]
Currently i'm only able to terminate all sessions.

I want to be able to terminate single sessions.

Use-Case: I'm using telegram on much different devices. in holiday i want to use a web client on a public internet caffee. after holiday i want to terminate exactly *this* session, but i can only terminate *all* sessions.
now i have to login every device, i am using.

**Comment by Jenjen1324** [comment]
+1

**Comment by DrKLO** [comment]
There is no API for that.
