### ISSUE TITLE
Sync unread counter/notifications across all devices

### ISSUE THREAD

**Issue by jeroenpraat** [DrKLO/Telegram#249]
Hi,

(Maybe this is not the right place to ask this. If not, please tell me where to submit this issue?)

Currently a notification is send to all devices. That's OK. But after you opened/read the message on one device, the notifications don't disappear on the other devices. Also the unread counter inside those other apps (smartphone or web) isn't reset on the other devices. Result is that you have to open old messages on the other devices to be able to use the unread functionality again.

Thank you for fixing this.

Jeroen

**Comment by Plonq** [comment]
Just got Telegram myself. Android notifications not disappearing after reading the messages from TDesktop is really annoying. Hopefully gets fixed soon.

**Comment by Raffo** [comment]
I would love to have a look at the code regarding this issue... can you give me an hint?

**Comment by IcyTexx** [comment]
This is an issue both with Android and iOS... When focusing on desktop app, the notifications on phones are ringing.

**Comment by DrKLO** [comment]
I think now it's fixed

**Comment by manyata** [comment]
in my phone this issues is coming.. even after reading the messages from android app. the icon counter shows unread messages.!

**Comment by AAraKKe** [comment]
I have seen this happening as well when reading messages from the pc or Web
version.

**Comment by spawnazzo** [comment]
Same problem here. Neither message to read nor message counter blinking on desktop app, but i got some on the phone app.

**Comment by sergigp** [comment]
Related problem here,

After read notifications in iOS (iphone and ipad) I see unread notifications (from iOS home screen) and there is no way to mark it unread. 

When I open the iOS app there aren't unread messages but from home screen is impossible to make the balloons disapear

**Comment by kuchin** [comment]
I have the same problem now.

**Comment by danielsuter** [comment]
I have the same problem. There is a badge with 2 unread messages but there aren't any unread messages. The only "solution" is to uninstall the ios app and reinstall it, which kinda sucks.

**Comment by Michi-4G** [comment]
Same here: There are badges with unread messages but there aren't any unread messages.

**Comment by AAraKKe** [comment]
Check that you don't have any message about "you friend x has joined
Telegram." I usually forget that those messages also count as unread.
