### ISSUE TITLE
Password to protect secret chats

### ISSUE THREAD

**Issue by FezVrasta** [DrKLO/Telegram#307]
Hello, I love Telegram, it saved me from not-secure chats :)

By the way I was wondering if could be possible add a password to access secret chats, could be enough a single master password to protect them all **[1]**.
So when you try to open a secret chat, your password will be asked and only if you enter the right one you'll be able to access that chat.

I think a GNU/Linux `sudo` like system would be nice. Let me explain:
Open a secret chat, your password is asked.
Open after some minutes another secret chat, your password is remembered from the last time so is not asked.
Open after an hour, your session is expired and password is required again.

In this way you have not to write password each time but only at the beginning of each "session".

I'd love to send a PR by myself but I don't know Java :(

Thanks again and have a nice day.

**[1]**: would be safer lets user have a different password for each secret chat but probably would be too difficult for some people.

**Comment by DrKLO** [comment]
Password protection for app added in 2.5.0.
