### ISSUE TITLE
Pushbullet Support

### ISSUE THREAD

**Issue by eckcon** [DrKLO/Telegram#501]
Integrating Pushbullet would be awesome... I know, telegram has an awesome desktop-app, but there are many pushbullet-users who look for a solution to answer whatsapp-messages from their desktop-PC using pushbullet (which will never be possible), and they could all be potential new telegram users...
Also it would be great for those who don't want to use telegram on a desktop-PC and only want to answer some messages occassionally.
Please have a look at: http://docs.pushbullet.com/extensions/messaging/
Apps that already use this are for example chompSMS, EvolveSMS etc.

**Comment by KhaaL** [comment]
Wether it would be implemented or not, remember that any android user who enables notification mirroring will have them sent to their computer anyway. With this implementation however, a user could also reply instantly from the notification on their desktop. The telegram client could seize this opportunity to warn the user about the risks, but still leave the decision with the user to trust, or not to trust, pushbullets service.

**Comment by eckcon** [comment]
Pushbullet just included this functionality: https://blog.pushbullet.com/2015/02/17/reply-to-whatsapp-hangouts-and-more-from-your-computer-with-pushbullet-on-android/

They included it for Telegram, WhatsApp and others on their side, don't ask me how, but it works, so I'll close this issue since it became obsolete ;-)
