### ISSUE TITLE
Request: Vibrate only when silent

### ISSUE THREAD

**Issue by wiseoldman95** [DrKLO/Telegram#543]
Vibrating only when the phone is in silent mode is supported in most major apps, but not in Telegram.
Telegram:
![telegram](https://cloud.githubusercontent.com/assets/5030488/4009924/bce8b43c-29eb-11e4-81b5-e5ff7cac00f2.png)

Cyanogen SMS:
![cyanogen](https://cloud.githubusercontent.com/assets/5030488/4009925/bdfed9a0-29eb-11e4-944c-5313da8e2627.png)

**Comment by Madden91** [comment]
![1f44d](https://cloud.githubusercontent.com/assets/10641644/5846399/a355f23c-a1c3-11e4-913d-61dc3404ce3b.png)

**Comment by DrKLO** [comment]
It was implemented in 2.6.x.
