### ISSUE TITLE
Notification mute for a given time

### ISSUE THREAD

**Issue by AAraKKe** [DrKLO/Telegram#556]
I know that this can be done with other application that turn off notifications during a given time but I think that having the option inside Telegram itself would be nice and allows you to filter when you are receiving notification and not only from whom. Some small field in the notification configuration can be used for that.

What do you think?

**Comment by kael-shipman** [comment]
+1 -- I've been begging for this. G-chat used to have it. With two taps, you could choose to temporarily mute notifications for 5 minutes, 20 minutes, 30 minutes, 1 hour, 2 hours, 6 hours or 1 day. To add to that, it would be nice if there were an option to mute for "just this conversation" or "globally".

Please please pretty please!!

Thanks,
Kael

**Comment by AUDI-A4** [comment]
It is already implemented in Telegram
