### ISSUE TITLE
FEATURE: Option to select Videos and more

### ISSUE THREAD

**Issue by luisalvarado** [DrKLO/Telegram#565]
Right now, the options to select from the gallery inside Telegram only offer the option for images. It should be similar to Whatsapp where you have 2 tabs, one for images and one for videos.

This could also be extended to Text, Docs, Music files and more. But right now, the only difficult way is by selecting the file as a document and searching for it on the Android device. Very hard and not intuitive.

**Comment by luisalvarado** [comment]
Is this an option that could be added in the future? (Was is discussed already)

**Comment by DrKLO** [comment]
Video selection in in-app gallery implemented in 2.8.0.
