### ISSUE TITLE
Support for tussenvoegsels

### ISSUE THREAD

**Issue by 0d30** [DrKLO/Telegram#690]
Hello!

Dutch user here. I love the app, especially with the new Lollipop design.
In the Netherlands many people have a surname with "tussenvoegsels." Read more about it at http://en.wikipedia.org/wiki/Tussenvoegsel
My feature request is about support for these tussenvoegsels. Now, when a user is called "Jan de Vries" (de Vries being his surname), and has no avatar set, his avatar will be JD. However, it should be JV according to Dutch sorting conventions.
Could you add support for this?

Thanks in advance.

**Comment by DrKLO** [comment]
I think it was implemented some time ago.
