### ISSUE TITLE
When i try it using eclipse no compile time error when i compiled it is shows the following error

### ISSUE THREAD

**Issue by timoabi** [DrKLO/Telegram#710]
12-17 00:41:00.980: E/AndroidRuntime(28176): FATAL EXCEPTION: main
12-17 00:41:00.980: E/AndroidRuntime(28176): java.lang.UnsatisfiedLinkError: opendb
12-17 00:41:00.980: E/AndroidRuntime(28176): 	at org.telegram.SQLite.SQLiteDatabase.opendb(Native Method)
12-17 00:41:00.980: E/AndroidRuntime(28176): 	at org.telegram.SQLite.SQLiteDatabase.<init>(SQLiteDatabase.java:25)
12-17 00:41:00.980: E/AndroidRuntime(28176): 	at org.telegram.android.MessagesStorage.openDatabase(MessagesStorage.java:100)
12-17 00:41:00.980: E/AndroidRuntime(28176): 	at org.telegram.android.MessagesStorage.<init>(MessagesStorage.java:76)
12-17 00:41:00.980: E/AndroidRuntime(28176): 	at org.telegram.android.MessagesStorage.getInstance(MessagesStorage.java:67)
12-17 00:41:00.980: E/AndroidRuntime(28176): 	at org.telegram.android.MediaController.newDownloadObjectsAvailable(MediaController.java:660)
12-17 00:41:00.980: E/AndroidRuntime(28176): 	at org.telegram.android.MediaController.checkAutodownloadSettings(MediaController.java:546)
12-17 00:41:00.980: E/AndroidRuntime(28176): 	at org.telegram.android.MediaController$2.onReceive(MediaController.java:405)
12-17 00:41:00.980: E/AndroidRuntime(28176): 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:746)
12-17 00:41:00.980: E/AndroidRuntime(28176): 	at android.os.Handler.handleCallback(Handler.java:605)
12-17 00:41:00.980: E/AndroidRuntime(28176): 	at android.os.Handler.dispatchMessage(Handler.java:92)
12-17 00:41:00.980: E/AndroidRuntime(28176): 	at android.os.Looper.loop(Looper.java:154)
12-17 00:41:00.980: E/AndroidRuntime(28176): 	at android.app.ActivityThread.main(ActivityThread.java:4624)
12-17 00:41:00.980: E/AndroidRuntime(28176): 	at java.lang.reflect.Method.invokeNative(Native Method)
12-17 00:41:00.980: E/AndroidRuntime(28176): 	at java.lang.reflect.Method.invoke(Method.java:511)
12-17 00:41:00.980: E/AndroidRuntime(28176): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:809)
12-17 00:41:00.980: E/AndroidRuntime(28176): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576)
12-17 00:41:00.980: E/AndroidRuntime(28176): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by DrKLO** [comment]
Use Android Studio.

**Comment by LukeOwncloud** [comment]
Copy the binary libraries to Eclipse's libs folder: There should be three folders named armeabi, armeabi-v7a, and x86. Copy all of them to TMessagesProj\src\main\libs\
