### ISSUE TITLE
Telegram changing contact names at will

### ISSUE THREAD

**Issue by Yajo** [DrKLO/Telegram#713]
In my phone there are several address books (SIM, google, phone, another google, etc.). Sometimes I have the same contact in more than one of those, and telegram uses the wrong one to pickup the contact name.

I can understand that, it's my fault to have duplicates, so when I want it to show another name I just change it inside telegram. The problem is that sometimes I open telegram and notice it has changed the contact name back to what it wants, and thereafter it gets changed too in all my telegram devices.

I think that after changing a contact name manually it should stop trying to fetch it automatically.

**Comment by DrKLO** [comment]
I think it should be fixed now.

**Comment by accessarjun** [comment]
I have this problem in iPhone. When I change a name inTelegram, it automatically changes in iPhone. This works fine in Android version though. Is there a solution to this?

**Comment by venusbahar** [comment]
I have this problem on Android. In addition when i delete some contact on my phone book, i see it again in telegram contacts and when i try to delete it from telegram i receive message that this contact doesnot have telegram account! I think this is telegram bug. Another problem is that telegram duplicate some of my phone contacs and also rename contacts that i hate this. It is better to telegram have an option to update contacts list just like whatsapp!
