### ISSUE TITLE
TELEGRAM IMPORT HELP IN ECLIPSE

### ISSUE THREAD

**Issue by minigroups** [DrKLO/Telegram#730]
Hi i am boopathi from india,and i cant able to import telegram android source code to my eclpse , some errors , i done download zip file from here 

https://github.com/DrKLO/Telegram/archive/master.zip

after that what i want to do, pls any 1 help ,, @DrKLO pls give a visit here brother :)

**Comment by Paramfullestop123** [comment]
Hi friends @omarkerr pls tell me how setup telegram in your IDE.
I am import this project on Eclipse IDE and change BuildVars.java with App_ID and App_Hash but i got null pointer exception.

**Comment by Paramfullestop123** [comment]
Hi friends @minigroups pls tell me how setup telegram in your IDE.
I am import this project on Eclipse IDE and change BuildVars.java with App_ID and App_Hash but i got null pointer exception.

**Comment by modmonkey** [comment]
Minigroup use android studio and import project into android studio 
But before import the project connect your pc to internet so that android studio download's all necessary files including gradle

**Comment by mdahvkate** [comment]
F:\Telegram-master\TMessagesProj\src\main\java\org\telegram\ui\Components\PasscodeView.java
* Error (1) :(1014, 46) error: incomparable types: Object and int
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

* Error(2):Execution failed for task ':TMessagesProj:compileDebugJava'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED
Information:Total time: 1 mins 27.207 secs
Information:2 errors
Information:0 warnings
Information:See complete output in console
![error](https://cloud.githubusercontent.com/assets/12016953/7220114/051a1eac-e6da-11e4-92fb-14d002e54d71.png)

**Comment by mahdi-taghizadeh** [comment]
I downloaded telegram source for android from https://github.com/DrKLO/Telegram
, please tell me what am i doing to run telegram in android studio(on windows 7)?

Please tell the story Step by Step to run this project in android studio!

Is this project(https://github.com/DrKLO/Telegram) an android app project? or it is some library for android studio?

If this source is an android app project for android, Please tell me how i can open this project(https://github.com/DrKLO/Telegram) in android studio?(I have some problem to openning it) and how i can run the project?(the run button in android studio is disabled)

and when the project is in running, what happening should i expected for seen! (please tell Step by Step, i am a beginner in telegram programming).

**Comment by mdahvkate** [comment]
This code will not run..We required perfect knowledge of Android because
this code contain so many errors..
I was tried but not got proper success.

**Comment by mahdi-taghizadeh** [comment]
Thank you so much. I have many errors too.
Please if any one have a complete Source code with out any error share it.
Sincerely

**Comment by mahdi-taghizadeh** [comment]
when i opened the project i saw this error in android studio on windows 7:

Error:Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at http://gradle.org/docs/2.5/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for object heap
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by mdahvkate** [comment]
Hey !... W r doing u? any Business?

**Comment by mahdi-taghizadeh** [comment]
Fotunatley i resolved all the errors in this project 2 days ago! but unfortunatly when i run it on simulator it don't work and crashed! 
If i run it as soon as possible , i will share all of the source code and modules that's needed to run for you.

yes, i wana to to make my business. (-;

**Comment by mdahvkate** [comment]
Ok.. I will wait for your code.. If you need any help regarding Business
please share as friend
