### ISSUE TITLE
Feature request - "Smart notifications" for group chats

### ISSUE THREAD

**Issue by Darkwood77** [DrKLO/Telegram#738]
So, chats with more than 5 people are sometimes mighty annoying when they start beeping with a message every 10 seconds. And yes, I know there is of course a "mute" button, as I believe it was previously discussed, however, Viber messenger had an absolutely genius approach here that would be, I hope, very easy to implement:

They had "Smart Notifications" as an option for each individual group chat. If a group chat was set to "Smart notifications", the phone would beep for the first and second message, and then it would simply go quiet *for that particular chat* and not beep any more at all until that chat is open and read.

The benefit of this would be that, unlike in muted group chats, you would at least have the first 1 or 2 sounds so that you would know that the chat is active and that you need to look at it later. I am not a big fan at all for fully muting conversations, and I think this idea worked brilliantly in Viber. But Viber is rubbish, while Telegram is so much better and I would love to have this option there.

Thanks for all the great work!

**Comment by PioneerAxon** [comment]
Another addition that I personally think would be better is to allow limited number of notifications for groups for specific duration.  So user can select "sound atmost X times in Y duration". This would give user finer control on group notifications. You can achieve the result suggested by Darkwood77 by setting it to "sound atmost 2 times in my lifetime". A user with different needs can set it to "sound atmost 2 times in 2 hours". Or, otherwise "sound always", at which point app would disable the duration selection part.

Hope this helps.

**Comment by Ofekalef** [comment]
Brilliant offer, I hope someone will implement it!

**Comment by PioneerAxon** [comment]
I have created a simple hacky patch [1] to fix this issue. It's very minimalistic change (9 lines addition). Hope this will help till it's officially accepted/implemented by the maintainer.. :)

https://gist.github.com/PioneerAxon/8b27cc8f24086a662c65

**Comment by Ofekalef** [comment]
Hi! I'm new here and don't know how to work... How do I make it work?
Plus, I understand that it works on Android. How can I achieve this on iPhone (for friends).

**Comment by PioneerAxon** [comment]
@Ofekalef , this patch is strictly for Android client, and sorry; I'm not familiar (or have talent + motivation + time) to implement it on iOS/WindowsMobile/Web/Desktop versions.
To get this patch working with Android client, follow these steps (assuming you are a little familiar with android development process..
1. Clone this repository, switch to dev branch.
2. Download the patch and apply on the repository.
3. Set your own API IDs in BuildVars.java file (more details are in comments in BuildVars.java).
4. Setup gradle.
5. Build the "release" version of the application.
6. Install the .apk in your phone, and you're good to go.. :)

**Comment by PioneerAxon** [comment]
I'm working on implementing the smart notifications, and with a little bit of hackery I've reached the following stage (see images). Hopefully this will be interesting to all the users of Telegram on Android. :)

![screenshot_2015-01-13-02-39-18](https://cloud.githubusercontent.com/assets/985083/5781128/1007cb54-9dd6-11e4-9cbc-9fc3bbd1cb27.png)
![screenshot_2015-01-13-02-41-03](https://cloud.githubusercontent.com/assets/985083/5781127/1007415c-9dd6-11e4-99a7-31b8f1753b07.png)

**Comment by Darkwood77** [comment]
Hi PioneerAxon, this looks absolutely gorgeous. The thing is, I'd really like for this to be in the official Telegram version for android, I'm not that confident about modifying my own installation.

Is there anyone we could contact about this, especially now after you've done such great work for it? Or is DrKLO monitoring these threads and deciding what to pick and choose for the upcoming builds?

**Comment by Ofekalef** [comment]
@PioneerAxon Thanks! Unfortunatly, I'm not familiar with the developing proccess. However, I don't need this feature right now simply because It doesn't annoy me, and if it does, I turn off the sound but still see the LED light.
Unfortumatly, not all of my friends are like that, and they simply disable notifications for that chat, and never get into Telegram unless I send them a privte message. In iPhone it is even more hard, because they cannot customize vibration, so it sends them a vibration for every message. Then they get back to talk in Whatsapp :-1: This is why I would like this feature to be an official Telegram feature, so +1 to @Darkwood77 's question.

**Comment by PioneerAxon** [comment]
@Darkwood77, Thank you.. :)
Even I was expecting this to be part of the official app. But I couldn't wait for it to be implemented, as I desperately needed it for personal and my group use.

Regarding tinkering with source code; well, it'll be surprising to most that this is my first android application that I was able to even compile, and my first ever Java code. ;)

I'm hopeful that @DrKLO will be monitoring this discussion and probably implementing/accepting this feature soon. But the complete lack of response tells us otherwise. I don't really want to create my own fork of Telegram android app. Maybe we can approach him on Telegram itself??

**Comment by PioneerAxon** [comment]
@Ofekalef, as I said earlier, even I wasn't familiar with android development before I modified this code.
I'm facing the same issue with group chats in Telegram, as others have disabled notifications for group chat and went back to WhatsApp. :/

Again, I'm sorry to tell you that I not familiar (or have talent + motivation + time) to implement it on iOS/WindowsMobile/Web/Desktop versions. That's something that either the community or Telegram project to take on! :(

**Comment by PioneerAxon** [comment]
Here's the patch I've created for the smart notification : https://gist.github.com/PioneerAxon/6f78261a566031759328#file-smart-notifications

Hopefully this will be accepted/reviewed by @DrKLO.. :)

**Comment by Darkwood77** [comment]
I am also hopeful that @DrKLO might at least let us know his thoughts - the only reason why I signed up to github was as this was the only place I've found where Telegram users can leave some sort of feedback - Telegram's website does not have any community board/forum or "suggestions" email address, and Telegram contact on twitter replies to anyone but me :-) Then again, I can't blame @DrKLO for not replying dilligently to every thread, just the sheer number of users' ideas is huge, and probably every single guy thinks that his idea is awesome, and should be implemented with top priority before anything else. Does anyone else know any other means to get in touch with Telegram development team - not necessarilly for Android client only?

Recently I got two friends to switch to Telegram from Whatsapp, having this feature, and "Notification sound in open chats" would really make it absolutely perfect for us. And both ideas seem (well - to me, I could be wrong!) really easy to implement, this one much thanks owed to your great work, @PioneerAxon!

**Comment by Ofekalef** [comment]
@Darkwood77 I'm having the same problem with Telegram on twitter, they answer everyone but me :) And didn't find any other way to contact Telegram. On the "ask a question" chat, they answer selectively and in delay.
@PioneerAxon Thanks, I don't have much time right now, but I guess that it's not that hard to apply it, I only need some development tools on my computer. I'm right?

**Comment by PioneerAxon** [comment]
@Darkwood77, I have the same problem with twitter! They respond to everyone but me :/ .
I don't know any other way of getting in touch (except for maybe pinging the developer(s) on Telegram, which might be a bad idea IMO).
For the friends what you can do is to apply this patch, compile your own APK, and send them your own version of APK. At least that's what I did in my group.. :)

@Ofekalef, applying the patch and compiling will be very easy. You'll just need "git" and "Android-studio" installed. Follow the steps I sent earlier.

If there are enough people with android development skills interested in this, we can fork this code, and release our own "Unofficial Telegram++" client for android, with most of the features requested by people on this repository. I'm actually starting to dislike the attitude of the developer not to open up to the community :-1: .

**Comment by Ofekalef** [comment]
But they have iPhone ( :-1: ). Is there a community of iPhone devs? 
I don't like all the plus versions of Telegram, because whenever there is an update to Telegram, they stay behind unless you keep updating your own app... But if there isn't another way to make changes to the app, then :+1: .

**Comment by akamustang** [comment]
This is really needed, hope it gets implemented in the official release.

**Comment by PioneerAxon** [comment]
@akamustang, I'm sorry, but I don't want to maintain my own version at this point, and the developer @DrKLO seems to be not interested in doing this at all. :disappointed: 

Now that we have another fork (https://github.com/rafalense/Telegram) of this app, I'll try to get it merged there..

Let's hope for the best.. :smile:

**Comment by akamustang** [comment]
Fair enough, great idea to see if rafalense will merge it into their fork.

The Telegram guys posted on Twitter that smart notification as a feature request is something they hope to look at, I guess it's not very high on the priority list though: https://twitter.com/telegram/status/546275281963859968

**Comment by PioneerAxon** [comment]
The patch is merged into Telegram+ (https://github.com/rafalense/Telegram).
Hopefully when the Play store issue is fixed, the app will be available from there.. :)

In the meantime you can head over to the G+ community for the apk etc..
@Darkwood77 @Ofekalef  @akamustang  @DrKLO

**Comment by DrKLO** [comment]
In https://github.com/DrKLO/Telegram/commit/2b8304ebf47b8e16b56fd2c1cfeb8fa3918ac1cb. Thanks.

**Comment by unmultimedio** [comment]
Guys I just found out this thread, it's awesome, I love telegram and I'd love more to colaborate on this!. Im replacing my official telegram app for this one.

Have any of you worked in notifications when chatting from a different device? Such as PC or other mobile?
