### ISSUE TITLE
Bug - photo viewer

### ISSUE THREAD

**Issue by auchri** [DrKLO/Telegram#739]
When I view a photo and I tab on the photo, the action bars are not disappearing.

I think they should fade out if I tab the photo and they should fade in, when I tab the photo again.

**Comment by DrKLO** [comment]
For me it's working. It shouldn't work in photo viewer in photo picker.

**Comment by auchri** [comment]
It doesn't work for me if I view a photo that somebody sent to me

**Comment by auchri** [comment]
fixed with 2.4.0 or 2.4.1
