### ISSUE TITLE
[Bug] Emoticon selector not disappearing in photo viewer

### ISSUE THREAD

**Issue by Minty123** [DrKLO/Telegram#740]
Hey there! I think I found a bug, maybe you can confirm it.

How to reproduce:
1) Open a chat with images in it
2) Tap the emoticon icon to bring up the emoticon selection
3) Tap on an image in the chat to enter the photo viewer

What it did:
The emotion selection does not disappear but overlays the opened image instead.

What did I expect:
The emoticon selection should close when I open an image in a chat. The keyboard does that correctly.

I'm using latest official Play Store version of Telegram.

**Comment by DrKLO** [comment]
It's workaround for another bug of android 5.0. I didn't find how to fix it in other way yet.
![811116641_35350_4039723545549771119](https://cloud.githubusercontent.com/assets/69369/5605847/c1dbae5c-9423-11e4-9e5e-b95665228071.png)

**Comment by DrKLO** [comment]
I think it should be fixed in 2.8.0.
