### ISSUE TITLE
Failed to sync Gradle project 'Telegram-master'

### ISSUE THREAD

**Issue by developermakj** [DrKLO/Telegram#741]
![i1 cimgpsh_orig](https://cloud.githubusercontent.com/assets/10384191/5604026/44b43cbc-938a-11e4-954c-b316ae55fec1.png)
Error:The project is using an unsupported version of the Android Gradle plug-in (0.14.0). The recommended version is 1.0.0.
<a href="fixGradleElements">Fix plugin version and re-import project</a>

Help me please??

**Comment by DrKLO** [comment]
Use dev branch.

**Comment by developermakj** [comment]
I did not understand, explain to me how to do this?
