### ISSUE TITLE
New Feature request : Simple forms

### ISSUE THREAD

**Issue by kpkrish** [DrKLO/Telegram#742]
Could we have a feature where we send a simple form to a telegram user, where the recipient would complete the form & submit it back.

This is how I see the whole process working.
I have my application working on my private server (managing appointments application)
At the appointed time I sent out a telegram message to the recipient (telegram user) with a form, the  recipient  will complete the form & click submit. Upon submit the phone will HTTP post to my url the completed form data.
or alternatively the form can go back to the telegram server and it can deliver the completed form to the sending user.

Other applications for this would be, I send out a form to my group asking everyone for date of birth or venue for meeting, so that as the moderator or group admin I can wish my group members on their birthdays. helps keep the group alive.

I don't know if the telegram client is built using OSGI, If yes then I could build a plugin and extend telegram myself.
Feel free to reach out to me for further questions relating to this requirement I will be happy to put together a business case / use case for you.

**Comment by stefan-niedermann** [comment]
nice idea, but this is such a kind of extremely special use-cases.... telegram is for instant messaging. i auggest you write your form in html an just send a link to it via telegram.

**Comment by Alirezaaa** [comment]
This is a nice idea but It is a kind of extremely special use cases as @stefan-niedermann said already. I think the suggested way is the best way for You.

**Comment by DrKLO** [comment]
It will never be implemented by me in official client. And it doesn't using OSGi.
