### ISSUE TITLE
Feature request: Improved multi-device notifications for secure chats

### ISSUE THREAD

**Issue by danielberlin** [DrKLO/Telegram#744]
It would be great to be *notified* especially about unread secure messages that are sent to other telegram-enabled devices on *all* devices.

E.g. if you have a secret chat on your desktop, it would be very useful to get notified about unread messages for those secret chat on other apps (especially on the smart phone) as well. Might be that the desktop app is closed or receiver is out of office. The encrypted messages cannot be shown on other devices, of course. But at least notified on all devices that there is such a message for a particular device.

See also https://github.com/overtake/telegram/issues/42

**Comment by DrKLO** [comment]
Not client related.
