### ISSUE TITLE
Alert mention in the group

### ISSUE THREAD

**Issue by St-dimka** [DrKLO/Telegram#745]
I am member of group chat. They write a lot of posts, so I disabled the notification of new messages. Sometimes in their conversation, they mention me, but I do not know about this and do not participate in an important conversation for me. In the past, in such popular systems of communication, such as IRC and Jabber notifications used by nick. As mentioned in a conversation participant nickname, his client notify him about it. Telegram recently introduced nicknames. It would be convenient to make a notification via their.
Oh yeah! Ideal if the message containing the references to be different from other messages. And the line "Reply" after clicking on a message to simplify writing nickname :-)

**Comment by Ofekalef** [comment]
+1

**Comment by FoxSays** [comment]
I have a similar situation. 

However, as people don't always know me by my username or if you have international friends, they might know you as a differernt name... I think it would be good if one could keep a list of keywords in the settings. If any of these keywords were mentioned in any chat, user would be notified regardless of notification setting of individual chatroom.

**Comment by nplezka** [comment]
+1

**Comment by Lana-chan** [comment]
I would also like this exact feature, with keywords function as described by FoxSays. Skype also already has this feature.

**Comment by z3t1** [comment]
+1. Use @ + Username/nick as a symbol for mention.

**Comment by Tishka17** [comment]
1. Mentions in group chat should have different from simple chat notifications. E.g I want to receive mention notifications even when chat notifications are disabled. 
2. Messages with mentions should be visually marked: color, text decoration or anything else.
3. Quotes are also a type of mentions. 
4. A good way to place a mention in message is "reply" button on other message. 
5. A possibility to select a name from list would be useful. 
6. There should be some way to type a name by keyboard
7. Custom keywords for mention detection is a good expansion of this feature

**Comment by aristidesfl** [comment]
+1

**Comment by jdkcn** [comment]
+1 This is useful.

**Comment by DrKLO** [comment]
In 2.6.0.

**Comment by aristidesfl** [comment]
In which version for mac?

**Comment by St-dimka** [comment]
Thank U!

**Comment by mirhl** [comment]
@aristidesfl 
This is not the place for mac version.
