### ISSUE TITLE
Problem after Rotate

### ISSUE THREAD

**Issue by St-dimka** [DrKLO/Telegram#747]
Occasionally, after the Auto Rotate is a problem, as shown in the screenshot
![screenshot_2015-01-07-21-25-55](https://cloud.githubusercontent.com/assets/2127601/5650951/436c048e-96b4-11e4-9695-879e653626b9.png)
After pressing the "Back" application is minimized. To fix should stop Telegram
Nexus 7 LTE, Android 4.4.4

**Comment by DrKLO** [comment]
I think it was fixed in 2.5.x.
