### ISSUE TITLE
Feature Request: Allow group admin to switch off the kick/leave message to participants

### ISSUE THREAD

**Issue by wonggwing** [DrKLO/Telegram#748]
As said, it is quite disturbing when someone decide to leave or being kicked by admin from the group. Here are 2 real life example that supports why this feature is useful.

(1) The problem is seen in Whatsapp when someone decides to clear up their contact list and remove a group that has been inactive for months, and everyone is prompted for that leaving message. It is disturbing and people in the group can either discuss about the reasons for why he leaves or remains in awkward silence.
(2) And in case of event organizing / event gatherings, it is quite discouraging if everyone sees kicking and leaving messages frequently. Messages of someone joined the group would be favorable, but not the leaving ones. It is also seen in Facebook groups which someone leaves a group is never displayed nor notified to everyone in the group.

I hope you would consider adding this function. That is allowing admin to toggle the notification of kicking/leaving of someone in a group to all others.

Been using telegram for few months, it's really useful. Thanks a lot.

**Comment by DrKLO** [comment]
Not client related. There is no API for that.

**Comment by developermakj** [comment]
+1
