### ISSUE TITLE
Ubuntu Gnu-Linux Desktop bar

### ISSUE THREAD

**Issue by Dryvenn** [DrKLO/Telegram#751]
Hi there !
First of all, congrats for your work and dedication !

As an user of Ubuntu, I think it'd be nice if your Linux desktop app had an integration in the menu bar and run in background. For instance, as the Dropbox desktop app (see example below).

![example](https://cloud.githubusercontent.com/assets/6233736/5663701/6865ef48-974a-11e4-9415-cba5030b5a52.png)

Hope it's not redundant with another issue.

Carry on ! :+1:

**Comment by DrKLO** [comment]
This is Android project.

**Comment by Dryvenn** [comment]
Yeah sorry, just saw this. I'll move it.

**Comment by robin0van0der0v** [comment]
Desktop project is here: https://github.com/telegramdesktop/tdesktop
