### ISSUE TITLE
Feature request: quote message

### ISSUE THREAD

**Issue by zouden** [DrKLO/Telegram#752]
My friends and I often use the Forward function to repeat an old message back to the same group, in order to then reply to it. This requires selecting the message, tapping the forward button, and selecting the same group again. But there's no easy way to see which group it was coming from and we often hit the wrong group.

A very simple enhancement would be a "quote" button next to the forward button in the action bar. It would simply forward the message to the current group.

**Comment by St-dimka** [comment]
+1

**Comment by Alirezaaa** [comment]
I like this feature.

**Comment by developermakj** [comment]
+1

**Comment by pschichtel** [comment]
I like how Skype does quoting

**Comment by DrKLO** [comment]
Replies were implemented some time ago.

**Comment by zouden** [comment]
Yes, after I suggested it here. Thanks, it's a great feature :)
