### ISSUE TITLE
Messages/pictures not immediately sent with 2G/3G connection

### ISSUE THREAD

**Issue by bcorbisiero** [DrKLO/Telegram#754]
Hello,
When I try to send a message/picture with my mobile Internet connection, the message/image remains many seconds with the small clock (not sent).
It happens also with 3G strong signal.

I have deleted all the app data and cache and logged in again and this seems to solve the problem.

I have a Google Nexus 4 smartphone, running Android 5.0.1.
Restoring the phone to factory defaults and reinstalling Telegram causes the same issue: I needed again to wipe the application data and log in again.

Anyone with the same problem? Is it a known issue?

Thank you!

**Comment by DrKLO** [comment]
What you expecting from slow network? Super fast upload and download speed? You should compain to you carrier.

**Comment by bcorbisiero** [comment]
My carrier provides a fast connection. It is not necessary to have a fast connection ti send a message via Telegram.

**Comment by DrKLO** [comment]
For me it takes no more than 1 second to send image via 3G.

**Comment by bcorbisiero** [comment]
My question was not about the mobile connection speed. I have absolutely no problem with other messengers. My question was about an issue I have encountered: Telegram outgoing messages/images remain blocked for some reason. If I clear all the Android app data and cache, the app begins to work properly also with 3G connection. Why??
