### ISSUE TITLE
Personalize time color

### ISSUE THREAD

**Issue by developermakj** [DrKLO/Telegram#755]
I want to change the color of the hour, someone can tell me where is the code for the time color Moved?
![screenshot_2015-01-08-12-12-43editadaparasite](https://cloud.githubusercontent.com/assets/10384191/5692460/0b5d17ce-98dd-11e4-9856-883a755a7b01.png)

the hour numbers of color is green, I put in black - HELP ME PLEASE?

@DrKLO  Help me Please?

**Comment by developermakj** [comment]
@DrKLO Help me?

**Comment by DrKLO** [comment]
ChatBaseCell class.
private static TextPaint timePaintIn;
private static TextPaint timePaintOut;
