### ISSUE TITLE
[suggestion] Official Repo for iOS

### ISSUE THREAD

**Issue by AdulteTerrible** [DrKLO/Telegram#759]
Hello DrKLO,

could you ask the developers of Telegram's iOS client to create an official public repo? There's none so far, but for people external to the project commiting the source code provided on Telegram's website (version 1.1 I believe). I'd sleep better if I could fork from an official repo, even if it contained only 1.1!

(I know it's not related to your work on the Android client, but I couldn't find a way to reach them directly)

Thanks for your work!

**Comment by DrKLO** [comment]
Hi, no.

**Comment by AdulteTerrible** [comment]
Well... Thanks for taking the time to reply ;)
