### ISSUE TITLE
What .xml to change the color of the MENU?

### ISSUE THREAD

**Issue by developermakj** [DrKLO/Telegram#763]
sorry, but can anyone tell me where could be the code which I can change the menu color? I found all the other places only the menu that I do not think the color
![screenshot_2015-01-13-17-04-30](https://cloud.githubusercontent.com/assets/10384191/5767062/083740a6-9ced-11e4-8dee-502b4a77fecc.png)
![screenshot_2015-01-13-17-13-25](https://cloud.githubusercontent.com/assets/10384191/5767064/08620598-9ced-11e4-8e60-02a757c858da.png)
![screenshot_2015-01-13-17-33-02](https://cloud.githubusercontent.com/assets/10384191/5767065/08663f00-9ced-11e4-8f8a-0c78b3aabc45.png)
![screenshot_2015-01-13-18-19-24](https://cloud.githubusercontent.com/assets/10384191/5767063/0851aa36-9ced-11e4-8173-4c54a56680c8.png)
![screenshot_2015-01-14-15-36-03](https://cloud.githubusercontent.com/assets/10384191/5767066/086aa784-9ced-11e4-8d20-42bd2ceb6d31.png)

**Comment by DrKLO** [comment]
Everything in code. See DrawerProfileCell.
