### ISSUE TITLE
Feature suggestion: Message types + filter on these types

### ISSUE THREAD

**Issue by bartdeboer** [DrKLO/Telegram#766]
It's my experience that often important messages get lost in the bulk of chat conversations. A solution could be to implement message types and the option to filter on these types. 

Message types are already partially implemented. Telegram has "special" messages like images, stickers, documents, locations. I would suggest to expand on these types. Specifically calendar dates would be really useful. It's probably the biggest use case scenario of Telegram for people to plan a date. These special messages could be added through the "attachment" button in the chat client. 

Other (interactive) types might be polls (group decisions), checklists (to-do's) or starred messages. Although the interactive nature of such messages might be more difficult to implement. 

Most importantly, it would be great if we could filter on message types. Include a filter icon in the top-right of the chat with: images, links, dates, documents, locations, starred messages. 

I believe these additions could enable Telegram to become a much stronger social productivity / collaboration tool (positioning itself somewhere between Whatsapp and Facebook). 

It would perhaps also eliminate/reduce the need for search (a feature which has a much bigger impact on the back-end load).

**Comment by Alirezaaa** [comment]
+1

**Comment by DrKLO** [comment]
API support needed,
@Alirezaaa for now i will close every issue with "+1" in it. I'm tired of it and of spam to my email, so I already disabled email notifications. I'm near to disable project issues page at all.

**Comment by Alirezaaa** [comment]
@DrKLO I'm sorry. I really didn't know and you are right; Getting notifications from just '+1' comments is annoying. Please forgive me. I don't do that again. Thanks for letting me know and thanks for your time.
