### ISSUE TITLE
Error open project in Android Studio 1.0

### ISSUE THREAD

**Issue by anttorval** [DrKLO/Telegram#767]
When I open an existing Android Studio project (Telegram-master)
![sin titulo](https://cloud.githubusercontent.com/assets/9047991/5804436/254b1e76-a006-11e4-807b-8465770b58ba.jpg)

 show : 
![sin titulo2](https://cloud.githubusercontent.com/assets/9047991/5804450/503b64e2-a006-11e4-8740-f566e6647a99.jpg)

**Comment by DrKLO** [comment]
Use dev branch.

**Comment by anttorval** [comment]
show same error! :(

**Comment by DrKLO** [comment]
You should "Open" project, not import.

**Comment by anttorval** [comment]
I do file>open>  project:
![sin titulo3](https://cloud.githubusercontent.com/assets/9047991/5805264/abae6de0-a00d-11e4-90a4-e88c9cb4983e.jpg)
