### ISSUE TITLE
[Feature Request] Stop sending notifications to phone when talking on desktop/other device

### ISSUE THREAD

**Issue by momotombo** [DrKLO/Telegram#768]
This feature is sorely missed when switching from another messenger. There's usually a 5 or so minute timeout when talking on another device, and then messages start arriving to the phone again. It's annoying when I'm sitting at my desk and my phone is buzzing over and over again when I've been talking on my PC the whole time. Some messengers seem to detect when the computer itself is idle to start sending messages to the phone again, which is much nicer than a simple timeout.

**Comment by DrKLO** [comment]
duplicate
