### ISSUE TITLE
Feature Request : Only accept from contacts / Ignore users who are blocked

### ISSUE THREAD

**Issue by FoxSays** [DrKLO/Telegram#769]
I am a Telegram user in Korea, and Telegram has grown popular enough here that spammers have graced us with their presence. 

So I have two feature requests:

1. To be able to ignore all messages and group invites from people not already on my list of contacts. I feel that this would become a near necessity when spam problem gets worse. It would be nice to have this option to completely free myself from potential spammers.

2. I have noticed that even if I have blocked someone (A), if a third party (B) invites both myself and A in a group chat, then I will be able to see everything A posts. If there a way to make it so that in a similar situation, I can choose to make the person I have blocked invisible?

Thanks

**Comment by DrKLO** [comment]
It's server side.

**Comment by FoxSays** [comment]
@DrKLO But my list of contacts is also uploaded on the server. So the fact that it's server side shouldn't affect this feature from being implemented.
