### ISSUE TITLE
When I create a new Telegram app, But it synchronized with existing telegram application

### ISSUE THREAD

**Issue by riyask** [DrKLO/Telegram#770]
I created a telegram client application with a new packageId using open source telegram code  in android and telegram API.But the problem is that when new messages arrived on my own application it also receives on telegram.The chat history is also showing from that of telegram. Is there any way to prevent this and keeping my own app as a brand new one?

**Comment by DrKLO** [comment]
Only if you will write your own server and API.

**Comment by riyask** [comment]
We have a community app in android and IOS, For our msging service for the community members can we use telegram as a official partner?. Practically we will have an entry point to telegram application from our app. Which will help in more downloads for Telegram and a reliable msging service for us which is a win win situation for both
