### ISSUE TITLE
Telegram shows I'm online when I'm not

### ISSUE THREAD

**Issue by Ofekalef** [DrKLO/Telegram#772]
I have Telegram on Moto G. When I close the app as in here:
![image](https://cloud.githubusercontent.com/assets/10423582/5871068/7336dee0-a2e0-11e4-8a51-61647e1a820a.png)
(from http://blog.laptopmag.com/9-awesome-android-ice-cream-sandwich-tips)
the app will show I'm online even after that, for some time (not a small time).
If a first press the home screen button (the middle one) then it will show I'm offline immediatly.

**Comment by DrKLO** [comment]
App setting offline status when Android calls Activity.onPause(). There is nothing wrong with my code.
