### ISSUE TITLE
Feature reques: notifications

### ISSUE THREAD

**Issue by MatteoColombo** [DrKLO/Telegram#773]
Hello 
I'd have a requested about notifications: If I receive multiple messages in the same conversation the phone rings (and vibrates) for each message. If I get 10 messages it rings 10 times and sometimes it's really annoying. 
It would be nice to introduce a range of time in which the notification is updated but the phone doesn't ring or vibrate. (in the same way whatsapp works).
Thank you

**Comment by caborracho** [comment]
+1

**Comment by DrKLO** [comment]
Duplicate
