### ISSUE TITLE
Telegram 2.3.3(416) Google play version having bug to download file as document.

### ISSUE THREAD

**Issue by AUDI-A4** [DrKLO/Telegram#778]
If someone send me mp3 or gif file as document.File starts getting download.Download does not complete and it changes to retry mode.It happens even i download document as 5 times.Please fix this issue.I am using kitkat 4.4.4.It happens when someone sends you multiple documents.

**Comment by DrKLO** [comment]
I can't understand what you mean. There is no "retry" mode for downloads. You should check your disc space or send logs from debug version to me.

**Comment by AUDI-A4** [comment]
According to scenario,If some one sends me multiple documents,

According to screen 1.I will receive the document like this  

![screenshot_2015-01-26-21-09-12](https://cloud.githubusercontent.com/assets/7442148/5902709/be7176ee-a5a2-11e4-92cd-d2bfdc745434.png)


After downloading it should be like screen 2

![screenshot_2015-01-26-21-25-36](https://cloud.githubusercontent.com/assets/7442148/5902734/f6f2200e-a5a2-11e4-896c-20a286db85c7.png)

But it is again getting into initial stage after completing the download as show in screen 1

**Comment by DrKLO** [comment]
You should check your disc space, or check write permissions to cache folder and /external storage/Telegram/ folder, or install debug version (https://rink.hockeyapp.net/apps/a5b5c4f551dadedc9918d9766a22ca7c/app_versions/458) and send logs to me, so i will be able to say what exactly is wrong.

**Comment by AUDI-A4** [comment]
Seems to me working.
