### ISSUE TITLE
Crop/Upload  image from Loginregister view

### ISSUE THREAD

**Issue by nOmi7** [DrKLO/Telegram#779]
I added backimage on login registerview however not able to download existing image or crop  and upload a new one 

avatarupdater.parenfragment is always null 

This is what i did 

LoginActivity
1) @Override
    public void onActivityResultFragment(int requestCode, int resultCode, Intent data) {
             if (views[currentViewNum] instanceof LoginActivityRegisterView) {
     ((LoginActivityRegisterView)views[currentViewNum]).avatarUpdater.onActivityResult(requestCode, resultCode, data);  ------ avatarupdater.parentfragment  is null when going from here for startCrop
        }
    }

2) At loginRegistervView i add 
public AvatarUpdater avatarUpdater = new AvatarUpdater();

 avatarUpdater.parentFragment = (LoginActivity)delegate;
 builder.setItems(items,.....) --- for the alert menu
if (user != null && user.photo != null && user.photo.photo_big != null) {
                                PhotoViewer.getInstance().setParentActivity((Activity)delegate);
                                //PhotoViewer.getInstance().openPhoto(user.photo.photo_big, ??????));
                            }  ----- WHAT to pass here and get this open photo working ?
 } else if (i == 0 && !full || i == 1 && full) {
                            avatarUpdater.openCamera();     --- FAILS AT STARTCROP bcz of null parentfragment @ avtarupdater
                        } else if (i == 1 && !full || i == 2 && full) {
                            avatarUpdater.openGallery();        --- FAILS AT STARTCROP bcz of null parentfragment @ avtarupdater

Thanks
Jeet

**Comment by DrKLO** [comment]
You using it wrong, check SettingsActivity.
I'm not recommending you to add photo selector to register view, because gallery can kill app on some devices if there is not enough and login interface state can be lost.
