### ISSUE TITLE
[android] An option to crop an image uploaded in groups/conversations, prior to be uploaded. 

### ISSUE THREAD

**Issue by themegabyte** [DrKLO/Telegram#780]
Hi, drKLO and the team
This is a very needed option that should have been present before. 
Just like in whatsapp, when we upload an image it gives an option to crop the image to be sent. It also saves time, because either we have to send  the image (screenshot for instance) as is or crop using Gallery.
  Since a lot of my friends have moved to Telegram, we would like to have this option. Thanks.

**Comment by caborracho** [comment]
+1
I'm with you. That would be a grat feature :)

**Comment by nplezka** [comment]
+1

**Comment by themegabyte** [comment]
thanks for your support @neplezka

**Comment by themegabyte** [comment]
EDIT: Hi, drKLO and the team.

**Comment by Paramfullestop123** [comment]
Hi friends @themegabyte pls tell me how setup telegram in your IDE.
I am import this project on Eclipse IDE and change BuildVars.java with App_ID and App_Hash but i got null pointer exception.

**Comment by themegabyte** [comment]
Resolved in version 2.5.0 (433). thanks @DrKLO and the team
