### ISSUE TITLE
Add option to cancel a sending message

### ISSUE THREAD

**Issue by caborracho** [DrKLO/Telegram#781]
Please add the option to cancel a message if it was not sent yet

**Comment by devianpctek** [comment]
Or better, have an option for delivery delay just like Google's messaging app

**Comment by caborracho** [comment]
Well. One can not replace the other. But I think that delay will also be nice :)

**Comment by DrKLO** [comment]
No, you can't be sure was request sent to server or not. Network doesn't work as you want.
Also trying to cancel messages in secret chats can break it because of seq_in and seq_out checks. One missing message will discard all other.

**Comment by caborracho** [comment]
mmm maybe I didn't explained well. I meant like manually. For instance, if I try to send a message and I don't have a good connection, the app would try to reach your servers. So I was thinking on like simply stop trying. 
I think you can actully know if the message was sent to the server, because when the message is sent I got a check mark indicating me that. You can possibly use that
