### ISSUE TITLE
feature request: pinned messages in groups

### ISSUE THREAD

**Issue by bgta** [DrKLO/Telegram#783]
This request is inspired on Hike feature: Group Pins, pin important messages so no one misses it. Look the image:

![unnamed](https://cloud.githubusercontent.com/assets/566032/5956596/aef94d7c-a7af-11e4-85bd-a7bbf93beed2.png)

**Comment by fidojones** [comment]
+1 to this feature

**Comment by DrKLO** [comment]
Not client related.

**Comment by bgta** [comment]
I expected that answer ... is there any way to climb the proposal to the part of the Server? Thanks for your time.

**Comment by DrKLO** [comment]
Telegram support or Twitter.
https://telegram.org/faq
