### ISSUE TITLE
Missing share button

### ISSUE THREAD

**Issue by TheNetStriker** [DrKLO/Telegram#784]
Is there a reasony why Telegram does not have a share button for third party apps to send chats, videos and pictures? (WhatsApp has this feature) If there is no reason why Telegram should not have this feature I'am willing to submit a patch to add this feature. (I've already taken a look at the code and I should be able to implement this feature)

**Comment by themegabyte** [comment]
+1

**Comment by DrKLO** [comment]
Telegram has this button in photo viewer. Button for documents will be added in next version.

**Comment by TheNetStriker** [comment]
Thanks for the hint. I've just tested this. For images this is works very good, but if I want to share a video I have to find an image to open the gallery and then scroll back to the video to get to the share button. Any ideas on how to make this easier? Maybe a fourth option on the contextmenu to open the gallery?
