### ISSUE TITLE
Shared images from WhatsApp not working

### ISSUE THREAD

**Issue by TheNetStriker** [DrKLO/Telegram#787]
Since a few versions I cannot share images from WhatsApp to Telegram. Instead of the picture only the "sent from WhatsApp" text is sent. I've attached the debugger to Telegram to see which intent is sent from WhatsApp and it seams to send an intent with type "message/rfc822" which is not handled properly by Telegram. I've tested this also with my own app and there I receive an "image/*" intent from WhatsApp, but with the specific intent filter combination of Telegram I also receive this rfc822 intent. Here is a screenshot of the intent sent to Telegram:

![telegram](https://cloud.githubusercontent.com/assets/2478144/5979569/15d41f8c-a8a9-11e4-9b7c-a0518794a838.PNG)

Could this please be fixed? I am also willing to help fix the problem.

**Comment by ziki77** [comment]
You can share image to telegram from whatsapp opening the image on whatsapp and share it from this "image full view", it works.
Sure, this is only a workaround.

**Comment by fduraibi** [comment]
This is actually a bug in Whatsapp since it shares the photos with the wrong mime type. However, if you do as @ziki77 and share it from the image viewer it get shared as "image/jpeg".

previously Telegram will get it as a document (file), but since whatsapp added the text "sent from WhatsApp" Telegram now picks up the text only.

**Comment by ziki77** [comment]
Moreover in whatsapp you cannot share more than one multimedia file at time, if you select more than one in the chat history, share button disappears. So there is no advantage to share from chat history than open the media and share it.
