### ISSUE TITLE
cannot serialize

### ISSUE THREAD

**Issue by nOmi7** [DrKLO/Telegram#789]
TLRPC.User asd = new TLRPC.User();
        asd.phone="221213123";
        asd.last_name="pasdbaar";
        asd.first_name="jesser";
        asd.id=12312322;
        asd.username="jeddt_rsdmar";
        ByteBufferDesc dataa = buffersStorage.getFreeBuffer(asd.getObjectSize());
        asd.serializeToStream(dataa);

why my dataa is null ???
what needs to be done to serialize user object ?

**Comment by DrKLO** [comment]
TLRPC.User is base class and can't be serialized. You should use TL_user, TL_userEmpty, etc.

**Comment by nOmi7** [comment]
So how does put user internal on message storage work ?

for (GObjs.User user : users) {
            state.requery();
            ByteBufferDesc data = buffersStorage.getFreeBuffer(user.getObjectSize());
            user.serializeToStream(data);
its direcly using the serializeToStream(data); on base class

**Comment by nOmi7** [comment]
Also i am trying to do some data binding and storage on my server for which i am using PHP ...
I see the TL_SChema avaliable in JSON can i deserlise response sent by PHP in JSON to a TL java object  ?

any pointers and examples will help a lot ..
thanks
