### ISSUE TITLE
Reverse order of messages in notifications

### ISSUE THREAD

**Issue by obskyr** [DrKLO/Telegram#790]
With the notifications as they are now, they go bottom-to-top, as shown here:

![yo!](https://cloud.githubusercontent.com/assets/4363779/5993266/d86c945a-aa4a-11e4-9237-398dfa9e8b26.png)

Note how the first message gets put on the bottom, and the later ones get put on top. This should be changed for the other way around, for two very simple reasons:

* It's confusing with the messages appearing in this order - you naturally read bottom-to-top, not top-to-bottom.
* In-app, Telegram renders new messages under ones previous. This makes for a confusing design inconsistency.

A change should be made to show new messages under the ones before, even in the notifications.

**Comment by DrKLO** [comment]
Duplicate https://github.com/DrKLO/Telegram/issues/497.
