### ISSUE TITLE
No scrollbar

### ISSUE THREAD

**Issue by auchri** [DrKLO/Telegram#792]
In the latest release (4.3.0) there is no scrollbar in the new shared files list. In the shared media section, there is a scrollbar

Android 4.4.4

**Comment by DrKLO** [comment]
Yes, I know. And what you want?

**Comment by auchri** [comment]
A scrollbar in booth sections or no scrollbar in booth sections. I prefer a scrollbar in booth sections.

**Comment by auchri** [comment]
added in 4.3.1, thank you :)
