### ISSUE TITLE
java.lang.NullPointerException : ConnectionsManager.java #487

### ISSUE THREAD

**Issue by PriyankaKamthe** [DrKLO/Telegram#794]
hey guys,

I try to implement telegram chat application but it gets crashed at launching time. & log cat shows following error message ;

02-02 14:59:43.255: E/AndroidRuntime(2027): FATAL EXCEPTION: stageQueue
02-02 14:59:43.255: E/AndroidRuntime(2027): java.lang.NullPointerException
02-02 14:59:43.255: E/AndroidRuntime(2027): 	at org.telegram.messenger.ConnectionsManager.processMessage(ConnectionsManager.java:2119)
02-02 14:59:43.255: E/AndroidRuntime(2027): 	at org.telegram.messenger.ConnectionsManager.tcpConnectionReceivedData(ConnectionsManager.java:2582)
02-02 14:59:43.255: E/AndroidRuntime(2027): 	at org.telegram.messenger.TcpConnection$9.run(TcpConnection.java:523)
02-02 14:59:43.255: E/AndroidRuntime(2027): 	at android.os.Handler.handleCallback(Handler.java:725)
02-02 14:59:43.255: E/AndroidRuntime(2027): 	at android.os.Handler.dispatchMessage(Handler.java:92)
02-02 14:59:43.255: E/AndroidRuntime(2027): 	at android.os.Looper.loop(Looper.java:137)
02-02 14:59:43.255: E/AndroidRuntime(2027): 	at org.telegram.messenger.DispatchQueue.run(DispatchQueue.java:100)

kindly help me to resolve this "NullPointer Exception".....

**Comment by DrKLO** [comment]
You changed code somehow, i don't see anything wrong in this line in my code. You should update your source code or provide code block around this line.

**Comment by PriyankaKamthe** [comment]
This is the code where error is occur;

else if (!(resultContainer.result instanceof TLRPC.TL_error)) {
                            		if (request.rawRequest == null || !request.rawRequest.responseClass().isAssignableFrom(resultContainer.result.getClass())) {
                                        if (request.rawRequest == null) {
                                            FileLog.e("tmessages", "rawRequest is null");
                                        } else {
                                            FileLog.e("tmessages", "***** RPC error: invalid response class " + resultContainer.result + " (" + request.rawRequest.responseClass() + " expected)");
                                        }
                                        implicitError = new TLRPC.TL_error();
                                        implicitError.code = -1000;
                                        implicitError.text = "";
                                    }


while debugging i come to know that the value of "resultContainer.result" is null...... but i don't get reason behind that.

**Comment by DrKLO** [comment]
I need to know which request you sent to server, because this request doesn't have response class in TLRPC.

**Comment by Paramfullestop123** [comment]
hey guys,

I try to implement telegram chat application but it gets crashed at launching time. & log cat shows following error message ;

02-02 14:59:43.255: E/AndroidRuntime(2027): FATAL EXCEPTION: stageQueue
02-02 14:59:43.255: E/AndroidRuntime(2027): java.lang.NullPointerException
02-02 14:59:43.255: E/AndroidRuntime(2027): at org.telegram.messenger.ConnectionsManager.processMessage(ConnectionsManager.java:2119)
02-02 14:59:43.255: E/AndroidRuntime(2027): at org.telegram.messenger.ConnectionsManager.tcpConnectionReceivedData(ConnectionsManager.java:2582)
02-02 14:59:43.255: E/AndroidRuntime(2027): at org.telegram.messenger.TcpConnection$9.run(TcpConnection.java:523)
02-02 14:59:43.255: E/AndroidRuntime(2027): at android.os.Handler.handleCallback(Handler.java:725)
02-02 14:59:43.255: E/AndroidRuntime(2027): at android.os.Handler.dispatchMessage(Handler.java:92)
02-02 14:59:43.255: E/AndroidRuntime(2027): at android.os.Looper.loop(Looper.java:137)
02-02 14:59:43.255: E/AndroidRuntime(2027): at org.telegram.messenger.DispatchQueue.run(DispatchQueue.java:100)

kindly help me to resolve this "NullPointer Exception".....

**Comment by Paramfullestop123** [comment]
How to check sever  request what about sent..?

**Comment by Paramfullestop123** [comment]
I am changed in BuildVars file with APP_ID  and APP_HASH.
kindly help me other file change if any require made.

**Comment by Paramfullestop123** [comment]
Is need to change Datacenter value with Test configuration: DC2 value or Production configuration: DC2(It's generate on telegram server with app_id and app_hash).
kindly help me as soon as posible



 private void fillDatacenters() {
        if (datacenters.size() == 0) {
            if (isTestBackend == 0) {
            	
            	 Log.v("ConnectionsManager", "if === 0 fillDatacenters");
            	 
                Datacenter datacenter = new Datacenter();
                datacenter.datacenterId = 1;
                datacenter.addAddressAndPort("149.154.175.50", 443);
                datacenters.put(datacenter.datacenterId, datacenter);

                datacenter = new Datacenter();
                datacenter.datacenterId = 2;
                datacenter.addAddressAndPort("149.154.167.51", 443);
                datacenters.put(datacenter.datacenterId, datacenter);

                datacenter = new Datacenter();
                datacenter.datacenterId = 3;
                datacenter.addAddressAndPort("174.140.142.6", 443);
                datacenters.put(datacenter.datacenterId, datacenter);

                datacenter = new Datacenter();
                datacenter.datacenterId = 4;
                datacenter.addAddressAndPort("149.154.167.91", 443);
                datacenters.put(datacenter.datacenterId, datacenter);

                datacenter = new Datacenter();
                datacenter.datacenterId = 5;
                datacenter.addAddressAndPort("149.154.171.5", 443);
                datacenters.put(datacenter.datacenterId, datacenter);
            } else {
            	Log.v("ConnectionsManager", "fillDatacenters esle part");
                Datacenter datacenter = new Datacenter();
                datacenter.datacenterId = 1;
                datacenter.addAddressAndPort("173.240.5.253", 443);
                datacenters.put(datacenter.datacenterId, datacenter);

                datacenter = new Datacenter();
                datacenter.datacenterId = 2;
                datacenter.addAddressAndPort("149.154.167.40", 443);
                datacenters.put(datacenter.datacenterId, datacenter);

                datacenter = new Datacenter();
                datacenter.datacenterId = 3;
                datacenter.addAddressAndPort("174.140.142.5", 443);
                datacenters.put(datacenter.datacenterId, datacenter);
            }
        } else if (datacenters.size() == 1) {
        	Log.v("ConnectionsManager", "fillDatacenters if esle part");
            Datacenter datacenter = new Datacenter();
            datacenter.datacenterId = 2;
            datacenter.addAddressAndPort("149.154.167.51", 443);
            datacenters.put(datacenter.datacenterId, datacenter);

            datacenter = new Datacenter();
            datacenter.datacenterId = 3;
            datacenter.addAddressAndPort("174.140.142.6", 443);
            datacenters.put(datacenter.datacenterId, datacenter);

            datacenter = new Datacenter();
            datacenter.datacenterId = 4;
            datacenter.addAddressAndPort("149.154.167.91", 443);
            datacenters.put(datacenter.datacenterId, datacenter);

            datacenter = new Datacenter();
            datacenter.datacenterId = 5;
            datacenter.addAddressAndPort("149.154.171.5", 443);
            datacenters.put(datacenter.datacenterId, datacenter);
        }
    }

**Comment by NitzDKoder** [comment]
Having the same problem..Trying to load the app it crashes always.

Also "Available MTProto servers and Public keys:" where to put these configuration/Keys is not mentioned anywhere.

I have filled BuildVars variables as needed,except BING_SEARCH_KEY.

"
03-05 14:03:09.359: E/AndroidRuntime(18324): Process: org.telegram.messenger, PID: 18324
03-05 14:03:09.359: E/AndroidRuntime(18324): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
03-05 14:03:09.359: E/AndroidRuntime(18324): 	at org.telegram.messenger.ConnectionsManager.processMessage(ConnectionsManager.java:2143)
03-05 14:03:09.359: E/AndroidRuntime(18324): 	at org.telegram.messenger.ConnectionsManager.tcpConnectionReceivedData(ConnectionsManager.java:2664)
03-05 14:03:09.359: E/AndroidRuntime(18324): 	at org.telegram.messenger.TcpConnection$9.run(TcpConnection.java:526)
03-05 14:03:09.359: E/AndroidRuntime(18324): 	at android.os.Handler.handleCallback(Handler.java:739)
03-05 14:03:09.359: E/AndroidRuntime(18324): 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-05 14:03:09.359: E/AndroidRuntime(18324): 	at android.os.Looper.loop(Looper.java:135)
03-05 14:03:09.359: E/AndroidRuntime(18324): 	at org.telegram.messenger.DispatchQueue.run(DispatchQueue.java:100)
"

Pls help @DrKLO.

**Comment by abnd** [comment]
I'm getting the same error. **using eclipse**. 
I read @DrKLO wrote: "Use Android Studio, i don't support eclipse."

after long hours i got the project to compile - but getting this error when pressing "start messaging" button.

Is there a way to run Telegram on eclipse without errors? 

(beacause i won't study Android Studio, and will drop this projet..)

thank you.

**Comment by NitzDKoder** [comment]
Was able to integrate in ecplise.See this post.
@abnd https://github.com/DrKLO/Telegram/issues/899
