### ISSUE TITLE
Emoji issue (replacing with others)

### ISSUE THREAD

**Issue by 39bit** [DrKLO/Telegram#796]
This has been a common issue over here AFAIK with several other issues also discussing about the current emoji choices.

The problem is that the current emoji font used (Apple Color Emoji, also used by WhatsApp) etc. is not the favorite of everyone, and even worse, it's actually under Apple's copyright. Under some sources that I could find (like [this](http://words.steveklabnik.com/emoji-licensing), [this](http://stackoverflow.com/questions/10834811/emoji-copyright) and [this](https://github.com/github/gemoji/pull/64)), it's shady (if not illegal) to distribute the emoji font like Telegram does now.

The choices are to use the system's own emoji or open-source free emoji fonts (such as Google's [Noto](https://www.google.com/get/noto/), which is licensed under Apache 2 and should be available as PNG as well).

EDIT: Some additional comments that they look out of place in an application that is designed to be Material Design for Android, so stock emojis on the system would be the best option. Also, using the argument of "[I don't like Android emojis](https://github.com/DrKLO/Telegram/issues/358#issuecomment-45840820)" is not a good argument in my opinion, considering the application has a particularly large user base which may have a great amount of users who don't like iOS emojis.

**Comment by fduraibi** [comment]
Telegram is not using the apple font, instead it is a big png image that get sliced by the app into smaller images and inserted into the text view area like inserting images into an HTML page.

But I don't know if that makes it ok or apple still has a license on the drawings themselves!!! 
(BTW, that is one of the reasons why I hate apple)

**Comment by 39bit** [comment]
They are a rip of the font('s emoji graphics) which are under the same copyright as the font itself.

**Comment by DrKLO** [comment]
Duplicate, already discussed. It will be no replaced with anything else.

**Comment by Multimoon** [comment]
DrKLO, this wasn't discussed. You leveled your unilateral opinion that we are all stupid in asking for the choice.

**Comment by cortices** [comment]
According to http://stackoverflow.com/questions/22337295/license-of-apple-color-emoji-ttf/22949517#22949517 there is no licence available for Apple Color Emoji
