### ISSUE TITLE
Mute icon alignment in RTL view

### ISSUE THREAD

**Issue by fduraibi** [DrKLO/Telegram#797]
The mute icon for groups with arabic names (RTL) when the app layout is also RTL is wrong as you can see in the picture.

![tel-bug](https://cloud.githubusercontent.com/assets/432460/6008167/7a79d6ca-aaed-11e4-96a0-f9d72f3e3f38.png)

**Comment by fduraibi** [comment]
I think it got fixed in the last update 2.5.0.

thanks DrKLO

**Comment by DrKLO** [comment]
Yep, thanks for report.
