### ISSUE TITLE
 Strange Bug: aaptOptions.useAaptPngCruncher = true

### ISSUE THREAD

**Issue by conectapb** [DrKLO/Telegram#804]
how could I do? Any example that explains a little better friend
![telegram](https://cloud.githubusercontent.com/assets/10766665/6024524/97c628ba-abaa-11e4-9a91-376f6a924ab7.png)

**Comment by DrKLO** [comment]
Use this source: https://github.com/DrKLO/Telegram/tree/dev
Your source code is outdated, last gradle.build: https://github.com/DrKLO/Telegram/blob/dev/TMessagesProj/build.gradle
