### ISSUE TITLE
Using RTC_WAKELOCK in alarm

### ISSUE THREAD

**Issue by 3mph4515** [DrKLO/Telegram#805]
Your notification scheduling based on RTC_WAKELOCK. 
It's not recommended for such needs. Repeating can be broken by wrong network time sync or user intervention in settings.
Maybe you should use ELAPSED_REALTIME_WAKEUP + elapsedRealtime() instead?

**Comment by DrKLO** [comment]
Thanks, i think it was fixed in 2.5.x.
