### ISSUE TITLE
Own branding issue about download link

### ISSUE THREAD

**Issue by 9cat** [DrKLO/Telegram#806]
I have  changed all the telegram logo and name to my own branding, 
However,

![image](https://cloud.githubusercontent.com/assets/1379110/6034969/22a54496-abdf-11e4-85ad-df4e4a58e500.png)

I have search all the string in the source code, and I can't find the string like the screen shown above.

it is still showing "https://telegram.org/dl"  anyone know what's these string come from. I really don't want to monitor and filter every message that the user sending and receiving.

**Comment by DrKLO** [comment]
It's getting from server.
