### ISSUE TITLE
Problem Adding Contacts to Group

### ISSUE THREAD

**Issue by farzadkh** [DrKLO/Telegram#807]
Hi, I've created a group named Big Data and I've added about 100 members to it, but then I've realized that only 60 persons are in group. I've tried to add them again with no success. I'm using both desktop and windows phone versions. I've tried to uninstall and reinstall the desktop version but the problem is still there.

**Comment by Paramfullestop123** [comment]
Hi friends @farzadkh  pls tell me how setup telegram in your IDE.
I am import this project on Eclipse IDE and change BuildVars.java with App_ID and App_Hash but i got null pointer exception.

**Comment by 3mph4515** [comment]
@Paramfullestop123 Use Android Studio (c)

**Comment by farzadkh** [comment]
I've used the telegram desktop -> https://tdesktop.com/win

**Comment by farzadkh** [comment]
Trying again, when I want to create a new group with the contcts that wasn't added to the previous group, the Telegram returns with no result! no group is created!

**Comment by DrKLO** [comment]
@farzadkh so there is server flood control, you should try later.

**Comment by meslahik** [comment]
if a person left a group, only a mutual contact can bring him back (both need to know each other's phone numbers)
— Telegram Messenger (@telegram) April 11, 2015
