### ISSUE TITLE
[Feature Request] Collapsing/expanding of consecutive messages in group chat

### ISSUE THREAD

**Issue by ktorn** [DrKLO/Telegram#808]
Some groups can grow quite big (up to 200 members) and some members can be quite chatty.

Not only does this create an issue in terms of notifications (as discussed in #738 ) but it makes the actual chat screen very verbose. 

I'd suggest that in group chat, consecutive messages by the same member automatically collapse after 2 or 3 messages, followed by a "more" link that when pressed expands to reveal the remaining messages, turning the "more" into a "less" link to collapse the messages again if necessary.

You find this message collapsing/expansion in several other social network contexts, but in this case I think it's best applied to consecutive messages rather than single, lenghty, messages.

It also works well for accidental message sending, such as when someone's cat walks across their keyboard when AFK.

**Comment by DrKLO** [comment]
I will not implement this. It's big overhead for mobile phones. Maybe you want to do this in your own version.
