### ISSUE TITLE
I can not send a webp file as a sticker to chat room from Google Drive in my Android phone

### ISSUE THREAD

**Issue by taijuin** [DrKLO/Telegram#814]
I can not send a webp file (as a sticker) to chat room from Google Drive or Dropbox in my Android phone.
it would be a document，not a sticker.

**Comment by Kampring** [comment]
me too, can't send webp file as a sticker from telegram for android
but with telegram for desktop work perfectly

**Comment by siavashh** [comment]
This problem is for android -5 , in android 5 we have no problem and it's work perfectly, in lower versions (lower than lollipop) the sticker file doesn't appear in chat, please fix this

**Comment by DrKLO** [comment]
I think it's fixed in 2.8.0.
