### ISSUE TITLE
Telegram crashes when sending instagram video

### ISSUE THREAD

**Issue by JonRockstein** [DrKLO/Telegram#815]
Telegram crashes when I try to send an mp4 video made with instagram (they are square, 640x640 px, maybe that's the problem).
I can reproduce this with different videos. It doesn't crash, if I edit the video with telegram (remove one frame).

**Comment by DrKLO** [comment]
Can you provide call stack?

**Comment by JonRockstein** [comment]
I'm sorry, i don't know how that works ;-)
Here is an instagram-video https://dl.dropboxusercontent.com/u/6119151/VID_30910201_202826.mp4
If you download it onto your phone and send it without editing telegram crashes (just tried it again to verify)

**Comment by JonRockstein** [comment]
Related to #619

**Comment by auchri** [comment]
@JonRockstein why closed?

**Comment by JonRockstein** [comment]
Quote:
"This crash related to some android bugs in native MediaCodec lib, unfortunately i can fix nothing in this case. Android is very bad in video encoding\decoding :("
