### ISSUE TITLE
error installing apk after ready

### ISSUE THREAD

**Issue by conectapb** [DrKLO/Telegram#818]
Ok friend will try to be more clear with my problem, I made all necessary changes, I can generate the apk perfectly, more alone than when I send to my cell to test it installs normally more when it comes the option that you type the number of the cell to activate, it hangs says "STOPPED" and ends

**Comment by DrKLO** [comment]
You should look at logcat and find crash call stack and then write it here.

**Comment by conectapb** [comment]
como faço isso?

**Comment by DrKLO** [comment]
Did you ever develop android apps?
https://www.google.com/#newwindow=1&q=logcat

**Comment by conectapb** [comment]
lol apprentice studying

**Comment by conectapb** [comment]
Unfortunately without success :(
