### ISSUE TITLE
Feature Request: hidden mode

### ISSUE THREAD

**Issue by alokmahor** [DrKLO/Telegram#822]
please add privacy feature which will allow one to hide chats that one want to keep private from the world and access them only with password so private conversation will be protected if someone takes one'e mobile

**Comment by AUDI-A4** [comment]
Agree. Password protection should be present

**Comment by DrKLO** [comment]
Password protection will be in next version.

**Comment by dserodio** [comment]
Please make the password optional. I miss the "Archive" feature from WhatsApp, which serves to declutter the conversation list.
