### ISSUE TITLE
Changing the address " Telegram "

### ISSUE THREAD

**Issue by LeonardoSummtz** [DrKLO/Telegram#824]
I am new to programming, and a school work , I had the idea of ​​open source ultilizar the telegram , first of all you do a great job , but could help me how to remove the " telegram " that has the application ?
![screenshot_1](https://cloud.githubusercontent.com/assets/10998438/6194894/e3eeae1c-b3af-11e4-8c31-bcc09ec378bf.png)

**Comment by DrKLO** [comment]
Edit AndroidManifest.xml
