### ISSUE TITLE
signingConfig.storeFile' does not exist.

### ISSUE THREAD

**Issue by LeonardoSummtz** [DrKLO/Telegram#825]
Error:A problem was found with the configuration of task ':TMessagesProj:packageDebug'.
> File 'C:\Users\USER\Desktop\Whispers\Telegram-master\TMessagesProj\config\debug.keystore' specified for property 'signingConfig.storeFile' does not exist.

Anyone know how to solve? , Did not move on any file, so correct translations , and took logos and Telegram addresses.

**Comment by DrKLO** [comment]
put keystore file to "C:\Users\USER\Desktop\Whispers\Telegram-master\TMessagesProj\config\"
