### ISSUE TITLE
Wrong messages order on connection restore

### ISSUE THREAD

**Issue by mirhl** [DrKLO/Telegram#826]
Enable airplane mode on your phone. 
Take a photo and send it to one of your telegram contact. 
Send a text message afterwards. 
Disable airplane mode and turn on either wifi or mobile data. 

Program will send every messages as soon as possible.. The image though, of course, will need some more seconds before it's sent. And server will have registered the later as if you had actually sent it after the messages. Which isn't the case. 

So I would propose to wait every message has been sent before sending the following. 
Indeed, this would pose a problem with big videos and files.. So a time/size conditional could be used. 
Or just a simple button to one should click to avoid having to wait

**Comment by DrKLO** [comment]
Never had this problem. It's not user friendly. But you may make this button in your own version and use it when you need.

**Comment by mirhl** [comment]
[This](http://youtu.be/lS4TnYxjqCA) is what I did on the phone. 
[This](https://cloud.githubusercontent.com/assets/9366725/6216310/3cbdf4f2-b609-11e4-8825-edc727c12989.png) is what I got on the desktop

Notice the inverted order. If you don't want it to be fixed.. I'm fine

**Comment by DrKLO** [comment]
I know that it's in different order. I mean I don't have problem if it will be sent in different order. It's not user friendly to wait until big file will be sent or make any buttons.
