### ISSUE TITLE
Telegram should not show you online when internet connectivity is off

### ISSUE THREAD

**Issue by AUDI-A4** [DrKLO/Telegram#830]
As per the below screenshot,It is showing my profile online even i am not connected to wifi or mobile data connection.This is not a valid thing in telegram.If we start comparing with whats app then you will notice the moment you turn off internet connectivity then you will see the last seen will go off from your contacts who is turned on last seen for you.But in case of telegram,whether your telegram is connected to internet or not.It will show the last seen from your contacts without internet connectivity which is not a good thing.

![screenshot_2015-02-14-21-16-30](https://cloud.githubusercontent.com/assets/7442148/6200116/74d8a056-b48f-11e4-96d4-4590aee37f4b.png)

**Comment by DrKLO** [comment]
It's always fake label for you, if you in app, you always online.

**Comment by Ofekalef** [comment]
But it's true, I've checked it and waited more than a minute and it didn't show me offline.
