### ISSUE TITLE
[feature] add the possibility to edit your own previous messages

### ISSUE THREAD

**Issue by PerfectCarl** [DrKLO/Telegram#832]
I have a confession: I am a bad typist.
And to make matter worse, I usually converse in other languages than my mothertongue.

I would love telegram to let me edit my messages so I can fix my obvious typos and errors.
Instead of turning red in shame each time that I browse my chat history

**Comment by tom95** [comment]
Definitely would be helpful. Quite annoying having to re-read every message you typed to make sure everything was right before sending.

**Comment by AUDI-A4** [comment]
+1 feature

**Comment by DrKLO** [comment]
No API support for this.

**Comment by PerfectCarl** [comment]
Does it mean that we need to file a feature proposal on the API project and come back here if the feature is added to the api?
