### ISSUE TITLE
dont share presence with unknown people

### ISSUE THREAD

**Issue by h-2** [DrKLO/Telegram#833]
Since I have been running Telegram, I have received messages by people that I don't know at all. This seems very weird to me, as I don't think anyone that I don't have on my contact list should be able to see when I am online, send me messages or indeed know that I have Telegram at all.
This looks like a sincere privacy issue to me, or am I misunderstanding something?

Thanks for your help!

**Comment by 4m4rOk** [comment]
Hey.
You've probably set yourself an username.
Go to Settings and save an empty username. This will remove your it and people will no longer be able to find you via search.

P.S. This will not affect existing conversations.

**Comment by h-2** [comment]
Thanks for the quick reply! I don't have any username, though...

**Comment by 4m4rOk** [comment]
In this case Telegram works like text messaging.
You can only get contacted by people who have your number in their phone book.
If you get contacted by strangers you might consider blocking them.

**Comment by DrKLO** [comment]
Soon there will be workaround for spam messages, i'm waiting for API support.
