### ISSUE TITLE
integrate secure messages in a better way

### ISSUE THREAD

**Issue by h-2** [DrKLO/Telegram#834]
It would be really nice, if I could have one conversation with both encrypted and non-encrypted messages. Then one could change Telegram to always default to a secure chat and only send insecurely, when this is not possible (i.e. the other person is offline).
Different types of messages could be colored differently. Also a "paranoid mode" could hold messages if the other contact is offline and send them only when both are online at the same time again.

This would really improve overall security from my point of view, although I agree it will make sharing the chat history of multiple clients very difficult. This on the other hand is a feature non of my contact partners use..

Thank you!

**Comment by DrKLO** [comment]
Duplicate.
It's a big overhead for logic. Because of different messages IDs, different shared media logic, self-destruct timer. Also you can create a lot of chats with one user and some of them can be discarded.
So my answer is no.
