### ISSUE TITLE
Support TeslaUnread notification count

### ISSUE THREAD

**Issue by 0nse** [DrKLO/Telegram#838]
[Nova Launcher](https://play.google.com/store/apps/details?id=com.teslacoilsw.launcher.prime) is one of the most popular launcher apps on Android. It comes with the ability to display a notification count on the respective app icon by having [TeslaUnread](https://play.google.com/store/apps/details?id=com.teslacoilsw.notifier) installed.

It offers a really [simple API](http://novalauncher.com/teslaunread-api/) for developers to integrate this service in their app.

This is low priority but it would be nice to have the official Telegram app implement this API and hence support this feature.

**Comment by DrKLO** [comment]
Their API doesn't look good. Android starting to spam in log about com.teslacoilsw.notifier package not found if Nova Laucher doesn't installed.

**Comment by 0nse** [comment]
It actually should fail silently. We all know that empty Catch-clauses are not a nice style, but if you remove the printing of the stacktrace, you shouldn't see anything in the log or am I overlooking something?

**Comment by DrKLO** [comment]
E/ActivityThread﹕ Failed to find provider info for com.teslacoilsw.notifier
