### ISSUE TITLE
Two instances on same device

### ISSUE THREAD

**Issue by mbnoimi** [DrKLO/Telegram#840]
My device supports two sim cards ([ASUS ZenFone 6](http://www.asus.com/Phones/ZenFone_6_A600CG/)).

How can I run two instances of Telegram? If I can't; Is there any way to attach two telegram accounts (ex. master account and sub-account)?

**Comment by DrKLO** [comment]
You can use two applications if you will compile other application with different package name.

**Comment by mbnoimi** [comment]
Can I change package name of compiled app?

PS.
* I've rooted device.
* I don't want to dive deep in building process because I face a problem before in building process and nobody helped me to pass it :(

**Comment by mbnoimi** [comment]
https://github.com/telegramdesktop/tdesktop/issues/445

**Comment by stefan-niedermann** [comment]
you could use webogram for the other instance, it's available as firefox app, too (if you've installed firefox) or as web application (using a browser)

**Comment by mbnoimi** [comment]
@stefan-niedermann Do you mean Firefox OS or Firefox the browser?

Sorry I didn't test Firefox OS and never run Firefox browser under Android

**Comment by stefan-niedermann** [comment]
I mean Firefox Browser - it allows you to "install" WebApps - like Telegram/Webogram. so you would not have two instances of android telegram app, but you could use two accounts: one with android telegram app and one with firefox browser webapp (webogram)

**Comment by mbnoimi** [comment]
Fantastic solution @stefan-niedermann 

Thanks a lot.

**Comment by mbnoimi** [comment]
Wow Telegram is very flexible application.
