### ISSUE TITLE
Emoji drawer background is too dark. Please increase the brightness of the Emoji drawer background.

### ISSUE THREAD

**Issue by wp9015362** [DrKLO/Telegram#843]
Dear Telegram developers,

the background of the Emoji drawer in Telegram is quite dark, it's almost if not even fully black.

Unfortunately that can be an issue with some of the darker Emojis. There's not enough contrast between the dark Emojis and the dark background of the Emoji drawer.

In WhatsApp, the background of the Emoji drawer is a little bit brighter than in Telegram.

Here is a picture which compares both:

http://imagenes.es.sftcdn.net/blog/es/2014/02/Whatsapp-and-telegram.jpg

Source: http://features.en.softonic.com/telegram-better-than-whatsapp

Could you please increase the background of the Emoji drawer in Telegram to something like how it is in WhatsApp (see picture above) to increase the contrast between the darker Emojis and the background?

It would be much appreciated.

Regards

**Comment by wp9015362** [comment]
@DrKLO Is that something you are going to do?

Can you please make the background of the Emoji drawer brighter?

Black simply is too dark.

It would be much appreciated if you would do it.

**Comment by wp9015362** [comment]
@DrKLO :

Maybe I should give you some examples, to explain to you better why the dark background currently being used on the Emoji drawer of Telegram-Android simply is incompatible with the Emojis:

The following black symbols for example are all almost invisible on the dark background currently being used by the Telegram-Android Emoji drawer:

:end: :soon: :registered: :heavy_minus_sign: :wavy_dash: :arrows_clockwise: :back: :heavy_dollar_sign: :heavy_multiplication_x: :heavy_check_mark: :top: :currency_exchange: :on: :copyright: :heavy_plus_sign: :curly_loop: :notes:

Those symbols are all pretty much black and therefore almost invisible on the dark background.

Also, some more examples:

:zzz:
You can't see the first "Z" on the dark background.
:wave:
You can't see the dark waves next to the hand on the dark background.
:dash: 
You can't see the small streaks on the right side of the cloud on the background.
:japanese_ogre:
You can't see the beard around the face on the dark background.
:movie_camera:
It's hard to see the movie camera on the dark background.
:electric_plug:
It's hard to see the plug on the dark background.
:gun:
It's hard to see the grip on the dark background.
:microphone:
It's hard to see the notes next to the microphone on the dark background.

As you can see, the dark background currently being used on the Emoji drawer of Telegram Android is incompatible with those Emojis.

Therefore:

Could you please please increase the brightness of the background to make it gray instead of black?

Or maybe just use the same silver/gray color that is being used for the iOS keyboard Emoji drawer?

Here are some screenshots of the iOS keyboard Emoji drawer, where you can see the silver/gray background:

http://blog.getemoji.com/emoji-keyboard-iphone

Could you please do that?

And maybe even do it for the next version like this:

https://github.com/DrKLO/Telegram/issues/936

?

It would be much appreciated.

Regards

**Comment by wp9015362** [comment]
@DrKLO :

Looks like the screenshot in the first post (http://imagenes.es.sftcdn.net/blog/es/2014/02/Whatsapp-and-telegram.jpg) actually is showing an old version of Telegram for Android. In the old version the Emoji drawer background was darker and had a gradient.

The current Emoji drawer background actually is a little brighter and has no gradient, as can be seen in the following screenshot for example:

https://telegram.org/file/811140073/1/IP83JaSL9H8/4f056c95a1cd5f0fec

But still, the background is still too dark.

It has RGB values of R: 34 / G: 34 / B: 34.

That is too dark for some of the darker Emojis.

I analyzed some screenshots of the WhatsApp Emoji drawer. And I got RGB values between R: 54 / G: 54 / B: 54 and R: 71 / G: 71 / B: 71 for the WhatsApp Emoji drawer background (different screenshots showed different values, maybe they were all from different WhatsApp versions, but 54 was always the minimum).

So, could you please increase the brightness of the Telegram for Android Emoji drawer background, so that is has RGB values of at least R: 64 / G: 64 / B: 64?

Or simply make it have the same background brightness as the iOS Emoji keyboard?

According to the screenshots over there for example:

http://blog.getemoji.com/emoji-keyboard-iphone

the RGB values of the iOS 8 Emoji keyboard background seem to be somewhere around R: 207 / G: 211 / B: 217.

Please do something about the Telegram for Android Emoji drawer background brightness. R: 34 / G: 34 / B: 34 simply is too dark.

It would be much appreciated.

Regards

**Comment by Multimoon** [comment]
If you want this change so badly why not fork it and make it yourself.

**Comment by wp9015362** [comment]
> @Multimoon wrote:
> 
> If you want this change so badly why not fork it and make it yourself.

I would have understood it if you would have said "If you want this change so badly, why not do it yourself and submit a pull request?".

But coming here suggesting a fork even though my request is about a bug, I definitely can not understand.

And I have a feeling that you simply feel insulted because of https://github.com/DrKLO/Telegram/issues/843 and now are trying to let out your frustration on me with comments like those...

As already mentioned, the dark background simply is incompatible with the Emojis, as some of the darker (parts of the) Emojis can not be properly seen on the dark background, so it should be changed IMHO. It's not just a personal preference, but a bug.

Anyway:

Any hint to what part of the source code would need to be changed to increase the brightness?

**Comment by Multimoon** [comment]
Find the layout XML file for the keyboard and set android:background.

**Comment by wp9015362** [comment]
Well,

would this:

https://github.com/DrKLO/Telegram/blob/2f874619264ac65213baf2300a3e53fdf34aec09/TMessagesProj/src/main/java/org/telegram/ui/Components/EmojiView.java

be the correct component?

I currently am not a developer, so:

What exactly needs to be changed to change the colors in the Emoji drawer?

And is there any easy way to edit the Emoji drawer colors and see the results of the edits without compiling the source code and so on?

@DrKLO :

If you are reading this:

It would be nice if you could simply change the parts of the Emoji drawer which are currently RGB 34, 34, 34 to be somehwere around RGB 60, 60, 60.

I did my own very simple mockup of this using Paint and simply changed the parts which are RGB 34, 34, 34 to be somehwere around RGB 60, 60, 60 and it looks fine without changing the other parts.

So that would probably be a very simple change for someone who actually is familiar with the source code, and yet it would still already help with the darker Emojis.

Regards

**Comment by wp9015362** [comment]
@DrKLO:

WhatsApp for Android apparently has received a new material design user interface with the latest update.

The Emoji drawer in the new WhatsApp material design user interface now looks like this:

http://www.androidpolice.com/wp-content/uploads/2015/04/nexus2cee_whatsapp-material-7.png ([Source](http://www.androidpolice.com/2015/04/14/hands-on-whatsapp-goes-material-with-cool-animations-fabs-and-lots-of-purty/))

![Image](http://www.androidpolice.com/wp-content/uploads/2015/04/nexus2cee_whatsapp-material-7.png)

As you can see, the background of the Emoji drawer is now much brighter and fits better with the overall material design (IMHO).

Could you please do the same for Telegram for Android?

It would be much appreciated.

Regards

**Comment by wp9015362** [comment]
@DrKLO :

Thank you very much for having fixed this with v2.8.0.

:+1: 

Regards
