### ISSUE TITLE
Please increase display size of Emojis in messages or alternatively add an option to increase the display size of Emojis in messages (independently from the message text size)

### ISSUE THREAD

**Issue by wp9015362** [DrKLO/Telegram#844]
Dear Telegram developers,

in Telegram, the Emojis in messages are currently displayed at the same height as the font/text height.

Unfortunately that way the Emojis are being displayed at a relatively small size.

In WhatsApp, the Emojis are displayed with a greater height than the font/text height.

Here is a picture which compares both:

http://imagenes.es.sftcdn.net/blog/es/2014/02/Whatsapp-and-telegram.jpg

Source: http://artikel.softonic.de/tschuss-whatsapp-5-tipps-zur-sicherung-von-chats-und-kontakten-24-02-2014

As you can see, WhatsApp displays the Emojis somehwat bigger than Telegram does, which looks better IMHO and increases the visibility of course.

Could you please increase the display size of the Emojis in messages to something like how it is in WhatsApp (see picture above) or alternatively add an option to change the display size of Emojis in messages (independently from the message text size)?

It would be much appreciated.

Regards

**Comment by DrKLO** [comment]
No, emoji size = font size. Larger emoji will break line height.

**Comment by alokmahor** [comment]
"Telegram aniways" have feature of changing size of emoticons
