### ISSUE TITLE
Passcode issue  in Telegram 2.5.0(439)

### ISSUE THREAD

**Issue by AUDI-A4** [DrKLO/Telegram#846]
As the today released version have passcode option which i really like.But the one thing, which is messed up, that is every time i need to tap up the lock icon to lock the Telegram for the next time opening of telegram which is really a big headache.Can you please make the option to lock the app permanently without tapping the lock icon every time.

**Comment by DrKLO** [comment]
It's not finished, please don't write about beta features.
