### ISSUE TITLE
Adding a member to the group who left earlier doesn't give him older messages even if chosen to show

### ISSUE THREAD

**Issue by shibme** [DrKLO/Telegram#851]
Steps to repro:
Add a user to a group.
Send some messages.
Ask him to exit group.
Now add him again and set previous message limit as 999 or something.

Expected:
The user should get the older messages in that group thread.

Actual:
The user doesn't get the older messages.

**Comment by DrKLO** [comment]
When user exit from group, he delete all his messages inside this group, so nothing to forward.
Server side logic.

**Comment by JunaidBabu** [comment]
Is there a way where the user can exit the group without deleting the messages from the group (like whatsapp does)?
