### ISSUE TITLE
Feature Request: Disable Activation Broadcast

### ISSUE THREAD

**Issue by KeyMar** [DrKLO/Telegram#855]
A seemly flag for disable account activation broadcast.
I think it could be appreciated by privacy maniacs 
(Needs protocol modification perhaps).

**Comment by DrKLO** [comment]
I don't understand what you mean.

**Comment by KeyMar** [comment]
When you active a new number a message is broadcasted to all your contact already have telegram.
Many my friends say that is not good some times. A good alternative is to decide who can receive this notice.  This is a one time option and i, in first, say, I'm not secure they want to add it.

**Comment by DrKLO** [comment]
It's server side, nothing can be changed by me.
