### ISSUE TITLE
Edit the open source code and run

### ISSUE THREAD

**Issue by EasonWang01** [DrKLO/Telegram#857]
I have success remove the Support--Telegram FAQ but I do not know how to remove the other Telegram FAQ which is below Setting icon 

Also,I was trying to change the Application name and remove F&Q and Ask a question
 which line I should change in DrawerLayoutAdapter.java, SettingsActivity.java and AndroidManifest.xml? thanks a lot

**Comment by DrKLO** [comment]
Discussed a lot of times already, please use search.
