### ISSUE TITLE
Feature Request: Voice message from android wear

### ISSUE THREAD

**Issue by shibme** [DrKLO/Telegram#860]
Message or reply with voice on android wear app would be greatly appreciated. Would be really helpful as predictions might fail from android wear while on travel.

**Comment by DrKLO** [comment]
Are you sure that it's possible? Check documentation, Android Wear only giving voice converted to text.

**Comment by shibme** [comment]
I guess it is possible. There's a voice recorder app for android wear which can record voice data right from the mic in my watch and I can replay them in my paired phone. If that is possible, so should be this. It would an awesome feature and most importantly no IM app has ever done it.

**Comment by DrKLO** [comment]
@shibme it's possible only for standalone application on android wear, not for notifications.
