### ISSUE TITLE
Blue chat background is not repeated over display

### ISSUE THREAD

**Issue by 0nse** [DrKLO/Telegram#863]
The blue chat background (which features only the colour without any cats or dogs) is not being stretched or repeated and hence leaves a white background:
![screenshot_2015-02-25-22-58-21](https://cloud.githubusercontent.com/assets/7449611/6381526/01a88644-bd42-11e4-9dd8-60b938fb9bda.png)
This is especially problematic with the new PIN protect feature:
![screenshot_2015-02-25-23-00-08](https://cloud.githubusercontent.com/assets/7449611/6381577/70405316-bd42-11e4-991b-83d4e600492f.png)

**Comment by DrKLO** [comment]
Thanks, fixed in last build.
