### ISSUE TITLE
PIN need's to be a number

### ISSUE THREAD

**Issue by frunc** [DrKLO/Telegram#864]
While setting up a PIN I have "numbers" keyboard with numbers and some symbols. If I put for examples 4 dots for pin application will ask me to reenter new PIN, but when I'm trying to enter application i don't see my own keyboard and I will not be able to enter dots. So application need to check did I enter only numbers without any symbol before it continues asking for reenter PIN.
I didn't try put symbol because. I don't want to reinstall application if this problem occurs.

**Comment by DrKLO** [comment]
Thanks, fixed in last build.

**Comment by frunc** [comment]
Everything is ok instead now I'm not able to insert 0. Numbers 1-9 works perfectly

**Comment by DrKLO** [comment]
It's also was fixed in 2.5.1
