### ISSUE TITLE
Help rebuild the native libraries

### ISSUE THREAD

**Issue by conectapb** [DrKLO/Telegram#865]
Who can I help rebuild the native libraries, I have done all the procedures that asks more do not know what commands to be able to recompile

**Comment by mokhtarabadi** [comment]
First download android ndk then run this command ndk-build -C path/to/TMessages/jni, if you have issue please first search!

**Comment by conectapb** [comment]
just start with this command in the terminal? ndk-build -C path / to / TMessages / jni if so it not the right says it is not recognized as an internal command

**Comment by conectapb** [comment]
??

**Comment by mokhtarabadi** [comment]
In Arch Linux, I downloaded latest android ndk and extract it to a folder, and edit PATH environment variable and add ndk path to it, so in terminal when I type ndk-build, it's perfect worked for me, (Sorry for English)
