### ISSUE TITLE
About  auth.sendSms

### ISSUE THREAD

**Issue by EasonWang01** [DrKLO/Telegram#866]
If I want to let other user who download my edited version of telegram,when he send his number and wait to receive verify code like 54236,could I use auth.sendSms API to tranfer the verify SMS directly send to my phone not his phone,then I can tell him what his verify code is than he can log in ?

I saw the code below but I don't know  which folder I need to add them in

{
boolFalse#bc799737 = Bool;
boolTrue#997275b5 = Bool;
---functions---
auth.sendSms#da9f3e8 phone_number:string phone_code_hash:string = Bool;
}

thanks

**Comment by DrKLO** [comment]
no, it's not possible.
