### ISSUE TITLE
FEATURE - Customize Sound / Background for Individual users / groups

### ISSUE THREAD

**Issue by luisalvarado** [DrKLO/Telegram#867]
This is a draft idea for the Telegram Dev Team (Keep it up. I just moved 2 companies and about 100+ users to Telegram from Viber and WhatsApp, they simply love it).

This would be a full customization offer for Telegram users that will offer the following features:

+ Offer users a way to customize the notification sound for specific users or groups (eg: My wife will have a mario bros tone while my boss would have a Dr. Robotnik one). Right now on android, there is only 1 tone for all Telegram users which is not customizable to know which user was written to you.

+ Offer customized backgrounds for specific users or groups.

This idea came to me because I wanted my wife to have the zelda theme song, my mom the mario bros song and my boss dr robotnik which is not possible right now. So maybe this can be reviewed as a potential idea. Thank you.

**Comment by DrKLO** [comment]
1) Check notifications and sounds settings in profile. You can specify sound for every single char or user.
2) Background image load took a lot of time to load since it's size is too big, so there always be a lag before opening chat.

**Comment by luisalvarado** [comment]
Found the sound settings, many thanks DrKLO. For the background image you are totally right about the lag that will be created. Thanks for the feedback.
