### ISSUE TITLE
Error 'dependencies' cannot be applied to '(groovy.lang.Closure)'

### ISSUE THREAD

**Issue by lgdelai** [DrKLO/Telegram#870]
Hello, I am getting these two errors:

Use version 1.10 of gradle, then tried to change the line 8 1.0.0 to 1.10, but did not solve the problem.

My gradle is in the folder: C: \ AndroidDeveloper \ android-studio \-gradle 1:10

Can anyone help me?

![erro telegram](https://cloud.githubusercontent.com/assets/7806314/6404592/7d5b350a-bdf8-11e4-850e-146a1eae6771.jpg)

**Comment by lgdelai** [comment]
Executing tasks: [clean, :assemble]

Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Build file 'E:\Documentos\- Documentos BKP\- Android Studio Projects\Telegram-master\TMessagesProj\build.gradle' line: 13

* What went wrong:
A problem occurred evaluating project ':TMessagesProj'.
> Could not create plugin of type 'AppPlugin'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.541 secs

**Comment by conectapb** [comment]
AMIGO lgdelai MIM TIRE UMAS DUVIDAS POR FAVOR

**Comment by developermakj** [comment]
precisa usar o brech - "DEV" e não o Master veja a atualização

**Comment by lgdelai** [comment]
Tks @developermakj 
I try another solution.
