### ISSUE TITLE
[Feature request] Sticker library and ability to import custom stickers into it

### ISSUE THREAD

**Issue by andreasackermann** [DrKLO/Telegram#872]
**Why?**
Me and my friends regularly send custom Stickers to each other and it is currently a pain on the phone to search for them in the message history and then forwarding them again to the chat.

**Of what use is this for Telegram?**
The ability to let users easily send custom sticker to each other would further set it apart from other messengers which do not offer this ability. Also, it is just really cool.

**How?**
I would recommend a new button in the action bar which appears when one presses on a sticker allowing the user to import the sticker to his sticker gallery.
To send a sticker, I would recommend a new button in the attach menu which would bring up the sticker gallery, in which the user could select a sticker he wants to send. I suppose one could reuse the existing gallery picker.

**Comment by Lapayo** [comment]
+1 :)

**Comment by narunetto** [comment]
I agree that this should be put in, I also think in the desktop and the phone there should be a way to make sticker sets for your friends and you. The custom stickers are one of my favourite features about Telegram other than the rest of the nice things and not being able to use them on mobile is my biggest pet peeve.

**Comment by Fexys** [comment]
:+1:

**Comment by Mindstormer619** [comment]
I think it's here in the latest update.

**Comment by andreasackermann** [comment]
A sticker library yes, which is an awesome improvement, but the import of received custom stickers is sadly still missing.

**Comment by AUDI-A4** [comment]
no it is there in latest update.after receiving the sticker then tap into stickers and click on add to stickers

**Comment by andreasackermann** [comment]
Oh, I did not notice that. Thank you guys very much for implementing it.
