### ISSUE TITLE
Avast error on install apk, Android:Whapsni-E [PUP]

### ISSUE THREAD

**Issue by lgdelai** [DrKLO/Telegram#873]
Hello.

When I install my app based on the telegram, avast is detecting as a virus, the message is:

Android: Whapsni-E [PUP]

How do I resolve this?

**Comment by DrKLO** [comment]
You should write to Avast developers.

**Comment by lgdelai** [comment]
I wrote.
But I do not think that answer me, let's wait.

I just wondered if it could be because of some feature or test new features.

Thank U @DrKLO  

Congratulations for the awesome work on Telegram.
