### ISSUE TITLE
Can't find class DrawerLayoutContainer$InsetsListener

### ISSUE THREAD

**Issue by lgdelai** [DrKLO/Telegram#874]
Hello @DrKLO 
My project is issuing the following error:

03-01 14:25:50.928  31247-31247/org.telegram.messenger E/ViewRootImpl﹕ sendUserActionEvent() mView == null

03-01 14:25:51.519  31247-31247/org.telegram.messenger E/ViewRootImpl﹕ sendUserActionEvent() mView == null

03-01 14:31:08.768  32631-32631/org.telegram.messenger E/dalvikvm﹕ Could not find class 'org.telegram.ui.ActionBar.DrawerLayoutContainer$InsetsListener', referenced from method org.telegram.ui.ActionBar.DrawerLayoutContainer.configureApplyInsets

Very thanks to every help.

**Comment by lgdelai** [comment]
Nobody know?  

:(

**Comment by conectapb** [comment]
Ei garoto vc é brasileiro?

**Comment by lgdelai** [comment]
I Find another solution.
Tanks.
