### ISSUE TITLE
Buttons titles are not translated

### ISSUE THREAD

**Issue by malishev** [DrKLO/Telegram#876]
I have a string in my XML localization file:
```xml
<string name="Cancel">Отменить</string>
...
<string name="OK">OK</string>
```
But the titles are not translated:
![photo8189399283116563](https://cloud.githubusercontent.com/assets/2178368/6428451/67efe9d8-bfb3-11e4-9f36-0cfa0af43666.jpg)

Telegram 2.5.2 on Android 5.0

**Comment by DrKLO** [comment]
Thanks, fixed in 2.6.0.
