### ISSUE TITLE
change color of the chat text

### ISSUE THREAD

**Issue by developermakj** [DrKLO/Telegram#877]
Hello guys, I need to help me with this file, which I can not find .. to change the color of the chat text is in black color ... want to put white 
![0b5d17ce-98dd-11e4-9856-883a755a7b01](https://cloud.githubusercontent.com/assets/10384191/6428874/744bb9ae-bf91-11e4-985b-b2bad8053466.png)

@DrKLO Help me? rsrs

**Comment by conectapb** [comment]
Ei boy vc é brasileiro?

**Comment by UnixH** [comment]
Sim

**Comment by UnixH** [comment]
Essa e outra conta que uso para falar pelo celular, mais sou sim brasileiro

**Comment by conectapb** [comment]
qual seu email amigo ou facebook. whatsapp? para trocar-mos algumas ideias ou

**Comment by UnixH** [comment]
makjnewcosta@gmail.com

**Comment by conectapb** [comment]
Pronto to no email

**Comment by DrKLO** [comment]
ChatMessageCell.java

**Comment by developermakj** [comment]
what? line ? @DrKLO

**Comment by DrKLO** [comment]
Oh, I'm wrong. MessageObject.java
textPaint.setColor(0xff000000);

**Comment by developermakj** [comment]
@DrKLO muito obrigado, imagino como deve ser difícil responder tantas perguntas em um dia, desculpa minhas perguntas bestas sempre... obrigado sempre DrKLO

**Comment by developermakj** [comment]
@DrKLO thank you, imagine what it must be difficult to answer so many questions in one day, excuse my beasts questions always ... always obliged DrKLO
