### ISSUE TITLE
NullPointerException at org.telegram.messenger.UserConfig.loadConfig(UserConfig.java:109)

### ISSUE THREAD

**Issue by Sergey63** [DrKLO/Telegram#878]
Hi.
i'm try run project, but always have nullPointerException. 
I'm fill form in https://my.telegram.org/apps and copy it in BuildVars APP_ID, APP_HASH. 
Then create new project in https://console.developers.google.com/project and copy PROJECT ID in BuildVars.GCM_SENDER_ID. How i understand BuildVars.HOCKEY_APP_HASH need for get log from users, so i skip it.
Next i add all needed libs (project hasn't Errors) and try run but not luck. What am I doing wrong?

**Comment by DrKLO** [comment]
Just remove hockey app from project.

**Comment by Sergey63** [comment]
I try remove hockey app from project but nullPointerException in UserConfig(109): 
final File configFile = new File(ApplicationLoader.applicationContext.getFilesDir(), "user.dat");

When print in log:
Log.v("test", "applicationContext = " + (ApplicationLoader.applicationContext == null));
it show me true, so when i go in ApplicationLoader, i find initialization applicationContext:
applicationContext = getApplicationContext();
in this case log show that applicationContext == null.

Have you got some idea why applicationContext  not initialized?

**Comment by Sergey63** [comment]
DrKLO, i try run project and have new problem:

[2015-03-03 15:28:10 - google-play-services_lib] Could not find google-play-services_lib.apk!

I add this string in project:

<meta-data android:name="com.google.android.gms.version"
           android:value="@integer/google_play_services_version" />

And add dependency on project - google-play-services_lib.
Do you know why google-play-services_lib don't pack in apk?

**Comment by Sergey63** [comment]
@DrKLO, i'm try run your project, but have problem with jni. When try start project on AVD, i have next error:
at org.telegram.SQLite.SQLiteDatabase.opendb(Native Method)
at org.telegram.SQLite.SQLiteDatabase.<init>(SQLiteDatabase.java:25)

How i understand "opendb" and other native methods must call out from generated libs (.so), but this does not happen. Do you now what the problem?
