### ISSUE TITLE
change color of the chat text again

### ISSUE THREAD

**Issue by developermakj** [DrKLO/Telegram#880]
@DrKLO the file changes the two texts, sending and receiving! and want to change only the color sending, not receiving message, I will show you an example below
I want it that way
![b32vpcn](https://cloud.githubusercontent.com/assets/10384191/6434510/5ee3c650-c069-11e4-9bac-50043f50cd7b.png)

more you told me where to find the file to change, the more changes there the two texts...
is to stay that way 
![7ngvsoz](https://cloud.githubusercontent.com/assets/10384191/6434528/cf6de180-c069-11e4-8b59-a07477971295.png)

@DrKLO help me again? for today will be the last time :dancer:

**Comment by developermakj** [comment]
@DrKLO Help me again? rsrs

**Comment by DrKLO** [comment]
You should create different Paint for incoming messages and use it in StaticLayout creation.
