### ISSUE TITLE
Change text color of messages_list ?

### ISSUE THREAD

**Issue by lgdelai** [DrKLO/Telegram#881]
Hello @DrKLO .

I'm trying to change the text color of  "messages_list.xml"  screen on 
" android:textColor="#808080" "       

but I can not.

------------------------
        <TextView
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:textColor="#808080"
            android:gravity="center"
            android:textSize="20dp"
            android:id="@+id/search_empty_text"
            android:layout_weight="1"/>
-----------------------

It is in another file?

**Comment by developermakj** [comment]
Eu fiz em outro arquivo, não e ai não !

**Comment by lgdelai** [comment]
Thank's
I go try again.

**Comment by developermakj** [comment]
leave your email to contact
