### ISSUE TITLE
error: incomparable types: Object and int  on PasscodeView.java in Telegram-dev

### ISSUE THREAD

**Issue by lgdelai** [DrKLO/Telegram#883]
Hello @DrKLO 

Using source: Telegram-dev'm getting this error:

--------------
error: incomparable types: Object and int

-------
It occurs in the file:
\ Telegram-dev \ TMessagesProj \ src \ main \ java \ org \ telegram \ ui \ Components \ PasscodeView.java

On line: 114
if (passwordFrameLayout.getTag ()! = 0) {

**Comment by lgdelai** [comment]
Solved,  i ut null on 0 place.

**Comment by ivanchik77** [comment]
thank you!

**Comment by EdoEscada** [comment]
Hi friend :) I have the same problem, so what is the solution, not clear answer above

**Comment by EdoEscada** [comment]
Thats OK then.
But after I created the APK, when it was running, there is a message : 
"Unfortunately, Telegram has stopped" ... mind to advise please :)

**Comment by ivanchik77** [comment]
I have the same problem, it would be wonderful if there was a good document showing step by step and rename the package assembly on android Studio
Sorry for my English
