### ISSUE TITLE
Anyone know report that error is that?

### ISSUE THREAD

**Issue by conectapb** [DrKLO/Telegram#887]
Launching application: org.telegram.messenger/org.telegram.ui.LaunchActivity.
DEVICE SHELL COMMAND: am start -n "org.telegram.messenger/org.telegram.ui.LaunchActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=org.telegram.messenger/org.telegram.ui.LaunchActivity }
Error type 3
Error: Activity class {org.telegram.messenger/org.telegram.ui.LaunchActivity} does not exist.

**Comment by conectapb** [comment]
Anyone ?

**Comment by Stuie** [comment]
Have you edited the LaunchActivity class or your AndroidManifest file?

**Comment by conectapb** [comment]
unsuccessfully :(
