### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Native method not found

### ISSUE THREAD

**Issue by MarcusAdriano** [DrKLO/Telegram#891]
I create a new project in Android Studio and copy all codes of Telegram Project.
My package name is marcusadriano.br.com.pombocorreio, i replaced "org_telegram" by "marcusadriano_br_com_pombocorreio" in all classes native and i get this error when running the app.

"java.lang.UnsatisfiedLinkError: Native method not found: marcusadriano.br.com.pombocorreio.SQLite.SQLiteDatabase.opendb:(Ljava/lang/String;Ljava/lang/String;)I
            at marcusadriano.br.com.pombocorreio.SQLite.SQLiteDatabase.opendb(Native Method)"

 Note: I already recompiled the native codes using NDK.

![image](https://cloud.githubusercontent.com/assets/7614148/6528610/e5faae88-c401-11e4-83a0-be047e368018.png)

**Comment by DrKLO** [comment]
I'm sure that you incorrectly renamed native methods.
