### ISSUE TITLE
Application integration issue, more inputs on how to use Available MTProto servers and Public keys(NullPointerException).

### ISSUE THREAD

**Issue by NitzDKoder** [DrKLO/Telegram#899]
Hey Folks,

Using Update to 2.4.0.

Trying to load the app it crashes always.

Also "Available MTProto servers and Public keys:" where to put these configuration/Keys is not mentioned anywhere.
https://my.telegram.org/apps

I have filled BuildVars variables as needed,except BING_SEARCH_KEY.

"
03-05 14:03:09.359: E/AndroidRuntime(18324): Process: org.telegram.messenger, PID: 18324
03-05 14:03:09.359: E/AndroidRuntime(18324): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
03-05 14:03:09.359: E/AndroidRuntime(18324): at org.telegram.messenger.ConnectionsManager.processMessage(ConnectionsManager.java:2143)
03-05 14:03:09.359: E/AndroidRuntime(18324): at org.telegram.messenger.ConnectionsManager.tcpConnectionReceivedData(ConnectionsManager.java:2664)
03-05 14:03:09.359: E/AndroidRuntime(18324): at org.telegram.messenger.TcpConnection$9.run(TcpConnection.java:526)
03-05 14:03:09.359: E/AndroidRuntime(18324): at android.os.Handler.handleCallback(Handler.java:739)
03-05 14:03:09.359: E/AndroidRuntime(18324): at android.os.Handler.dispatchMessage(Handler.java:95)
03-05 14:03:09.359: E/AndroidRuntime(18324): at android.os.Looper.loop(Looper.java:135)
03-05 14:03:09.359: E/AndroidRuntime(18324): at org.telegram.messenger.DispatchQueue.run(DispatchQueue.java:100)
"
Pls Need more inputs @DrKLO 

Thanks

**Comment by DrKLO** [comment]
You should increase you versionCode in build.gradle, because app moved to 23 layer and it should send initConnection request to server.

**Comment by NitzDKoder** [comment]
@DrKLO well it worked..you are real geek out here..awesome coding..thanks

**Comment by bcenge** [comment]
I paid for you by a telegram package modified " ati " can someone help me
