### ISSUE TITLE
Bug Report: Emoji turn into native style on android after certain amounts

### ISSUE THREAD

**Issue by GeQi** [DrKLO/Telegram#900]
Windows:
![unnamed qq screenshot20150310204710](https://cloud.githubusercontent.com/assets/4011632/6589627/441b4338-c768-11e4-9e04-33124a039f45.png)
Android:
![photo_2015-03-10_20-47-17](https://cloud.githubusercontent.com/assets/4011632/6589626/44195e10-c768-11e4-82de-122465ea13d9.jpg)

**Comment by DrKLO** [comment]
Duplicate. Emoji replacement limited to 50 due to performance issues.
