### ISSUE TITLE
Notifications on iPhone appear for one second and get auto-cleared

### ISSUE THREAD

**Issue by itsBasir** [DrKLO/Telegram#906]
Occasionally notifications on my iPhone only appear for 1 second (or less) and then disappear. With all mention of them gone, not in Notification Center or even the app badge.

Others have also told me that it shows me as coming online and reading their messages, but that is not the case. I have no other sessions signed in.

**Comment by AUDI-A4** [comment]
@itsBasir this repository is meant for android not ios thanks

**Comment by DrKLO** [comment]
I transferred this issue to iOS developer. Thanks.
