### ISSUE TITLE
Remove Contact

### ISSUE THREAD

**Issue by PatrickWinkler** [DrKLO/Telegram#907]
I removed an contact from my phone, but it still remains in my telegram list and i see no option to get rid of it.

thanks

EDIT: 
Sorry i was i little bit fast to open this issue, now i found that option.
It would be easier if you can just mark contacts from the list with a long click to delete them.

**Comment by DrKLO** [comment]
I disabled option to delete user from Telegram when it's deleted from contacts list, because sometimes android goes crazy and can return empty contacts list, so it will wipe all of you contacts.
Ok, i will add option to delete contact with long press later.
