### ISSUE TITLE
Drunk mode

### ISSUE THREAD

**Issue by alorma** [DrKLO/Telegram#909]
Hi.

I really like the new PIN feature, that prevents users to expose their private date to anyone.

Talking with a friend i think it's great to have something like "drunk ode" that help telegram users to not use telegram if you are not at 100%.

Something like puzzles, or math operations, or ability to "block" users for a while (or me, as receiver block another user).

What do you think?

**Comment by MrGluek** [comment]
Drink responsibly.

**Comment by davux** [comment]
I find the idea very funny, and also I don't think it's a good idea in Telegram, unless you phrase it in a more generic way.

I also think it was very rude from DrKLO to close the request without even a word.
