### ISSUE TITLE
telegram code source error

### ISSUE THREAD

**Issue by hassen66** [DrKLO/Telegram#912]
when i combilted telegram code source  i get an error
i use android sdk 1.1.0
Error:A problem was found with the configuration of task ':TMessagesProj:packageDebug'.
> File 'C:\Telegram-master\Telegram-master\TMessagesProj\config\debug.keystore' specified for property 'signingConfig.storeFile' does not exist.

**Comment by DrKLO** [comment]
So you should place debug.keystore in place where it want this file.
