### ISSUE TITLE
error run app

### ISSUE THREAD

**Issue by hassen66** [DrKLO/Telegram#913]
i get an error when i run my app to my android
unfortunately has stopped

**Comment by DrKLO** [comment]
Can you provide any call stack? Without addition info this issue is useless.

**Comment by EdoEscada** [comment]
Same here,
Dear Doctor, I have produced the APK and then run it in my Android smartphone. The error is : Unfortunately, (AppsName) has stopped, happened in my 3 Android Smartphones.

Following some internet advises, I have cleared cache, clear RAM, restarted my mobile, set my Google Play Store not to update APK, 

I use Android Studio the latest version.
Hoping your advise so crazy:)

Thx
Regards
