### ISSUE TITLE
Emojis seem to suffer from visible image compression and seem to have broken transparency. Please use lossless compression with proper transparency instead.

### ISSUE THREAD

**Issue by wp9015362** [DrKLO/Telegram#914]
Dear Telegram developers,

the Emojis in Telegram for Android seem to suffer from visible image compression, which gets especially noticeable upon increasing the message font size (which makes the Emojis become larger as well).

To me it looks like as if the Emojis would be images which are compressed using JPEG or something like that and as if they would have a lot of compression and maybe even chroma subsampling (4:2:0) applied to them.

In addition, the transparency of the images seems to be somewhat broken, because you can see a faint rectangle behind/around them.

Unfortunately I don't know where those images are stored on GitHub, so I don't know how to look at them with a PC. Therefore I can only tell from looking at them from inside the Telegram Android app.

And from there it looks like as described above.

So, could you please use lossless compression without chroma subsampling (i.e. with full chroma resolution, i.e. 4:4:4) for them instead? Like PNG for example?

It would be much appreciated.

Regards

**Comment by DrKLO** [comment]
Emoji textures was saved as jpeg for reduce it's size. Alpha channel also saved in jpeg as grayscale image. Size is critical for android 2.x devices. Also loading jpeg is faster then png. No other solution for it until I will drop 2.x support.

**Comment by wp9015362** [comment]
Thanks for your fast response @DrKLO .

> @DrKLO wrote:
> 
> Emoji textures was saved as jpeg for reduce it's size.
> Alpha channel also saved in jpeg as grayscale image.

I think I might have found where the images are stored on GitHub now:

https://github.com/DrKLO/Telegram/tree/master/TMessagesProj/src/main/assets/emoji

?

I had a look at those images and unfortunately they indeed are saved with a lot of compression (JPEG quality 62) and indeed are saved with chroma subsampling (4:2:0).

@DrKLO could you please at least save them without chroma subsampling (i.e. full chroma resolution, i.e. 4:4:4)?

Please see what chroma subsampling does to colors:

Without chroma subsampling (4:4:4):

![rgbk3olr](https://cloud.githubusercontent.com/assets/7558360/6662225/0827d33c-cbb9-11e4-9299-dfcbaf7b4d04.png)

With chroma subsampling (4:2:0):

![yuv420amq5v](https://cloud.githubusercontent.com/assets/7558360/6662230/24c85b1a-cbb9-11e4-9336-c41feea24a55.png)

As you can see, the image with chroma subsampling (4:2:0) looks much worse than the picture without chroma subsampling (4:4:4).

JPEG allows for saving images without chroma subsampling.

So, could you please try to compress the Emojis with JPEG but with chroma subsampling disabled, so that they will retain their full chroma resolution (i.e. be 4:4:4)?

It would be much appreciated.

It would be really nice if you could do that at the very least.

And it would be even nicer if you could also try to increase the JPEG quality a bit. As mentioned above, the Emojis currently seem to be compressed with a JPEG quality of 62 only, which is very very low.

Maybe you could increase it to a somewhat higher quality value?

How about 80? Or 90? Or someting in between? Or maybe even 100?

Could you please try? It would be much appreciated.

Oh, and another, alternative question:

> @DrKLO wrote:
> 
> Size is critical for android 2.x devices.
> Also loading jpeg is faster then png.
> No other solution for it until I will drop 2.x support.

With "2.x devices" you are referring to Android 2.x devices, aren't you?

So, how about using JPEGs for Android 2.x devices and using PNGs for all later devices (4.x, 5.x, and so on?

Would that be possible?

It would be really nice if you would reply.

After having increased the message font size and then having seen the compression artifacts on the Emojis in Telegram for Android, I can hardly unsee it, even when the Emojis are smaller.

I compared them to some 160x160 PNGs found on the internet, and they look a lot better (cleaner, sharper).

So it would be really nice if you could do something about it.

Regards

**Comment by wp9015362** [comment]
@DrKLO :

TextSecure for Android is also using PNGs, see:

https://github.com/WhisperSystems/TextSecure/tree/master/assets

And it's working fine.

So, please use PNGs for Telegram for Android as well.

It would be much appreciated.

Regards
