### ISSUE TITLE
Feature Request - Create Telegram Account without cellphone sms.

### ISSUE THREAD

**Issue by namoplasta** [DrKLO/Telegram#915]
Create telegram only the username, the code confirmation can be by email.

It is good to be implemented before a competitor implements.

And it will avoid people to use public phones, as they can choose a username and verifying code by email of your choice.

Even if the person does not have a phone number, will serve so that more people using username, talk to each other, even with those who have number and decided to create a username, benefiting desktop users.

Feature important for anyone who does not like to give the mobile number for privacy reasons.

If it is implemented, if the person wants it can add a cellphone number in the future.

**Comment by DrKLO** [comment]
Not client related.
And as result we will get a lot of span accounts.
