### ISSUE TITLE
Like and Noted/OK

### ISSUE THREAD

**Issue by ongray** [DrKLO/Telegram#920]
FEATURE REQUEST

LIKE expression - especially in a group chat, a lot of times we want to show the expression that we like the note posted. It will be good if can just do it with a click/tap (like what wechat have in the moment). save a lot of like too.

NOTED/OK expression - sometime we really lazy to type, we like to just click/tap to tell them we have taken the note. This also save a lot of lines, to save everyone from just typing 'noted'.

**Comment by NGM89** [comment]
Great Idea!

**Comment by DrKLO** [comment]
There is no API for that.
