### ISSUE TITLE
Brazilian number problem with new "9" digit

### ISSUE THREAD

**Issue by rafaelmr2** [DrKLO/Telegram#923]
Hi,

In my region the phone number has changed (now has a new  "9" digit in begin). Now I have 2 accounts and can't delete the old (when I try to delete, telegram service only delete the new account with "9").

I'm from Brazil. Whem people add me, they add the old account (they can't add the new, because this bug).

Thanks.

**Comment by DrKLO** [comment]
Can you email detailed info about your phone number and region to support@telegram.org?

**Comment by rafaelmr2** [comment]
Yes.

**Comment by rafaelmr2** [comment]
Sent.

**Comment by rafaelmr2** [comment]
OK, but I still waiting account migration ;)
