### ISSUE TITLE
Problem with button InviteFriends at Telegram

### ISSUE THREAD

**Issue by Nekbakht** [DrKLO/Telegram#926]
I wanna change text of Invite message. I did this on string.xml and when i first time click the button "inviteFriends" it was my text in message but after 5 minute when i click this button text again "Hey, les/t switch to www.telegram/dI.
Why? can you help me?

**Comment by DrKLO** [comment]
Duplicate. It's getting from server side.

**Comment by Nekbakht** [comment]
And how I can fix it?
