### ISSUE TITLE
Lost control over secret chats after restoring phone to factory

### ISSUE THREAD

**Issue by kastedo** [DrKLO/Telegram#928]
After restoring my phone to factory I reinstalled Telegram and realized that I couldn't access the old secret chats anymore (Actually I knew it would happen, but completely forgot it when I decided to restore to factory). This wouldn't be a problem if there were a way to cancel/delete the old chats from the new intallation or Telegram notified my contacts about the secret chats not being valid anymore. The worst part is that my contacts might be trying to message me on the lost chats and I would never get their messages. I understand the server can't know when a phone is reset to factory, but there should be a manner to cancel the secret chats on all other devices/installations in the same way it is possible to log out from all other devices.

**Comment by DrKLO** [comment]
For now "Terminate all other sessions" should do it. If there will be other way in API to do it, I will implement it.
