### ISSUE TITLE
Send Messager For Various Groups

### ISSUE THREAD

**Issue by Acmsj** [DrKLO/Telegram#929]
Could someone help with a way to send a message to X number of groups at once.
select the groups that the message should be sent

**Comment by Acmsj** [comment]
@DrKLO can you help me?

**Comment by DrKLO** [comment]
First you should implement interface for groups selection, then you should do something like this
for (long dialog_id : selectedDialogs) {
   SendMessagesHelper.getInstance().sendMessage(..., dialog_id);
}

**Comment by Acmsj** [comment]
Sorry I messed up, is to send to all groups that I am the adm

**Comment by Acmsj** [comment]
or all that participate

**Comment by Acmsj** [comment]
@DrKLO

**Comment by Acmsj** [comment]
Sorry I messed up, is to send to all groups that I am the adm or all of which i participating. in the case would be when I send a message to any group she go for all groups @DrKLO
