### ISSUE TITLE
what principal difference between android Fragment and yours BaseFragment? And what need to insert new subBaseFragment in lifecycle?

### ISSUE THREAD

**Issue by Sergey63** [DrKLO/Telegram#931]
I want insert new Fragment which can be accessed from ChatActivity. I create new MyFragment extends BaseFragment. How i can correctly insert it into lifecycle? What to look for?

**Comment by DrKLO** [comment]
I don't want to use android fragments with its support library because it's full of crashes on old devices and functional limitations. 
Use presentFragment.
