### ISSUE TITLE
Feature Request: Live Help / Live Support System

### ISSUE THREAD

**Issue by serialpsychokillerfromhell** [DrKLO/Telegram#932]
Please, think about the possibility of implementing the Telegram with functions similar to the following applications:

Firehose:
Site: https://firehosechat.com/
App: https://play.google.com/store/apps/details?id=com.mysterioustrousers.firehose.chat

Zopim:
Site: https://www.zopim.com/
App:https://play.google.com/store/apps/details?id=com.zopim.android&hl=en

LiveZilla:
Site: http://www.livezilla.net/home/en/
App: https://play.google.com/store/apps/details?id=net.livezilla.mobile.client&hl=en

**Comment by DrKLO** [comment]
Not client related.
