### ISSUE TITLE
Emoji keyboard doesn't cover virtual keyboard completely

### ISSUE THREAD

**Issue by jackgu1988** [DrKLO/Telegram#936]
At least on the Google keyboard, if the keyboard is visible and I tap the emoji button, the emoji drawer doesn't cover the keyboard completely. Two ways of fixing it:

1. When the emoji button is tapped, hide the virtual keyboard first.

2. Check the view size and compare it to the screen size. If the view size is smaller, a keyboard should be active, so  make the emoji drawer as big as the difference between the two sizes.

**Comment by DrKLO** [comment]
It's will be fixed in next version.
