### ISSUE TITLE
Duplicate Notifications

### ISSUE THREAD

**Issue by pixelpoesie** [DrKLO/Telegram#937]
When iam writing and recieving messeges on the Desktop Client, the Android Client still gives me notifications, and my phone is constantly peeping and blinking. The only way ti fix it, is to disable notifications on my phone.

**Comment by DrKLO** [comment]
Duplicate.

**Comment by pixelpoesie** [comment]
Sorry. I did not find an issue like this. could you provide me a link? Thanks!

**Comment by auchri** [comment]
#768 and #561 for example
