### ISSUE TITLE
How to add webView to show image on menu of telegram

### ISSUE THREAD

**Issue by Nekbakht** [DrKLO/Telegram#938]
I added this on DraverActionCells.java

        addView(webView);
       
       webView.setLayoutParams(layoutParams);
   

   
    public void setWebView (String link)
    {
        webView.loadUrl(link);
    }

on
i add this
 else if (i == 9) {
                //actionCell.setTextAndIcon(LocaleController.getString("TelegramFaq", R.string.TelegramFaq), R.drawable.menu_help);
                actionCell.setWebView("http://nek.tioo.ru/r.png");
            }

but when i run i have error why?

**Comment by DrKLO** [comment]
Which error?

**Comment by Nekbakht** [comment]
Application closing
