### ISSUE TITLE
How can i remove invite friends?

### ISSUE THREAD

**Issue by omarkerr** [DrKLO/Telegram#942]
how can i remove invite friends and make sure it doesn't display any at all i tried by editing string.xml and DawerLayoutAdapter.java but it still has the action without text and a big gap see image blow
![photo278520933020444632](https://cloud.githubusercontent.com/assets/10163450/6837630/a3d668a6-d31c-11e4-9f98-0e5000419b34.jpg)

**Comment by DrKLO** [comment]
You should learn how to work with Adapters. Everything you need is in DawerLayoutAdapter.java.

**Comment by omarkerr** [comment]
thank you
