### ISSUE TITLE
Messages sending to both the apps which is not fine

### ISSUE THREAD

**Issue by shivasrinath** [DrKLO/Telegram#944]
we had customized telegram app.People who are going to use the our customized app are already having the telegram.When I send message in my app it been delivering to both the apps.But I don't want to it to happen.If I send message to the contact from our app then he should receive message on our app only but not also on the telegram app.

**Comment by AUDI-A4** [comment]
@shivasrinath i think this is not possible. To make this happen, You should have your own server.
