### ISSUE TITLE
Music paused when sending a message, phone in silent mode. 

### ISSUE THREAD

**Issue by pharno** [DrKLO/Telegram#947]
Versions
-----------
Android: 4.3
Model Number GT-N7105 (galaxy note 4)
Telegram 2.6.1 (475)

Expected behavior
------------------------
When the phone is set to silent mode (not vibrate), and music is on, telegram should not pause the music when sending a message.

Actual behavior
-------------------
The music is muted for a short time. I think the duration is about the same as if the phone was on loud mode.

Steps to reproduce
-------------------------
- Start music (Standard music app or spotify)
- set phone to silent
- open telegram and send a message
- music was paused

Additional informations
------------------------------
This only occures since today, maybe since yesterday. Notification settings within telegram have not been touched. Girlfriend has the same issue, different phone (galaxy s4). we both use the stock rom, im using spotify, her the stock music app.

**Comment by DrKLO** [comment]
I don't have this issue on Android 4.4, 5.0 and 5.1. For now you can disable in-chat sounds in notifications settings.

**Comment by DrKLO** [comment]
Can you test debug build (note: you need uninstall current market version to install this one) https://rink.hockeyapp.net/apps/a5b5c4f551dadedc9918d9766a22ca7c/app_versions/537
and tell me is it was fixed or not?

**Comment by pharno** [comment]
jup, seems fixed.

**Comment by pharno** [comment]
gf just reported that disabling chat sounds also works. Also, other messengers (whatsapp) seem to work find, only happens with telegram.

**Comment by DrKLO** [comment]
I uploaded update to Play Market 2.6.1 (479). Thanks for report.

**Comment by pharno** [comment]
thanks :)

just another question, where can I see the commit for it? master is old, and dev has not been updated since half a day.
