### ISSUE TITLE
What's Y-Land on countries list?

### ISSUE THREAD

**Issue by cgomezmendez** [DrKLO/Telegram#949]
https://github.com/DrKLO/Telegram/blob/master/TMessagesProj/src/main/assets/countries.txt#L215
is this some kind of eagster egg? i searched for Y-Land without any related result, but country code seems to be of Czechoslovakia until its breakup.
http://en.wikipedia.org/wiki/List_of_country_calling_codes

**Comment by DrKLO** [comment]
It's our little secret.
