### ISSUE TITLE
New "In-Chat Sounds" introduced with Telegram for Android version 2.6.1 do not work reliably and also are very quiet

### ISSUE THREAD

**Issue by wp9015362** [DrKLO/Telegram#953]
Hello @DrKLO ,

first of all:

Thank you very much for the new "In-Chat Sounds" option, which was requested in https://github.com/DrKLO/Telegram/issues/549 and https://github.com/DrKLO/Telegram/issues/734 and which you now have added in Telegram for Android version 2.6.1 in which it is available from Settings -> Notifications and Sounds -> In-app notifications -> In-Chat Sounds!

Much appreciated!

But:

The sounds do not work reliably and are very quiet.

The Google Play Store changelog for Telegram says:

> Added sounds for outgoing and incoming
> messages in the currently opened conversation
> (can be disabled in notification settings)

And there indeed seems to be a sound for both incoming as well as outgoing messages when Settings -> Notifications and Sounds -> In-app notifications -> In-Chat Sounds are enabled.

But the sounds only work sporadically, most of the time there is no sound.

And the sounds are also very quiet.

Can you please fix that?

Regards

**Comment by AUDI-A4** [comment]
One thing is incoming and outgoing chat sound both are having same sound.It should be different sound for incoming message and outgoing message like in whatsapp

**Comment by wp9015362** [comment]
> @AUDI-A4 wrote:
> 
> One thing is incoming and outgoing chat sound both are having same sound.
> It should be different sound for incoming message and outgoing message
> like in whatsapp

I'm not entirely sure (because the sounds are so quiet and short), but I think the the outgoing sound actually is different from the incoming sound. They seem to be similar but different.

But, again, maybe the sounds are just too short and too quite to tell.

Anyway:

Do the sounds always work for you?

For me they only work sporadically. Sometime the sounds appear. But most of the time the sounds do not appear.

And they are very quiet.

Even if I am putting the volume of the device to maximum, they are still very quiet.

**Comment by AUDI-A4** [comment]
@wp9015362 yes voice is too low.One more thing, it is producing outgoing message sound  without message being sent.For example, if you are sending a message but not connected to internet then clock icon will appear below the msg.outgoing sound should be appeared of outgoing msg when the message is having single tick means message is sent like whatsapp

**Comment by AUDI-A4** [comment]
@DrKLO one more thing i noticed.While chatting with someone,Both incoming and outgoing in chat sounds Stop working for a while.Please test and confirm by yourself @DrKLO and if possible then pleasefix in the next release

**Comment by AUDI-A4** [comment]
No in chat sounds produced for images,file and videos.Outcoming sound should not be produced untill message is sent to somebody not in clock icon

**Comment by AUDI-A4** [comment]
@Drklo if you are sending first msg to someone then most of time in chat sounds does not produced. if you are using headphone then no chat sounds produced for any msg. Without headphone, no chat sounds produced for image,file and video.Please fix in the next release, i am getting habitual of the sounds.Love your work

**Comment by harryd100** [comment]
Hi, is this issue solved? I'm running the latest version (2.9.1) and still no chat-sounds.

**Comment by AUDI-A4** [comment]
Please increase the system sounds in your mobile if it is low. I dont have any problem with chat sounds.but compared to whatsapp it is quite low.

**Comment by harryd100** [comment]
@AUDI-A4 I have turned up the volume all to maximum level and still do not hear any sound when a chat is updated. Even with a headset I hear nothing. I'm using a HTC Desire 610.

**Comment by AUDI-A4** [comment]
With headset you cannot hear, there is problem in app  while using headset
