### ISSUE TITLE
[Request] Add Catalan translation to built-in languages

### ISSUE THREAD

**Issue by jmontane** [DrKLO/Telegram#955]
Hi,

Catalan translation [1] is finished and updated. I've tested it and all looks fine. It follows Telegram translation guide available here [2].

So, I think it's ready to be distributed built-in in app.

[1] https://www.transifex.com/projects/p/telegram/language/ca/
[2] https://core.telegram.org/translating_telegram

**Comment by DrKLO** [comment]
I don't accept Translations on github. Ask our support about it.
