### ISSUE TITLE
Wrong localization used in "Invite friend" string

### ISSUE THREAD

**Issue by jmontane** [DrKLO/Telegram#956]
String used by "Invite friends" menu is not translated with strings.xml, but it's translated in some other (wrong?) way.

I'm a Catalan user, with an Android phone in Catalan, using an Spanish carrier.

If Telegram is in English (default), I push "Invite friends" and I select Gmail, string shown is "Oye, cambiémonos a Telegram: https://telegram.org/dl". Which is in Spanish!!!? but my phone has nothing set in Spanish! why string in Spanish is used?

If I download and use Catalan translation file from Transifex, same behaviour. String is in Spanish??!!! But this string is not found in Catalan strings.xml file.

So, Spanish string is hardcoded somewhere out from "strings.xml" and it can not be localized following phone and Telegram locale set.

Just a related remark,
If I select a non Telegram user from contacts list, and I send an SMS invitation, this string is properly localized. Telegram shows "Hey, let's swith to Telegram: https://telegram.org/dl" in English (default) and "Ep, canvieu al Telegram: https://telegram.org/dl" in Catalan. So it's well localized in this case.

**Comment by DrKLO** [comment]
It's getting from server, so not client related.

**Comment by jmontane** [comment]
Closed?

IMHO it's a client issue too.

Android client uses the same string in two places, but its localized in different way(!!). 
In one place, it's localized requesting the translation to server.
In other one, it's localized using resource strings.xml

So, I think its clearly an issue client.
