### ISSUE TITLE
Upgrade for mentions in group

### ISSUE THREAD

**Issue by St-dimka** [DrKLO/Telegram#962]
Thank you for added function mentions in the group chats. But I have a proposal for its upgrade: will be easier if incoming @username will be converted to first and last name .
Choice username by entering @ is not convenient. It will be convenient if username will be selected after clicking on the message of this user.

**Comment by kofp** [comment]
+1

**Comment by AUDI-A4** [comment]
+1

**Comment by Aleks006** [comment]
+1

**Comment by DrKLO** [comment]
Every user have its own first name and last name for every contact, so it's not possible.

**Comment by St-dimka** [comment]
I mean own names.
I have contacts in Ivan Ivanov. Someone mentions his @Ivanov. My telegram converts @username in Ivan Ivanov.
Such action is already making a telegram when I enter @. He offers me @username, name and surname. Why not do it in incoming messages?

**Comment by St-dimka** [comment]
У меня ужаснейший английский, удалите это сообщение, если так делать нельзя(писать по-русски). Но я боюсь дальнейших непониманий.
Не у всех людей понятные имена пользователей. Я встречал и @babnick, и @kaknadodelat. Когда к таким людям обращаются - многие не помнят кто это. Приходится шерстить все контакты, дабы найти этого человека.
Почему бы не преобразовывать полученный ник автоматически в имя и фамилию такие, которые записаны у меня в контактах? А у других, соответственно, так как у них записано. Пусть это делает программа, а передаётся в сообщении тот же @username.
Такое действие уже умеет делать telegram когда я ввожу @. В этом случае он предлагает мне @username'ы, а правее имя и фамилию - кто это. Именно так, как они у меня записаны.
Вот, кстати, это вы почему-то проигнорировали: постоянный набор собаки для обращения к человеку очень неудобен. Чисто механически это медленно. Гораздо быстрее было бы, если обратиться к человеку можно было просто тапнув по его сообщению в чате. Там во всплывающем меню просто добавить строку "Обращение" которая вставит в поле ввода @username, относящийся к этому человеку

**Comment by DrKLO** [comment]
@St-dimka 
1) зачем искать среди всех контактов, когда можно просто нажать на юзернейм и откроется профиль?
2) что-то преобразовывать это серверная задача, это не ко мне. Но я сомневаюсь что кто-то будет делать такие усложнения, при том что контакты можно переименовывать. И вся логика уже ломается. Клиент ничего не знает о юзернейме до того, как пользователь кликнет на него, чтобы заменять на своей стороне.

Именно по юзернейму сервер определяет, что здесь есть обращение к какому-то человеку и добавляет флаг к сообщению, чтобы затем если уведомление у человека отключены, ему оно все равно пришло. С именами такое сделать просто нереально.

В общем другими словами: останется так, как есть сейчас.

**Comment by St-dimka** [comment]
так ведь сейчас такое преобразование со стороны клиента существует! Когда я набираю @ - программа советует мне @username1 - Фамилия Имя; @username2 - Фамилия Имя и т.п.
Почему бы не сделать такое преобразование на стороне клиента во входящих сообщениях? Не затронется сервер, флаги и никакая логика.
Клиент увидел в тексте "@ivanov," посмотрел по той же базе, подменил на "Иван Иванов,".
Если же люди будут пересылать сообщения или цитировать их с ответом, то в тексте сообщения будет передаваться не имя и фамилия, а тот же @username и подставляться у каждого клиента по своему в соответствии с контактным листом.
