### ISSUE TITLE
Source code a little outdated

### ISSUE THREAD

**Issue by nastys** [DrKLO/Telegram#963]
Hi, I just noticed that the source code here is outdated compared to the Play Store APK.
For instance, the Play Store version has both in and out chat sounds, while a build from the source code only plays the out sound, even if I put my sound_in.wav file.
https://github.com/DrKLO/Telegram/tree/dev/TMessagesProj/src/main/res/raw

NOTE: this is NOT a duplicate of #930 ; I'm talking about the dev branch.
The APK generated from the source code shows build 475, while the Play Store version shows build 479.

**Comment by DrKLO** [comment]
Just wait until I will update source code.
