### ISSUE TITLE
Feature Request - Hide chat contents from app switcher

### ISSUE THREAD

**Issue by gabrielbauman** [DrKLO/Telegram#966]
When switching between apps, the contents of chats are visible in Telegram's thumbnail. 

TextSecure has the option to keep chat contents from appearing in the switcher. It would be great to have that option in Telegram.

**Comment by DrKLO** [comment]
It's not possible. flag_secure is very buggy on some devices.

**Comment by gabrielbauman** [comment]
So,  because "some devices" are buggy, the rest of us have to go without?

Seems like something that should be done on a "best effort" basis. Just because a feature may not work on all devices shouldn't mean it must be left out. 

Make it obvious to the user that flag_secure might not work as expected, but at least give them the option of enabling it.

**Comment by DrKLO** [comment]
Yes, because there 9000 different android devices and i will not going to check every single device.

**Comment by gabrielbauman** [comment]
No one is asking you to check "9000 android devices".

Give the user an option to set flag_secure. If they choose to enable it, let them know that it might not work as expected and that the feature is provided as-is.

Simple! No ongoing burden for you and those of us whose devices handle flag_secure would gain a useful feature.
