### ISSUE TITLE
Feature Request - Upgrade standard chat to secret chat

### ISSUE THREAD

**Issue by gabrielbauman** [DrKLO/Telegram#967]
Would be neat to have the option to "upgrade" a standard chat to a secret chat. Maybe a button on the toolbar.

This could be presented as a request to the other user requiring their consent, or the request could be honored immediately without approval. 

Insecure chat history would have to be highlighted as such, and a marker should appear to indicate where secure chat began.

**Comment by DrKLO** [comment]
It's not possible.

**Comment by gabrielbauman** [comment]
Even if you made it clear that going to secret mode would pin the conversation to the device in hand? Hmm.
