### ISSUE TITLE
Voicechat Functionality

### ISSUE THREAD

**Issue by db2k** [DrKLO/Telegram#970]
Hello,

with the latest update Whatsapp introduced in-app voicecalls. I think this could be possible with telegram too. Are there any plans for now? It would be super cool since you could call from your firefox os, browser or your windows app too.

Thanks for every information!

**Comment by jlelse** [comment]
+1

**Comment by DrKLO** [comment]
Not client related.

**Comment by db2k** [comment]
@DrKLO where we can suggest not only client related features?

**Comment by DrKLO** [comment]
@db2k Twitter or support.

**Comment by auchri** [comment]
Read the faq: https://telegram.org/faq#q-can-i-make-calls-or-video-calls-via-telegram
