### ISSUE TITLE
Error while compiling Telegram source code in Android Studio

### ISSUE THREAD

**Issue by sagarmred** [DrKLO/Telegram#972]
I've checked out Telegram source code from Github to Android Studio,and got an error while compiling.

Error:A problem was found with the configuration of task ':TMessagesProj:packageDebug'.
> File 'C:\Users\Sagar\AndroidStudioProjects\Telegram\TMessagesProj\config\debug.keystore' specified for property 'signingConfig.storeFile' does not exist.

What do I do to solve this?
Is there any other working way for Importing and Compiling Telegram Source Code?

Thanks in advance.

**Comment by DrKLO** [comment]
Use search.
