### ISSUE TITLE
Service Notification name change

### ISSUE THREAD

**Issue by friend4chams** [DrKLO/Telegram#976]
Please help me with service notification for MyApp , e.g.
A text or code is received from +42777 or Telegram it shows the name 'Telegram' ,  it should show MyApp name e.g MyApp Notifications or just MyApp
If it is service side, is there a way to change to to MyApp name inside codes?

Please help i searched for this , i did not find it.

**Comment by DrKLO** [comment]
It's getting from server.

**Comment by friend4chams** [comment]
Yes as i said if it is from server side then there may be any solution for it.
And i can see on https://core.telegram.org/api/obtaining_api_id 
2. Please don't use the name Telegram for your app or make sure you have the word unofficial in the title.
3. Please do not use the official Telegram logo (white paper plane in a blue circle) in your app.

and here you are your self imposting the same Title and Image in mean of text. atleast this should be changed from server side and name should be the same which we gave during api creation,
