### ISSUE TITLE
[FEATURE REQUEST]  Keep both Name & Telephone number hidden when only Username is shared

### ISSUE THREAD

**Issue by paratraveler** [DrKLO/Telegram#980]
Currently, one's tele number is not shared with someone who has been given only your username; unless the new contact also has you in their phone's contacts list. 

Make it so that the Telegram 'Name' fields info is kept hidden, also, when a user has only contacted you via your username & doesn't have you in their phone's contact list.

**Comment by DrKLO** [comment]
Not client related.
