### ISSUE TITLE
Emoji drawer seems to draw over all other view on the screen. Even system views like Notification drawer.

### ISSUE THREAD

**Issue by shnr33** [DrKLO/Telegram#981]
Also this can be noticed while using blue-light filtering apps like Twilight, where the the emoji drawer won't be covered in the red overlay.
OS - Android 5.0.1
Device - Nexus 4

![telegram_emoji_over_notification](https://cloud.githubusercontent.com/assets/6046850/7001090/6f5eb92a-dc4f-11e4-841c-e35e973f75c9.png)

**Comment by DrKLO** [comment]
Duplicate, it's workaround for android 5.x bug.
