### ISSUE TITLE
Telegram Apps confusing each other, SERVER ISSUES THAT NEED URGENT ATTENTION

### ISSUE THREAD

**Issue by emahuni** [DrKLO/Telegram#983]
Guys, thank you very much for this wonderful API, it rocks.

There are a few issues that you should address on the server side. I got source files for Telegram, installed Telegram on my phone and Desktop and then I installed ZapZap Messanger, an implementation of the Telegram API. I wanted to see what that Telegram App had done with the code. 

It sent an SMS from Telegram when I was activating the ZapZap app. That in itself can confuse users who are not aware ZapZap , Telegram or any other Telegram App use the same API. 

Then I noticed that the contacts I have in Telegram were the same in ZapZap . I was expecting ZapZap to have one or two contacts in the account if at all.

Then I noticed that my own name was now included as a contact in my own account.

On my desktop it then said that someone has logged into my Telegram account from another device or something along those lines. This was fine when it was just Telegram alone.

In Telegram, the Telegram contact had changed to ZapZap and other things were just mixed up.

My point is that, if Telegram is going to be widely used, Apps should be completely different and not be connected at all. Imagine if 4 apps implement the Telegram API on one device from one user? That's havoc.

To my understanding this is a server-side issue. I think on the server-side you are supposed to use the API-ID to distinguish apps so that they don't confuse each other. So that the server doesn't send things assuming it is sending to the Telegram APP or some other APP implementing it. Please use the information that developers submit when creating the API_ID. That matters if the Telegram API is going to take a foothold in the messaging arena. We don't want to confuse users. That can actually pull your efforts down. Unfortunately these are bugs we can't fix as a community in GitHub. I think it is better if you guys release the server source code so we help with these issues.

I have read where you mentioned that you keep the server to maintain on security and other implementation issues etc, but it then boils down to one thing, what is done with the data that is sent to your servers, what do you or what does the server do with the data? It just leaves everyone in the proprietary woes and in the shadows again. 

Again thank you so much, I love this API and your vision, but please make it completely open.

**Comment by friend4chams** [comment]
I agree with you. this must be implemented, each api separate  with a path, if contacts are same not matter name should be differentiated. that which app they are actually using. and From notification name  (Telegram) name should be matching to our API app name.

**Comment by DrKLO** [comment]
Not client related issue.
In my opinion developers of unofficial clients responsible for telling users that their apps using Telegram servers or they should implement they own servers.
I don't think that it's cheap to support infrastructure (buy servers, pay for sms and traffic, etc) for every single unofficial client.
