### ISSUE TITLE
can not compile telegram dev

### ISSUE THREAD

**Issue by spyexe** [DrKLO/Telegram#984]
Hello I have this error in android studio 
Error:A problem was found with the configuration of task ':TMessagesProj:packageDebug'.
> File 'C:\Users\Ali\Downloads\Compressed\Telegram-dev_2\Telegram-dev\TMessagesProj\config\debug.keystore' specified for property 'signingConfig.storeFile' does not exist.
how to fix this error ???

**Comment by AUDI-A4** [comment]
https://github.com/DrKLO/Telegram/issues/34
