### ISSUE TITLE
'Telegram' folder name change inside File manager

### ISSUE THREAD

**Issue by friend4chams** [DrKLO/Telegram#985]
I want to use MyApp name inplace of 'Telegram' name on the folder which is created after installation of MyApp.  And all folder inside 'Telegram' directory e.g. MyApp Audio , MyApp Documents etc

I saw some other apps which are using Telegram API they got their own name on the folder.

Which file to edit ?  i can not find it. I have changed all 'Telegram' names to MyApp but still when i install MyApp the 'Telegram' named folder creates.

**Comment by DrKLO** [comment]
ImageLoader.java, createMediaPaths function.

**Comment by friend4chams** [comment]
Thank you, it worked.
