### ISSUE TITLE
alternative registration identifier & crawl not

### ISSUE THREAD

**Issue by TameOfGroans** [DrKLO/Telegram#987]
For those who neither have- nor tolerate sms texting what other identifier could be used for account registration?

■ Xmpp Texting JID?
■ nick?
■ SIP URI?

While I understand how some might deem it beneficial to have app/platform peruse contacts to find peers also using service I shall not be allowing that. Will there be an option to opt out of contacts crawling in the proximate future?

**Comment by DrKLO** [comment]
Not client related question. I don't think that there will be any other options to create account, because in other way we will get a lot of spam accounts.

**Comment by TameOfGroans** [comment]
Where ought one post server issues?

**Comment by AleixDev** [comment]
[Twitter](https://telegram.org/faq#twitter) or [support](https://telegram.org/faq#telegram-support)
