### ISSUE TITLE
Why at telegram don`t working find image by web

### ISSUE THREAD

**Issue by Nekbakht** [DrKLO/Telegram#989]
when i typed some things on find web editor and click enter i see just no result

why ?
what i need to fix on my code?

**Comment by yudin80849** [comment]
https://github.com/DrKLO/Telegram#usage be sure that you've filled this https://github.com/DrKLO/Telegram/blob/master/TMessagesProj/src/main/java/org/telegram/messenger/BuildVars.java#L18
